# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/unit/_utils/test_fzf_guard.pct.py

__all__ = ['test_both_wrappers_refuse_before_launching_fzf', 'test_duplicate_display_terms_are_refused', 'test_duplicates_after_stripping_are_refused', 'test_mismatched_lengths_are_refused', 'test_unique_display_terms_are_fine']

# %% pts/tests/unit/_utils/test_fzf_guard.pct.py 3
import pytest

from boxyard._utils.base import _reject_ambiguous_disp_terms, run_fzf, run_fzf_multi

# %% pts/tests/unit/_utils/test_fzf_guard.pct.py 5
def test_unique_display_terms_are_fine():
    _reject_ambiguous_disp_terms(["a", "b"], ["x (1)", "x (2)"])

# %% pts/tests/unit/_utils/test_fzf_guard.pct.py 7
def test_duplicate_display_terms_are_refused():
    # TESTREF: test_fzf_rejects_duplicate_display_terms
    with pytest.raises(ValueError) as excinfo:
        _reject_ambiguous_disp_terms(["a", "b"], ["same", "same"])
    assert "same" in str(excinfo.value)


def test_duplicates_after_stripping_are_refused():
    """The lookup strips, so the check must strip too."""
    with pytest.raises(ValueError):
        _reject_ambiguous_disp_terms(["a", "b"], ["same", "  same  "])

# %% pts/tests/unit/_utils/test_fzf_guard.pct.py 9
def test_mismatched_lengths_are_refused():
    with pytest.raises(ValueError):
        _reject_ambiguous_disp_terms(["a"], ["x", "y"])

# %% pts/tests/unit/_utils/test_fzf_guard.pct.py 11
def test_both_wrappers_refuse_before_launching_fzf(monkeypatch):
    def _explode(*args, **kwargs):
        raise AssertionError("fzf was launched despite ambiguous display terms")

    monkeypatch.setattr("subprocess.run", _explode)

    with pytest.raises(ValueError):
        run_fzf(terms=["a", "b"], disp_terms=["same", "same"])
    with pytest.raises(ValueError):
        run_fzf_multi(terms=["a", "b"], disp_terms=["same", "same"])
