# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/unit/cmds/test_doctor_hints_are_runnable.pct.py

__all__ = ['test_hints_contain_commands', 'test_suggested_command_parses']

# %% pts/tests/unit/cmds/test_doctor_hints_are_runnable.pct.py 3
import ast
import inspect
import re
import shlex

import click
import pytest
import typer

import boxyard.cmds._doctor as _doctor_module
from boxyard._cli.app import app


# A hint is a template: `{box_index_name}` and the like are filled in at
# runtime. Substituting a plausible value keeps shlex and click honest without
# pretending the placeholder is real.
_PLACEHOLDER = "PLACEHOLDER"

_COMMAND_RE = re.compile(r"`(boxyard [^`]*)`")


def _literal_strings(source: str) -> list[str]:
    """
    Every string literal in the module, with f-string holes filled in.

    Adjacent literals are concatenated by the PARSER, so a hint split across
    several `f"..."` fragments arrives here as one string — which is exactly the
    shape the broken hint had.
    """
    out: list[str] = []
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            out.append(node.value)
        elif isinstance(node, ast.JoinedStr):
            text = ""
            for part in node.values:
                if isinstance(part, ast.Constant) and isinstance(part.value, str):
                    text += part.value
                else:
                    text += _PLACEHOLDER
            out.append(text)
    return out


def _suggested_commands() -> list[str]:
    source = inspect.getsource(_doctor_module)
    commands = set()
    for literal in _literal_strings(source):
        for match in _COMMAND_RE.finditer(literal):
            commands.add(match.group(1).strip())
    return sorted(commands)

# %% pts/tests/unit/cmds/test_doctor_hints_are_runnable.pct.py 5
def test_hints_contain_commands():
    commands = _suggested_commands()
    assert len(commands) >= 10, commands
    # TESTREF: test_doctor_hints_are_runnable
    assert any("--sync-direction" in c for c in commands), (
        "the diverged-box hint was not extracted, so the case this test exists "
        "for is not covered"
    )

# %% pts/tests/unit/cmds/test_doctor_hints_are_runnable.pct.py 7
@pytest.mark.parametrize("command", _suggested_commands())
def test_suggested_command_parses(command):
    cli = typer.main.get_command(app)
    argv = shlex.split(command)[1:]  # drop the leading "boxyard"
    assert argv, command

    name, *args = argv
    sub = cli.commands.get(name)
    assert sub is not None, f"`{command}` names a subcommand that does not exist"

    try:
        # PARSE only. Several of these commands do real work; make_context
        # validates flags and values without invoking anything.
        sub.make_context(name, list(args), resilient_parsing=False)
    except click.MissingParameter:
        # A bare mention like `boxyard copy` is a template, not a full command.
        # Missing a required option is fine; a WRONG one is not.
        pass
    except click.exceptions.Exit:
        pass
    except click.UsageError as e:
        pytest.fail(f"`{command}` does not parse: {e}")
