# AUTOGENERATED! DO NOT EDIT! File to edit: pts/mod/_fingerprint.pct.py

__all__ = ['FINGERPRINT_VERSION', 'base_path_for', 'clear_base', 'filter_signature', 'local_tree_differs', 'read_base', 'tree_fingerprint', 'write_base']

# %% pts/mod/_fingerprint.pct.py 3
import hashlib
import json
import os
import stat as stat_mod
from pathlib import Path

from . import const


FINGERPRINT_VERSION = 1
"""Bumped when the digest's INPUTS change, so old sidecars read as unusable
rather than being compared against a digest computed a different way."""

# %% pts/mod/_fingerprint.pct.py 4
def filter_signature(
    exclude_path: "str | Path | None",
    include_path: "str | Path | None" = None,
    filters_path: "str | Path | None" = None,
) -> str:
    """
    A digest of the ACTIVE filter rules, so changing scope forces a reconcile.

    Blank lines and whole-line comments are normalised away, so reformatting a
    comment does not churn every box. This is not a reimplementation of rclone's
    matching -- it only has to change when the rules change.
    """
    parts: list[str] = []
    for label, path in (
        ("exclude", exclude_path),
        ("include", include_path),
        ("filters", filters_path),
    ):
        if path is None:
            continue
        try:
            text = Path(path).read_text(encoding="utf-8")
        except FileNotFoundError:
            continue
        rules = [
            ln.strip()
            for ln in text.splitlines()
            if ln.strip() and not ln.strip().startswith("#")
        ]
        parts.append(f"{label}:" + "\n".join(rules))
    digest = hashlib.sha256("\n--\n".join(parts).encode("utf-8")).hexdigest()
    return digest[:32]

# %% pts/mod/_fingerprint.pct.py 5
def tree_fingerprint(
    path: "str | Path",
    exclude_names: "set[str] | None" = None,
    *,
    filter_sig: str = "",
) -> "str | None":
    """
    A digest of everything under `path` that the transport would compare.

    Returns None ONLY when the root does not exist -- "there is no tree here",
    which the caller's existence logic must answer, not this function. An
    existing but EMPTY tree digests to a real, stable value, so emptying a box
    is a change like any other and its deletions propagate.

    Per entry: the relative path, the kind, the size, the mtime in nanoseconds,
    and -- for regular files -- the owner-execute bit. For symlinks, the target
    string instead of a size, because the target IS what rclone writes into the
    `.rclonelink` file, making this the transport's own view rather than a guess
    about symlink semantics.

    Entries are hashed individually and the digests sorted before the final
    hash, so memory stays bounded on a box with hundreds of thousands of files
    rather than holding every path tuple at once.

    An unreadable directory RAISES, exactly as `check_last_time_modified` does
    and for the same reason: swallowing it would shrink the tree, and a smaller
    tree hashes to a digest that says "unchanged" about files it never looked
    at. A directory that vanishes mid-walk is a legitimate race and tolerated.
    """
    exclude_names = exclude_names or set()
    root = Path(path).expanduser().resolve()
    if not root.exists():
        return None

    entry_digests: list[str] = []

    def record(rel: str, kind: str, size_or_target, mtime_ns: int, execbit: str) -> None:
        line = f"{rel}\0{kind}\0{size_or_target}\0{mtime_ns}\0{execbit}"
        entry_digests.append(hashlib.sha256(line.encode("utf-8", "surrogateescape")).hexdigest())

    if root.is_file():
        st = root.lstat()
        record(root.name, "file", st.st_size, st.st_mtime_ns,
               "x" if st.st_mode & stat_mod.S_IXUSR else "-")
    else:
        stack = [str(root)]
        while stack:
            current = stack.pop()
            try:
                entries = list(os.scandir(current))
            except FileNotFoundError:
                continue
            except OSError as e:
                raise OSError(
                    f"Cannot fingerprint '{root}': '{current}' could not be read "
                    f"({e}). Fix the permissions, or exclude it from the box."
                ) from e

            for entry in entries:
                if entry.name in exclude_names:
                    continue
                rel = Path(entry.path).relative_to(root).as_posix()
                try:
                    st = entry.stat(follow_symlinks=False)
                except FileNotFoundError:
                    continue
                if stat_mod.S_ISLNK(st.st_mode):
                    try:
                        target = os.readlink(entry.path)
                    except OSError:
                        continue
                    record(rel, "symlink", target, st.st_mtime_ns, "-")
                elif entry.is_dir(follow_symlinks=False):
                    # Directories are descended into but NOT recorded: rclone
                    # does not sync empty directories, and recording them would
                    # let an excluded file's arrival move a directory mtime and
                    # so change the digest -- the .DS_Store false positive this
                    # design exists to avoid.
                    stack.append(entry.path)
                elif entry.is_file(follow_symlinks=False):
                    record(rel, "file", st.st_size, st.st_mtime_ns,
                           "x" if st.st_mode & stat_mod.S_IXUSR else "-")
                # Anything else (fifo, socket, device) is skipped, matching what
                # rclone will transfer -- parity, not an omission.

    entry_digests.sort()
    h = hashlib.sha256()
    h.update(f"v{FINGERPRINT_VERSION}\0{filter_sig}\0".encode("utf-8"))
    for d in entry_digests:
        h.update(d.encode("ascii"))
    return h.hexdigest()

# %% pts/mod/_fingerprint.pct.py 6
def base_path_for(local_sync_record_path: "str | Path") -> Path:
    """
    Where the sidecar lives, derived from the record it describes.

    Deriving it keeps `get_sync_status` a pure function of the paths it is
    already given, and makes all three parts (DATA, META, CONF) get the same
    treatment with no special-casing -- they all go through the same helper.
    """
    p = Path(local_sync_record_path)
    return p.with_name(p.name.removesuffix(".rec") + const.BOX_SYNC_BASE_SUFFIX)


def read_base(local_sync_record_path: "str | Path") -> "dict | None":
    """
    The recorded baseline, or None if there is not a usable one.

    Corruption, a version bump and absence all read as None -- the SAME
    "no usable baseline" answer -- because every one of them means the same
    thing operationally: this machine cannot prove what the tree looked like at
    the last sync, so it must go and find out. That is loud (it forces a
    reconcile), never silent.
    """
    p = base_path_for(local_sync_record_path)
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError, UnicodeDecodeError):
        return None
    if not isinstance(data, dict):
        return None
    if data.get("version") != FINGERPRINT_VERSION:
        return None
    if not isinstance(data.get("fingerprint"), str):
        return None
    if not isinstance(data.get("sync_record_ulid"), str):
        return None
    return data


def write_base(
    local_sync_record_path: "str | Path",
    *,
    sync_record_ulid: str,
    fingerprint: str,
    filter_sig: str,
) -> Path:
    """
    Record the baseline atomically, bound to the record it describes.

    Atomic because a torn sidecar that happened to parse would be the one
    genuinely dangerous outcome -- a digest that says "unchanged" about a tree
    that changed. Temp file plus `os.replace`, the same way the check records
    are written.
    """
    p = base_path_for(local_sync_record_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "version": FINGERPRINT_VERSION,
        "sync_record_ulid": str(sync_record_ulid),
        "filter_signature": filter_sig,
        "fingerprint": fingerprint,
    }
    tmp = p.with_name(p.name + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    os.replace(tmp, p)
    return p


def clear_base(local_sync_record_path: "str | Path") -> None:
    """Remove the sidecar. Absence is fine -- this is used on teardown paths."""
    base_path_for(local_sync_record_path).unlink(missing_ok=True)

# %% pts/mod/_fingerprint.pct.py 7
def local_tree_differs(
    *,
    local_path: "str | Path",
    local_sync_record_path: "str | Path",
    local_sync_record_ulid: "str | None",
    exclude_names: "set[str] | None",
    filter_sig: str,
) -> "bool | None":
    """
    Has this machine's tree changed since the sync the baseline describes?

    True / False when it can be answered from the baseline; **None means
    UNKNOWN** -- no baseline, or one bound to a different sync -- and the caller
    must decide what to do about that. None is deliberately not collapsed into
    True here: "unknown" is safe in the records-match branch (force a reconcile)
    and actively harmful in the remote-newer branch, where treating it as
    modified turns every pending pull into a CONFLICT. Only the caller knows
    which branch it is in.

    Unknown is also what a filter-signature change produces, which is what makes
    editing a box's exclude list reconcile the newly in-scope files.
    """
    base = read_base(local_sync_record_path)
    if base is None:
        return None
    if local_sync_record_ulid is None or base["sync_record_ulid"] != str(
        local_sync_record_ulid
    ):
        return None
    if base.get("filter_signature") != filter_sig:
        return None

    current = tree_fingerprint(local_path, exclude_names, filter_sig=filter_sig)
    if current is None:
        # The tree is gone entirely. That is an existence question, not a
        # modification one, and the caller's existence logic already answers it.
        return None
    return current != base["fingerprint"]
