# AUTOGENERATED! DO NOT EDIT! File to edit: pts/mod/_ownership.pct.py

__all__ = ['OwnershipRefused', 'may_push', 'owner_gate', 'push_would_transfer', 'require_machine_name', 'write_denied_hint', 'write_denied_message']

# %% pts/mod/_ownership.pct.py 3
from pathlib import Path

import boxyard.config
from ._models import BoxMeta

# %% pts/mod/_ownership.pct.py 5
class OwnershipRefused(Exception):
    """
    A deliberate, user-initiated action was refused because this machine is not
    the box's write owner (or has no machine name to be one with).

    Only ever raised out of a command a person typed. The routine sync path uses
    `SyncCondition.WRITE_DENIED` instead — see this module's docstring.
    """

# %% pts/mod/_ownership.pct.py 7
def may_push(config: boxyard.config.Config, box_meta: BoxMeta) -> bool:
    """Is this machine allowed to push `box_meta`'s DATA/CONF?"""
    if box_meta.write_owner is None:
        return True  # unowned == unrestricted
    return box_meta.write_owner == config.machine_name


def require_machine_name(config: boxyard.config.Config, action: str) -> str:
    """
    Return this machine's name, or refuse with a message that names the fix.

    Ownership identifies a machine by a configured name and never by its
    hostname: one machine in this fleet has reported both `lukas-pocket4` and
    `pocket4`, and macOS reports user-editable pretty names.
    """
    if not config.machine_name:
        raise OwnershipRefused(
            f"Cannot {action}: this machine has no name, so it cannot be "
            f"recorded as a box's write owner.\n"
            f"Set `machine_name` in '{config.config_path}' to this machine's "
            f"canonical short name (e.g. 'macbook' or 'mymain'), then try again."
        )
    return config.machine_name

# %% pts/mod/_ownership.pct.py 9
def write_denied_message(
    config: boxyard.config.Config,
    box_meta: BoxMeta,
    part_label: str = "DATA",
) -> str:
    """The one-paragraph explanation shared by sync, doctor and multi-sync."""
    return (
        f"'{box_meta.index_name}' is owned by '{box_meta.write_owner}', so the "
        f"{part_label} of this copy is not pushed. It still pulls."
    )


def write_denied_hint(
    config: boxyard.config.Config,
    box_meta: BoxMeta,
) -> str:
    """The two ways out, both safe to run exactly as written."""
    return (
        f"Either take the box over with `boxyard claim --steal -r "
        f"'{box_meta.index_name}'`, or throw away this machine's changes with "
        f"`boxyard discard-local -r '{box_meta.index_name}'` (which keeps a "
        f"copy under '{config.local_sync_backups_path}'). "
        f"The tidy handover is `boxyard release` on '{box_meta.write_owner}' "
        f"followed by `boxyard claim` here."
    )


def owner_gate(
    config: boxyard.config.Config,
    box_meta: BoxMeta,
    action: str,
) -> None:
    """
    Refuse a deliberate remote-mutating action on a box another machine owns.

    Used by the paths that bypass `sync_helper` entirely and would otherwise
    write to the remote with no ownership check at all: `force-push`, `rename
    --scope remote|both` (it renames the remote directory), and `delete` (it
    purges the remote and writes a tombstone).
    """
    if may_push(config, box_meta):
        return
    raise OwnershipRefused(
        f"Cannot {action}: {write_denied_message(config, box_meta)}\n"
        f"{write_denied_hint(config, box_meta)}"
    )

# %% pts/mod/_ownership.pct.py 11
async def push_would_transfer(
    config: boxyard.config.Config,
    *,
    local_path: Path,
    remote: str,
    remote_path: Path,
    include_path: Path | None = None,
    exclude_path: Path | None = None,
    filters_path: Path | None = None,
) -> bool:
    """
    Would pushing `local_path` to `remote:remote_path` actually change anything?

    Uses the box's real filters, so debris that can never be transferred does
    not count as a change.

    Returns True when the answer is yes AND when the question could not be
    answered at all. Both callers of this treat True as "refuse to push and
    report it", so an unreachable remote surfaces as a reported state rather
    than as a silent all-clear — the one thing this must never do is claim a
    box is clean because it failed to look.
    """
    from ._utils import rclone_check

    answered, differing = await rclone_check(
        rclone_config_path=config.rclone_config_path,
        source="",
        source_path=local_path.as_posix(),
        dest=remote,
        dest_path=remote_path.as_posix(),
        include_file=include_path.as_posix() if include_path else None,
        exclude_file=exclude_path.as_posix() if exclude_path else None,
        filters_file=filters_path.as_posix() if filters_path else None,
    )
    if not answered:
        return True
    return bool(differing)
