# AUTOGENERATED! DO NOT EDIT! File to edit: pts/mod/_remote_identity.pct.py

__all__ = ['REMOTE_IDENTITY_VERSION', 'clear_remote_identity', 'note_agreement', 'read_remote_identity', 'record_md5', 'remote_identity_path', 'write_remote_identity']

# %% pts/mod/_remote_identity.pct.py 3
import hashlib
import json
import os
from pathlib import Path

from . import const

REMOTE_IDENTITY_VERSION = 1


def record_md5(text: str) -> str:
    """
    md5 of a sync record's bytes, as `rclone lsjson --hash` reports it for the
    file on the remote. Records are UTF-8 JSON and `run_cmd_async` decodes
    stdout as UTF-8 without stripping, so re-encoding the text reproduces the
    file's bytes exactly.
    """
    return hashlib.md5(text.encode("utf-8")).hexdigest()


def remote_identity_path(local_sync_record_path: "str | Path") -> Path:
    """`<dir>/data.rec` -> `<dir>/data.remote.json`, beside the record it describes."""
    p = Path(local_sync_record_path)
    return p.with_name(p.name.removesuffix(".rec") + const.BOX_REMOTE_IDENTITY_SUFFIX)


def write_remote_identity(
    local_sync_record_path: "str | Path",
    *,
    md5: str,
    ulid: str,
    sync_complete: bool,
) -> Path:
    """
    Remember the remote record this machine just agreed with. Atomic (temp
    file plus `os.replace`), like the fingerprint sidecar: a torn sidecar that
    happened to parse would be the one dangerous outcome.
    """
    p = remote_identity_path(local_sync_record_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "version": REMOTE_IDENTITY_VERSION,
        "md5": md5,
        "ulid": str(ulid),
        "sync_complete": bool(sync_complete),
    }
    tmp = p.with_name(p.name + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    os.replace(tmp, p)
    return p


def read_remote_identity(local_sync_record_path: "str | Path") -> "dict | None":
    """
    The remembered remote identity, or None when there is not a usable one.
    Absence, corruption, a version bump and a missing field all read as None:
    every one of them means "cannot prove", which costs a real check.
    """
    p = remote_identity_path(local_sync_record_path)
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    if not isinstance(data, dict) or data.get("version") != REMOTE_IDENTITY_VERSION:
        return None
    if not isinstance(data.get("md5"), str) or not isinstance(data.get("ulid"), str):
        return None
    if not isinstance(data.get("sync_complete"), bool):
        return None
    return data


def clear_remote_identity(local_sync_record_path: "str | Path") -> None:
    """Remove the sidecar. Absence is fine -- used on teardown paths."""
    remote_identity_path(local_sync_record_path).unlink(missing_ok=True)


def note_agreement(local_sync_record_path: "str | Path", status) -> bool:
    """
    Write the sidecar from a `SyncStatus` whose verdict means "nothing to do":
    SYNCED (both sides hold the same record and the local tree matches it) or
    EXCLUDED (this machine deliberately holds no copy; the remote record was
    read and is complete -- an incomplete one yields an INCOMPLETE condition
    before EXCLUDED is ever reached). Any other verdict writes nothing and
    returns False. A status with no remote record (never pushed) has no
    identity to remember and also returns False.
    """
    from ._models import SyncCondition

    if status.sync_condition not in (SyncCondition.SYNCED, SyncCondition.EXCLUDED):
        return False
    rec = status.remote_sync_record
    md5 = status.remote_sync_record_md5
    if rec is None or md5 is None:
        return False
    write_remote_identity(
        local_sync_record_path,
        md5=md5,
        ulid=str(rec.ulid),
        sync_complete=rec.sync_complete,
    )
    return True
