# AUTOGENERATED! DO NOT EDIT! File to edit: pts/mod/_restic.pct.py

__all__ = ['CanonicalRootUnavailable', 'GATE_SLACK_SECONDS', 'PullMode', 'PullResult', 'PushResult', 'ResticCondition', 'ResticError', 'ResticLocked', 'ResticRepo', 'ResticStatus', 'anchored_include_args', 'apply_removals', 'canonical_data_path', 'canonical_link', 'canonical_root', 'clear_state', 'count_tracked_files', 'data_root_exclude_args', 'estimate_stored_bytes', 'get_restic_binary', 'get_status', 'init_repo', 'latest_snapshot_id', 'local_is_modified', 'local_nodes_differ', 'mark_pull_started', 'matches_restic_exclude', 'parent_is_usable', 'parse_diff', 'parse_pointer', 'pointer_remote_path', 'pull', 'push', 'rclone_program_for', 'read_pointer', 'read_state', 'repo_exists', 'repo_url_for_box', 'require_restic_available', 'resolve_restic_password', 'restic_excludes_from_rclone_file', 'run_restic', 'snapshot_exists', 'snapshot_nodes', 'snapshot_source_path', 'state_path', 'tree_modified_since', 'tree_touched_since', 'write_pointer', 'write_state']

# %% pts/mod/_restic.pct.py 3
import contextlib
import json
import os
import stat
import time
from datetime import datetime
import shutil
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path

from . import const
from ._utils import run_cmd_async

# %% pts/mod/_restic.pct.py 5
class ResticError(Exception):
    """A restic invocation failed. Carries the command's own stderr."""

    def __init__(self, message: str, returncode: int | None = None, stderr: str = ""):
        self.returncode = returncode
        self.stderr = stderr
        super().__init__(message)


class ResticLocked(ResticError):
    """
    The repository is held by an EXCLUSIVE lock -- `forget` or `prune` on
    another machine, or a stale lock from one that suspended mid-operation.

    Its own class because it is the one restic failure with a standard remedy
    (`restic unlock`, once the holder is known to be gone) and the one a caller
    may legitimately choose to retry rather than report.
    """

# %% pts/mod/_restic.pct.py 7
_RESTIC_FALLBACK_DIRS = (
    "/opt/homebrew/bin",
    "/usr/local/bin",
    "/usr/bin",
    "/bin",
    "/snap/bin",
)

_restic_binary: str | None = None


def _is_executable(path: Path) -> bool:
    return path.is_file() and os.access(path, os.X_OK)


def _resolve_restic_binary() -> str:
    searched: list[str] = []

    env_path = os.environ.get(const.ENV_VAR_BOXYARD_RESTIC)
    if env_path:
        if _is_executable(Path(env_path).expanduser()):
            return str(Path(env_path).expanduser())
        raise ResticError(
            f"{const.ENV_VAR_BOXYARD_RESTIC} is set to '{env_path}', but no executable "
            f"restic binary exists there. Fix the path or unset "
            f"{const.ENV_VAR_BOXYARD_RESTIC}."
        )
    searched.append(f"${const.ENV_VAR_BOXYARD_RESTIC} (env var, unset)")

    which = shutil.which("restic")
    if which:
        return which
    searched.append("PATH (via shutil.which)")

    for d in _RESTIC_FALLBACK_DIRS:
        candidate = Path(d) / "restic"
        if _is_executable(candidate):
            return str(candidate)
        searched.append(str(candidate))

    raise ResticError(
        "boxyard could not find the `restic` binary. Searched:\n  - "
        + "\n  - ".join(searched)
        + f"\n\nInstall restic (https://restic.net/#installation), or set "
        f"{const.ENV_VAR_BOXYARD_RESTIC} to its full path."
    )

# %% pts/mod/_restic.pct.py 8
def get_restic_binary() -> str:
    """The resolved restic binary path, resolved and cached on first use."""
    global _restic_binary
    if _restic_binary is None:
        _restic_binary = _resolve_restic_binary()
    return _restic_binary

# %% pts/mod/_restic.pct.py 10
@dataclass(frozen=True)
class ResticRepo:
    """
    Where a repo is, and how to reach it.

    `rclone_program` is what makes restic inherit BOXYARD'S storage-location
    abstraction rather than replacing it with restic's own, much narrower, set
    of backends. It is `None` for a local path, which is what tests use.
    """

    url: str
    password: str
    cache_dir: Path
    rclone_program: str | None = None

    def base_args(self) -> list[str]:
        args = [get_restic_binary()]
        if self.rclone_program is not None:
            args += ["-o", f"rclone.program={self.rclone_program}"]
        return args + ["-r", self.url]

    def env(self) -> dict[str, str]:
        """
        The child environment. The password is passed HERE, fetched once per
        process by the caller.

        Not restic's `--password-command`: restic reruns it on every
        invocation, and `secret get` measured 0.77-1.51 s, so at one invocation
        per box that is minutes of 1Password round trips per pass for a value
        that does not change.
        """
        env = dict(os.environ)
        env["RESTIC_PASSWORD"] = self.password
        env["RESTIC_CACHE_DIR"] = str(self.cache_dir)
        # A password file or command inherited from the ambient environment
        # would silently win over what we just set.
        env.pop("RESTIC_PASSWORD_FILE", None)
        env.pop("RESTIC_PASSWORD_COMMAND", None)
        env.pop("RESTIC_REPOSITORY", None)
        env.pop("RESTIC_REPOSITORY_FILE", None)
        return env


def require_restic_available(config, what: str) -> None:
    """
    Refuse NOW if this machine cannot work a restic repository.

    `what` names the operation, so the message says what will not happen rather
    than only what is wrong.

    Both prerequisites are checked together because both are fatal in the same
    way and a person fixing one wants to know about the other in the same
    breath: the binary, and the repository password.

    THE SCAR: `boxyard include` on a converted box printed "Included box ..."
    on a machine with no `restic` binary at all, created nothing, and the
    failure surfaced several commands later -- by which time `sync` refused,
    `exclude` refused, and the machine was in a state no command could exit.
    A command that reports success and does nothing is worse than one that
    refuses, so anything that will need restic asks this BEFORE it acts or
    prints.
    """
    try:
        get_restic_binary()
    except ResticError as e:
        raise ResticError(f"Cannot {what}: {e}") from None
    try:
        resolve_restic_password(config)
    except ResticError as e:
        raise ResticError(f"Cannot {what}: {e}") from None


def rclone_program_for(rclone_config_path: "str | Path") -> str:
    """
    The `-o rclone.program` string that routes restic through boxyard's own
    rclone configuration.

    restic takes this as ONE string and re-parses it into argv, so the paths in
    it must be quoted rather than interpolated raw. Verified against restic
    directly: with an unquoted path containing a space it splits at the space
    and dies with `fork/exec /tmp/claude-1000/rp: no such file or directory`,
    and with the same path shlex-quoted it runs. So restic parses this
    shell-style, and `shlex.join` is the matching encoder -- not a workaround
    for it.

    Interpolating a path into a string that something else re-parses is the
    exact pattern the repo bans everywhere else, and it was live here. Today
    both paths happen to be boxyard-controlled and space-free, so this was
    latent rather than broken -- but `rclone_config_path` comes from user
    config, and a home directory with a space in it is ordinary on macOS.
    """
    import shlex

    from ._utils import get_rclone_binary

    return shlex.join([str(get_rclone_binary()), "--config", str(rclone_config_path)])


def repo_url_for_box(
    store_path: Path, storage_location: str, remote_index_name: str
) -> str:
    """The rclone-backed repo URL for one box at one storage location."""
    path = (
        Path(store_path)
        / const.REMOTE_BOXES_REL_PATH
        / remote_index_name
        / const.BOX_RESTIC_REL_PATH
    )
    return f"rclone:{storage_location}:{path.as_posix()}"


def pointer_remote_path(store_path: Path, remote_index_name: str) -> Path:
    """Where the snapshot pointer lives on the remote, at depth 2."""
    return (
        Path(store_path)
        / const.REMOTE_BOXES_REL_PATH
        / remote_index_name
        / const.BOX_SNAPSHOT_POINTER_REL_PATH
    )

# %% pts/mod/_restic.pct.py 12
_password_cache: dict[str, str] = {}

# %% pts/mod/_restic.pct.py 13
def resolve_restic_password(config) -> str:
    """
    The repository password, from the environment or `restic_password_command`.

    Cached per resolved command for the life of the process, which is the whole
    point: `secret get` measured 0.77-1.51 s, and a 590-box pass would otherwise
    spend minutes on 1Password round trips for a value that cannot change.

    Refuses loudly when neither source is configured. There is no default and no
    fallback: an empty password would create a repository nobody could open
    again, and restic itself refuses one.
    """
    import subprocess

    env_value = os.environ.get(const.ENV_VAR_BOXYARD_RESTIC_PASSWORD)
    if env_value:
        return env_value

    command = getattr(config, "restic_password_command", None)
    if not command:
        raise ResticError(
            f"No restic repository password is configured. Set "
            f"`restic_password_command` in '{config.config_path}' to a command "
            f"that prints it (e.g. `secret get BOXYARD_RESTIC_PASSWORD`), or "
            f"set ${const.ENV_VAR_BOXYARD_RESTIC_PASSWORD}."
        )
    if command in _password_cache:
        return _password_cache[command]

    # A configured command is a shell string by nature ("secret get NAME"), and
    # it comes from the user's own config file rather than from box content, so
    # `shell=True` is appropriate here and only here. Nothing derived from a
    # path or a box name is ever interpolated into it.
    proc = subprocess.run(
        command, shell=True, capture_output=True, text=True
    )
    if proc.returncode != 0:
        raise ResticError(
            f"`restic_password_command` failed (exit {proc.returncode}): "
            f"{command}\n{proc.stderr.strip()}"
        )
    password = proc.stdout.strip()
    if not password:
        raise ResticError(
            f"`restic_password_command` produced no output: {command}. An empty "
            f"password would create a repository that cannot be opened again."
        )
    _password_cache[command] = password
    return password

# %% pts/mod/_restic.pct.py 15
async def run_restic(
    repo: ResticRepo,
    args: list[str],
    *,
    timeout: float | None = None,
    check: bool = True,
    stdout_line_callback=None,
) -> tuple[int, str, str]:
    """
    Run one restic subcommand. Returns `(returncode, stdout, stderr)`.

    Always argv, never a shell string: a box's DATA path comes off the
    filesystem and may contain spaces, quotes, backticks or `$()`.

    `check=False` is for the callers that must distinguish "restic said no" from
    "restic failed" -- notably `snapshot_exists`, where restic's two relevant
    commands disagree about how absence is reported.
    """
    cmd = repo.base_args() + args
    returncode, stdout, stderr = await run_cmd_async(
        cmd,
        timeout=timeout,
        env=repo.env(),
        stdout_line_callback=stdout_line_callback,
    )
    if returncode == const.RESTIC_EXIT_LOCK_FAILED:
        raise ResticLocked(
            f"restic could not lock '{repo.url}': another operation holds it "
            f"exclusively (`forget` or `prune`, or a stale lock from a machine "
            f"that suspended). `restic unlock` clears a stale one.\n{stderr.strip()}",
            returncode=returncode,
            stderr=stderr,
        )
    if check and returncode != 0:
        raise ResticError(
            f"`restic {args[0] if args else ''}` failed on '{repo.url}' "
            f"(exit {returncode}).\n{stderr.strip()}",
            returncode=returncode,
            stderr=stderr,
        )
    return returncode, stdout, stderr


async def init_repo(repo: ResticRepo) -> None:
    """Create the repository. Fails loudly if one is already there."""
    await run_restic(repo, ["init"])


async def repo_exists(repo: ResticRepo) -> bool:
    """Whether a repository is already present and openable at this URL."""
    returncode, _, _ = await run_restic(
        repo, ["cat", "config"], timeout=const.RESTIC_METADATA_TIMEOUT, check=False
    )
    return returncode == 0

# %% pts/mod/_restic.pct.py 17
class CanonicalRootUnavailable(Exception):
    """
    The canonical root cannot be used on this machine.

    Raised rather than worked around, because silently backing up through the
    real path instead would record a path no other machine can match, and the
    damage (every other machine falling back to full restores) would show up
    somewhere else entirely.
    """


def canonical_root() -> Path:
    """
    The fixed directory every box is backed up through, created 0700 and
    validated.

    `/tmp` is world-writable and sticky on every machine in this fleet, so a
    hostile or stale entry could otherwise redirect a backup -- or a restore --
    outside the box. The root must therefore be a real directory, not a symlink,
    owned by us, and not group- or world-writable. Anything else is refused.
    """
    root = Path(const.RESTIC_CANONICAL_ROOT)
    if root.is_symlink():
        raise CanonicalRootUnavailable(
            f"'{root}' is a symlink. It must be a real directory owned by this "
            f"user; refusing to back up through it."
        )
    try:
        root.mkdir(mode=0o700, parents=True, exist_ok=True)
    except OSError as exc:
        raise CanonicalRootUnavailable(
            f"cannot create the canonical restic root '{root}': {exc}"
        ) from exc
    stat = root.stat()
    if not root.is_dir():
        raise CanonicalRootUnavailable(f"'{root}' exists and is not a directory.")
    if hasattr(os, "geteuid") and stat.st_uid != os.geteuid():
        raise CanonicalRootUnavailable(
            f"'{root}' is owned by uid {stat.st_uid}, not by this user "
            f"({os.geteuid()}). Refusing to back up through it."
        )
    if stat.st_mode & 0o077:
        raise CanonicalRootUnavailable(
            f"'{root}' is mode {stat.st_mode & 0o777:o}; it must not be readable "
            f"or writable by group or other."
        )
    return root


def canonical_data_path(box_index_name: str) -> Path:
    """
    The path a box is ALWAYS backed up through, on every machine.

    Note the index name appears twice, and that is the point: the first is the
    symlink (pointing at this machine's checkout root), the second is the box's
    own directory inside it. A symlink as the FINAL component would archive the
    link and nothing else.
    """
    return Path(const.RESTIC_CANONICAL_ROOT) / box_index_name / box_index_name


@contextlib.contextmanager
def canonical_link(box_index_name: str, data_path: Path):
    """
    Point the canonical path at `data_path` for the duration of one operation.

    Re-pointed ATOMICALLY on every use, never created-only-if-missing: a crashed
    run can leave a link aimed at a checkout root the box has since left, and
    silently backing up the old location would be worse than any failure. Costs
    0.033 ms, measured.
    """
    data_path = Path(data_path).resolve()
    if data_path.name != box_index_name:
        raise CanonicalRootUnavailable(
            f"'{data_path}' is not named for its box ('{box_index_name}'), so the "
            f"canonical path cannot be formed. This is a boxyard bug, not a "
            f"user error."
        )
    root = canonical_root()
    link = root / box_index_name
    tmp = root / f".tmp-{box_index_name}-{os.getpid()}"
    tmp.unlink(missing_ok=True)
    os.symlink(data_path.parent, tmp)
    os.replace(tmp, link)
    try:
        yield canonical_data_path(box_index_name)
    finally:
        link.unlink(missing_ok=True)

# %% pts/mod/_restic.pct.py 19
def data_root_exclude_args(data_path: Path) -> list[str]:
    """
    `--exclude` arguments for things that must never enter a snapshot.

    Today that is exactly the exec-bit manifest: restic carries Unix mode
    natively and exactly (755/644/775 all round-trip), so the manifest is dead
    weight for a restic-backed box -- and leaving it in would churn a generated
    file inside the very thing that exists to avoid churning generated files.

    ANCHORED TO THE ABSOLUTE PATH, because that is what `backup` matches
    against. The bare basename would also exclude a `.boxyard-perms.json` that
    is real content somewhere inside the box; a leading slash would exclude
    nothing at all.
    """
    return [
        "--exclude",
        (Path(data_path) / const.BOX_PERMS_MANIFEST_REL_PATH).as_posix(),
    ]


def restic_excludes_from_rclone_file(exclude_path: "str | Path | None") -> list[str]:
    """
    Translate boxyard's rclone exclude file into restic `--exclude` patterns.

    Without this a converted box would silently start storing `.venv/`,
    `node_modules/`, `target/` and everything else the fleet-wide exclude list
    removes -- the same list that cut jackfruit from 687,876 files to 134,551
    before restic was involved at all. Ignoring it would not be a small
    regression.

    The two syntaxes agree on the case that matters. rclone writes one pattern
    per line with a trailing slash for a directory (".venv/"), and restic
    matches an unanchored pattern against the basename at any depth -- which is
    exactly rclone's meaning for these names. Only the trailing slash has to go.

    Deliberately NOT passed to restic as `--exclude-file`: the file is rclone's,
    the syntaxes diverge for anchored and wildcard patterns, and handing restic a
    file written for another tool would silently apply different rules than the
    plain path does.
    """
    if exclude_path is None:
        return []
    path = Path(exclude_path)
    if not path.is_file():
        return []
    patterns: list[str] = []
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        patterns.append(stripped.rstrip("/"))
    return patterns


def anchored_include_args(rel_paths: list[str]) -> list[str]:
    """
    `--include` arguments for a targeted restore, anchored to the snapshot
    SUBPATH by a leading slash.

    Without the leading slash restic matches the basename at any depth, so
    restoring one changed `package.json` would restore every `package.json` in
    the box. With an absolute path it matches nothing and restores silently
    nothing at all.
    """
    args: list[str] = []
    for rel in rel_paths:
        args += [f"--include=/{rel.lstrip('/')}"]
    return args

# %% pts/mod/_restic.pct.py 21
async def snapshot_exists(repo: ResticRepo, snapshot_id: str) -> bool:
    """Whether `snapshot_id` is still in the repo."""
    returncode, stdout, _ = await run_restic(
        repo,
        ["snapshots", snapshot_id, "--json"],
        timeout=const.RESTIC_METADATA_TIMEOUT,
        check=False,
    )
    if returncode != 0:
        return False
    try:
        return bool(json.loads(stdout))
    except json.JSONDecodeError:
        return False


async def snapshot_source_path(repo: ResticRepo, snapshot_id: str) -> str | None:
    """
    The absolute path this snapshot was backed up FROM, or None if it is gone.

    Needed on every pull: it is what lets `restore <snap>:<source>` place the
    CONTENTS at an arbitrary local directory, so a box is restorable onto a
    machine whose checkout root differs from the pusher's.
    """
    returncode, stdout, _ = await run_restic(
        repo,
        ["snapshots", snapshot_id, "--json"],
        timeout=const.RESTIC_METADATA_TIMEOUT,
        check=False,
    )
    if returncode != 0:
        return None
    try:
        snapshots = json.loads(stdout)
    except json.JSONDecodeError:
        return None
    if not snapshots or not snapshots[0].get("paths"):
        return None
    return snapshots[0]["paths"][0]


async def latest_snapshot_id(repo: ResticRepo) -> str | None:
    """The most recent snapshot's full id, or None for an empty repo."""
    returncode, stdout, _ = await run_restic(
        repo,
        ["snapshots", "--json", "--latest", "1"],
        timeout=const.RESTIC_METADATA_TIMEOUT,
        check=False,
    )
    if returncode != 0:
        return None
    try:
        snapshots = json.loads(stdout)
    except json.JSONDecodeError:
        return None
    return snapshots[-1]["id"] if snapshots else None

# %% pts/mod/_restic.pct.py 23
def state_path(boxyard_data_path: Path, box_index_name: str) -> Path:
    return (
        Path(boxyard_data_path)
        / const.RESTIC_STATE_REL_PATH
        / box_index_name
        / "data.json"
    )


def mark_pull_started(
    boxyard_data_path: Path, box_index_name: str, target_snapshot: str
) -> None:
    """
    Note that a restore to `target_snapshot` has begun.

    Keeps whatever snapshot the record already named, so an interrupted pull
    still knows where it came FROM as well as where it was going.
    """
    previous = read_state(boxyard_data_path, box_index_name)
    write_state(
        boxyard_data_path,
        box_index_name,
        (previous or {}).get("snapshot") or target_snapshot,
        now_unix=(previous or {}).get("synced_at_unix"),
        pulling_from=target_snapshot,
    )


def clear_state(boxyard_data_path: Path, box_index_name: str) -> bool:
    """
    Forget this machine's restic state for a box. True if there was one.

    The state record says "my local tree is at snapshot X". Once the tree is
    gone -- `exclude`, `discard-local` -- that claim is false, and leaving it
    behind means the next thing to read it is told about a tree that is not
    there.

    Absence is a legitimate outcome, not a masked bug: a plain box never has
    one, and neither does a box excluded twice.
    """
    path = state_path(boxyard_data_path, box_index_name)
    if not path.exists():
        return False
    path.unlink()
    return True


def read_state(boxyard_data_path: Path, box_index_name: str) -> dict | None:
    """The snapshot this machine last agreed with, and when, or None."""
    path = state_path(boxyard_data_path, box_index_name)
    if not path.exists():
        return None
    try:
        record = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError, UnicodeDecodeError):
        return None
    if not isinstance(record, dict) or not record.get("snapshot"):
        return None
    return record


def write_state(
    boxyard_data_path: Path,
    box_index_name: str,
    snapshot_id: str,
    now_unix: float | None = None,
    pulling_from: str | None = None,
    files: int | None = None,
) -> Path:
    """
    Record agreement with `snapshot_id`, now.

    Written via a temp file in the same directory then renamed, so a crash
    mid-write leaves either the old record or the new one, never a truncated
    file that reads as "never synced" and silently costs a full restore.

    `pulling_from` marks a restore that is IN PROGRESS. Without it an
    interrupted pull is indistinguishable from local edits: the tree matches
    neither the old snapshot nor the new one, so `local_is_modified` says yes
    and the box reports CONFLICT -- a false conflict after every interrupted
    pull, needing a person for something the next pass could finish by itself.
    Cleared by writing the record again without it, which only happens after a
    restore has completed.
    """
    import tempfile
    import time

    path = state_path(boxyard_data_path, box_index_name)
    path.parent.mkdir(parents=True, exist_ok=True)
    record = {
        "snapshot": snapshot_id,
        "synced_at_unix": time.time() if now_unix is None else now_unix,
    }
    if pulling_from is not None:
        record["pulling_from"] = pulling_from
    # How many files that snapshot held. `backup --dry-run` cannot see a
    # DELETION -- a file that is gone is simply not walked, so `files_new` and
    # `files_changed` both stay 0 and a box whose only change is a deletion
    # never pushes. Comparing the count catches it, with no extra remote call.
    if files is not None:
        record["files"] = files
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".tmp-", suffix=".json")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(json.dumps(record))
        os.replace(tmp, path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise
    return path

# %% pts/mod/_restic.pct.py 25
async def read_pointer(
    rclone_config_path: Path,
    storage_location: str,
    store_path: Path,
    remote_index_name: str,
) -> dict | None:
    """
    The remote's current snapshot pointer, or None if the box has never been
    pushed in this format.

    A single-box read, for the standalone paths. The scheduled pass gets this
    for the WHOLE yard out of the bulk depth-2 listing it already runs.
    """
    from ._utils import rclone_cat

    exists, raw = await rclone_cat(
        rclone_config_path=rclone_config_path,
        source=storage_location,
        source_path=pointer_remote_path(store_path, remote_index_name).as_posix(),
    )
    if not exists:
        return None
    return parse_pointer(raw)


def parse_pointer(raw: str) -> dict | None:
    """
    Parse a pointer's contents.

    Unreadable is reported as None -- "the remote has not told us anything we
    can use" -- which routes to a full restore. A corrupt pointer must not be
    able to make a box look UP TO DATE.
    """
    try:
        pointer = json.loads(raw)
    except (json.JSONDecodeError, TypeError):
        return None
    if not isinstance(pointer, dict) or not pointer.get("snapshot"):
        return None
    return pointer


async def write_pointer(
    rclone_config_path: Path,
    storage_location: str,
    store_path: Path,
    remote_index_name: str,
    snapshot_id: str,
    source_path: str,
) -> None:
    """
    Publish the snapshot the remote should now be considered to hold.

    Written AFTER the snapshot exists, never before: the other order advertises
    a snapshot that is not there yet, and a puller would fail on a repo that is
    actually fine.
    """
    import tempfile

    from ._utils import rclone_copyto

    body = json.dumps({"snapshot": snapshot_id, "path": source_path}, sort_keys=True)
    with tempfile.NamedTemporaryFile(
        "w", suffix=".snapshot", delete=False
    ) as handle:
        handle.write(body + "\n")
        tmp = Path(handle.name)
    try:
        await rclone_copyto(
            rclone_config_path=rclone_config_path,
            source="",
            source_path=tmp.as_posix(),
            dest=storage_location,
            dest_path=pointer_remote_path(
                store_path, remote_index_name
            ).as_posix(),
            dry_run=False,
        )
    finally:
        tmp.unlink(missing_ok=True)

# %% pts/mod/_restic.pct.py 27
async def parent_is_usable(
    repo: "ResticRepo", parent_snapshot: str, data_path: Path
) -> bool:
    """
    Can restic's own change detection answer for this (snapshot, path) pair?

    Only if the snapshot still EXISTS and was taken from THIS EXACT PATH.

    The path condition is the absolute-path trap in its third and most
    consequential place. `backup --parent` matches the parent's tree BY PATH, so
    a parent taken elsewhere makes every file look new: measured, byte-identical
    content under a different path reports `files_new=1, files_unmodified=0`
    against `files_new=0, files_unmodified=1` for the same content under the
    same path.

    The canonical path (see `canonical_link`) is what normally makes both
    conditions hold on every machine, so this is NOT the usual route -- exact
    detection is. Two distinct things still reach it, and only one expires:

    1. **The parent snapshot is gone.** Permanent, and routine once retention
       ships: any machine's `forget` can remove the snapshot another machine's
       state record names. Deliberately no `TODO(cleanup)` -- this never goes
       away.
    2. **The parent was taken through a different path.** Either a snapshot
       predating the canonical root, which expires when conversion completes, or
       a canonical root that cannot be validated right now -- a `/tmp` that is a
       symlink, world-writable or owned by someone else, a machine or platform
       we have not met. That half is defence in depth and also does not expire.

    When it fires, detection falls back to the mtime-versus-record-time test the
    plain backend already applies. Not a regression: it is today's semantics.
    """
    source = await snapshot_source_path(repo, parent_snapshot)
    if source is None:
        return False
    return source == os.path.abspath(str(data_path))


# How far before `synced_at_unix` a timestamp still counts as "after it".
#
# Filesystem timestamp granularity is not always nanoseconds -- HFS+ records
# whole seconds -- so a write that genuinely happened AFTER the recorded moment
# can be stamped slightly before it. Without slack that edit would be gated out
# and lost silently, which is the one outcome this whole area exists to prevent.
# Two seconds costs an occasional unnecessary full check and nothing else.
GATE_SLACK_SECONDS = 2.0


def tree_touched_since(
    data_path: Path,
    since_unix: float,
    exclude_names: "set[str] | None" = None,
) -> bool:
    """
    Has anything under `data_path` been touched since `since_unix`?

    The cheap gate in front of change detection, and a SUFFICIENT CONDITION
    only: False means nothing was touched and the tree therefore still matches
    the snapshot; True means "maybe", and the caller must do the real work.
    Being wrong towards True costs one slow check. Being wrong towards False
    loses an edit, silently, for ever -- so every uncertainty here resolves to
    True.

    `max(mtime, ctime)`, and the ctime is the entire point. `chmod` moves ctime
    and leaves mtime alone (measured), so the plain backend's
    `check_last_time_modified` -- which is mtime-only -- would reintroduce
    exactly the defect the change-detection audit removed, one level up. It sees
    all eleven shapes in that table, including both directions of `chmod` and a
    symlink retargeted in place.

    DIRECTORIES are stat-ed too, not just their entries: deleting a file leaves
    nothing new to look at, and only its parent's mtime moves.

    An unreadable directory RAISES rather than being skipped, for the same
    reason `check_last_time_modified` does: swallowing the error would lower the
    answer and gate out real changes underneath it. A directory that vanishes
    mid-walk is a legitimate race and is tolerated.
    """
    exclude_names = exclude_names or set()
    threshold = since_unix - GATE_SLACK_SECONDS
    root = Path(data_path)
    stack = [str(root)]
    while stack:
        current = stack.pop()
        try:
            entries = list(os.scandir(current))
            st = os.lstat(current)
        except FileNotFoundError:
            continue
        except OSError as e:
            raise OSError(
                f"Cannot tell whether '{root}' has changed: '{current}' could "
                f"not be read ({e}). Fix the permissions, or exclude it from "
                f"the box."
            ) from e
        if max(st.st_mtime, st.st_ctime) > threshold:
            return True
        for entry in entries:
            if entry.name in exclude_names:
                continue
            try:
                est = entry.stat(follow_symlinks=False)
            except FileNotFoundError:
                continue
            if max(est.st_mtime, est.st_ctime) > threshold:
                return True
            if entry.is_dir(follow_symlinks=False):
                stack.append(entry.path)
    return False


def tree_modified_since(data_path: Path, since_unix: float) -> bool:
    """
    Repo-independent change detection, for when the recorded snapshot is gone.

    Deliberately the SAME question the plain backend already asks --
    `check_last_time_modified` against the sync record's timestamp -- so the
    fallback is not a new mechanism and not a weaker guarantee than today's.
    """
    from ._utils import check_last_time_modified

    last_modified = check_last_time_modified(Path(data_path))
    if last_modified is None:
        return False  # nothing there to have changed
    return last_modified.timestamp() > since_unix


@contextlib.contextmanager
def _backup_path(box_index_name: str | None, data_path: Path):
    """
    The path restic should be pointed at, and whether it is the canonical one.

    Falls back to the real path when the canonical root cannot be validated.
    That should not happen on any machine in the live fleet, so it means
    something is wrong with `/tmp` -- but falling back DEGRADES rather than
    fails: it stays correct, because `parent_is_usable` and
    `PullMode.FULL_PATH_MISMATCH` both key off the recorded path. Refusing
    instead would leave a machine unable to save work because of a permissions
    problem somewhere else entirely. The caller is told which path was used.
    """
    if box_index_name is None:
        yield Path(data_path), False
        return
    try:
        with canonical_link(box_index_name, data_path) as canonical:
            yield canonical, True
    except CanonicalRootUnavailable:
        yield Path(data_path), False


def _backup_args(effective_path: Path, excludes: list[str] | None) -> list[str]:
    """
    Flags shared by the real backup and the dry-run used for change detection.
    The two MUST agree, or a box looks modified in one and clean in the other.

    `--ignore-inode` is not optional. Two machines never share inodes and restic
    compares them by default, so a replica that obtained its copy by restoring
    reports every file `changed` without it -- measured, `changed=2 unmodified=0`
    against `changed=0 unmodified=2` with the flag. A genuine edit is still seen.
    """
    args = ["--no-scan", "--ignore-inode"]
    args += data_root_exclude_args(effective_path)
    for pattern in excludes or []:
        args += ["--exclude", pattern]
    return args


async def snapshot_nodes(
    repo: ResticRepo, snapshot: str
) -> dict[str, tuple] | None:
    """
    `{relative path: (type, mode, mtime)}` for the nodes a snapshot recorded.

    Restic's OWN view, so the box's excludes are already applied -- which is the
    reason this asks the repository rather than walking the tree and re-deciding
    what `.venv/` means. A second implementation of the exclude rules would
    drift, and a drifted exclude shows up as a box that is permanently
    "modified" and pushes for ever.

    A DIRECTORY's mtime is deliberately recorded as None. It changes whenever
    anything is created or deleted inside it -- INCLUDING an excluded file, so a
    `.DS_Store` appearing would otherwise mark the box modified on every pass on
    both Macs. It also differs on any machine whose copy came from a restore,
    which would leave every replica permanently dirty. Neither is a change to
    the box.

    Returns None if the snapshot cannot be listed -- forgotten by retention, or
    the repository is unreachable -- which the caller must read as "cannot
    tell", never as "unchanged".
    """
    nodes: dict[str, tuple] = {}
    # `ls --json` opens with the snapshot itself, which carries the source path.
    # Taking it from here rather than asking `snapshot_source_path` separately
    # saves a whole restic invocation, and process startup is what this costs:
    # measured, the check takes the same ~3 s on a 600-node box as on a 7,300
    # node one.
    prefix = ""

    def _line(line: str) -> None:
        nonlocal prefix
        if not line.startswith("{"):
            return
        try:
            node = json.loads(line)
        except json.JSONDecodeError:
            return
        if node.get("struct_type") == "snapshot":
            paths = node.get("paths") or []
            if paths:
                prefix = str(paths[0]).rstrip("/")
            return
        if node.get("struct_type") != "node" or not prefix:
            return
        path = node.get("path") or ""
        if path == prefix:
            rel = ""
        elif path.startswith(prefix + "/"):
            rel = path[len(prefix) + 1:]
        else:
            return  # an ancestor of the backup root; not part of the box
        kind = node.get("type")
        nodes[rel] = (
            kind,
            node.get("mode"),
            None if kind == "dir" else node.get("mtime"),
        )

    returncode, _, _ = await run_restic(
        repo,
        ["ls", "--json", "--long", snapshot],
        timeout=const.RESTIC_METADATA_TIMEOUT,
        check=False,
        stdout_line_callback=_line,
    )
    if returncode != 0:
        return None
    return nodes


def local_nodes_differ(data_path: Path, expected: dict[str, tuple]) -> bool:
    """
    Does the tree at `data_path` still match what the snapshot recorded?

    Compares TYPE, MODE and -- for everything except directories -- MTIME. That
    combination is what restic's own counters cannot express: a symlink is
    neither a file nor a directory, so nothing about one moves `files_new`,
    `files_changed` or `dirs_new`, and a mode lives in metadata rather than in
    content so changing one rewrites no file.

    Retargeting a symlink in place is caught by its MTIME: measured, `ln -sfn`
    moves it, and nothing else about the node changes.

    New nodes are found by listing each directory the snapshot recorded, and
    only SYMLINKS count as an addition here -- new files and new directories
    already move `files_new` and `dirs_new`, and counting every unrecorded entry
    would report excluded ones (a `.DS_Store`, a `.pyc`) as changes.
    """
    root = Path(data_path)
    for rel, (kind, mode, mtime) in expected.items():
        path = root / rel if rel else root
        try:
            st = path.lstat()
        except FileNotFoundError:
            return True  # recorded, and gone: a deleted symlink, file or dir
        except OSError:
            return True
        actual_kind = (
            "symlink" if stat.S_ISLNK(st.st_mode)
            else "dir" if stat.S_ISDIR(st.st_mode)
            else "file"
        )
        if actual_kind != kind:
            return True
        if mode is not None and stat.S_IMODE(st.st_mode) != stat.S_IMODE(mode):
            return True
        if mtime is not None and not _mtime_matches(st.st_mtime, mtime):
            return True

    recorded = set(expected)
    for rel, (kind, _mode, _mtime) in expected.items():
        if kind != "dir":
            continue
        directory = root / rel if rel else root
        try:
            entries = list(os.scandir(directory))
        except OSError:
            return True
        for entry in entries:
            if not entry.is_symlink():
                continue
            child = f"{rel}/{entry.name}" if rel else entry.name
            if child not in recorded:
                return True
    return False


def _mtime_matches(local_epoch: float, recorded: str | None) -> bool:
    """Compare a filesystem mtime with restic's RFC3339 string, to the second.

    To the SECOND on purpose: restic records nanoseconds, and several
    filesystems and every `rsync`-like copy round the fraction differently. A
    sub-second difference is never a change a person made, and treating one as a
    change would push on every pass.
    """
    if not recorded:
        return True
    try:
        text = recorded.replace("Z", "+00:00")
        when = datetime.fromisoformat(text)
    except ValueError:
        return True  # unparseable: do not manufacture a change from it
    return int(when.timestamp()) == int(local_epoch)


async def local_is_modified(
    repo: ResticRepo,
    data_path: Path,
    parent_snapshot: str | None,
    *,
    synced_at_unix: float | None = None,
    excludes: list[str] | None = None,
    box_index_name: str | None = None,
    expected_files: int | None = None,
    exclude_names: "set[str] | None" = None,
) -> "tuple[bool, float | None]":
    """
    Does this machine hold DATA changes the remote has not seen?

    Returns `(modified, clean_check_at_unix)`. The second value is set ONLY
    when the answer "not modified" was proved by the FULL check (the dry-run
    plus node comparison), and holds the moment captured BEFORE that check
    started reading the tree. The caller re-stamps `synced_at_unix` with it,
    which is what closes the cheap gate again after an excluded-name arrival
    (a `.DS_Store` bumping its directory's mtime) has opened it: without the
    re-stamp the gate stays open FOR EVER and every subsequent pass pays the
    full check -- and `--skip-unchanged` never skips the box again. Captured
    before the walk per 0.8.1's rule: erring early costs one extra check,
    erring late hides a mid-check write.
    """
    # THE CHEAP GATE, and it is parity rather than an optimisation.
    #
    # The plain backend has always short-circuited on a local mtime walk and
    # NEVER contacted the remote when nothing was touched. Measured on mymain
    # against the live remote: a no-op DATA sync of jackfruit-hq -- 1,419,522
    # files -- takes 8 SECONDS, on a box whose real passes take 7-10 hours.
    #
    # Without this, restic loses the unchanged case AT EVERY SIZE, because it
    # pays ~2.2 s for `restic snapshots` regardless: measured, a 42-file restic
    # box took 11 s against that 1.4-million-file plain box's 8 s. Unchanged is
    # the overwhelming majority of passes on almost every box, so the comparison
    # that matters is the one restic was losing.
    #
    # SUFFICIENT CONDITION ONLY. Nothing touched => the tree still matches the
    # snapshot => skip the three remote calls. Anything touched -- INCLUDING an
    # excluded write, which bumps a directory's mtime -- falls through to the
    # full check, which then answers correctly. The gate may only ever skip work
    # when nothing at all has been touched.
    if parent_snapshot is not None and synced_at_unix is not None:
        if not tree_touched_since(data_path, synced_at_unix, exclude_names):
            return False, None

    with _backup_path(box_index_name, data_path) as (effective_path, _):
        if parent_snapshot and not await parent_is_usable(
            repo, parent_snapshot, effective_path
        ):
            # The parent snapshot is gone (retention pruned it) or unusable,
            # so nothing can prove this tree clean. Assume changed -- the same
            # direction the no-timestamp case below always took. This used to
            # fall back to `tree_modified_since`, the files-only mtime test
            # that sees two of ten change shapes, so a replica whose ONLY
            # change since the pruned snapshot was a deletion, rename, chmod
            # or symlink edit read "clean" and had that change silently
            # reverted by the next full restore. The cost of assuming: an
            # owner pays one parentless backup and converges; a non-owner
            # reports WRITE_DENIED until a person looks -- rare (pruning), and
            # honest, since the replica genuinely cannot be proven clean.
            return True, None

        _pre_check_unix = time.time()

        args = ["backup", "--dry-run", "--json"] + _backup_args(
            effective_path, excludes
        )
        if parent_snapshot:
            args += ["--parent", parent_snapshot]
        args.append(str(effective_path))

        returncode, stdout, _ = await run_restic(repo, args, check=False)

        if returncode != 0:
            return True, None  # cannot tell -> assume changed

        summary: dict = {}
        for line in stdout.splitlines():
            try:
                message = json.loads(line)
            except json.JSONDecodeError:
                continue
            if message.get("message_type") == "summary":
                summary = message
                break

        if not summary:
            return True, None

        # Restic's counters, which are ANCESTOR-IMMUNE -- measured: writing an
        # unrelated file in the box's parent directory moves none of them. That
        # rules out every "did anything change" field restic reports, because
        # `tree_blobs`, `dirs_changed` and `data_added` all move for activity
        # ABOVE the box, and the canonical root lives under `/tmp`.
        if (
            summary.get("files_new")
            or summary.get("files_changed")
            or summary.get("dirs_new")
        ):
            return True, None
        if (
            expected_files is not None
            and summary.get("total_files_processed") != expected_files
        ):
            return True, None

        # ...and what those counters CANNOT express. They count node KINDS, so
        # a symlink -- neither a file nor a directory -- moves none of them, and
        # neither does a mode, which lives in metadata rather than content.
        # Measured misses: adding a symlink, retargeting one, deleting one,
        # deleting an empty directory, and every `chmod` including the exec bit.
        # Six shapes, of which only the first was ever reported.
        #
        # So the remaining question is asked against the snapshot's own node
        # list. It runs only when the cheap counters have already said "clean",
        # which is the common case for a box nobody has touched.
        if parent_snapshot is None:
            return False, _pre_check_unix
        expected = await snapshot_nodes(repo, parent_snapshot)
        if not expected:
            # Unlistable, or listed nothing: either way nothing is known, and
            # "assume changed" costs a sync rather than losing work.
            return True, None
        if local_nodes_differ(data_path, expected):
            return True, None
        return False, _pre_check_unix

# %% pts/mod/_restic.pct.py 29
class ResticCondition(Enum):
    """Named to line up with `SyncCondition`, so the mapping is mechanical."""

    SYNCED = "synced"
    NEEDS_PUSH = "needs_push"
    NEEDS_PULL = "needs_pull"
    CONFLICT = "conflict"
    # No repo or no pointer on the remote: this box has never been pushed in
    # this format. A legitimate, expected state, not an error.
    UNINITIALISED = "uninitialised"


@dataclass(frozen=True)
class ResticStatus:
    condition: ResticCondition
    remote_snapshot: str | None = None
    local_snapshot: str | None = None
    local_modified: bool = False
    # Set when "not modified" was proved by the FULL check rather than the
    # cheap gate: the moment captured before that check read the tree. The
    # sync path re-stamps `synced_at_unix` with it, closing the gate that an
    # excluded-name arrival would otherwise hold open for ever.
    clean_check_at_unix: "float | None" = None


async def count_tracked_files(
    repo: ResticRepo,
    data_path: Path,
    *,
    excludes: list[str] | None = None,
    box_index_name: str | None = None,
) -> int | None:
    """
    How many files restic would walk in this tree, right now.

    Measured the SAME way `local_is_modified` compares it -- a dry-run's
    `total_files_processed` -- rather than by counting the tree here, which
    would be a second implementation of the exclude rules that could disagree.

    Recorded after a PULL as well as after a push. Without it a pulled box has
    no count, "no count" means "assume changed", and the box would push a
    redundant snapshot on every single pass.
    """
    with _backup_path(box_index_name, data_path) as (effective_path, _):
        args = ["backup", "--dry-run", "--json"] + _backup_args(
            effective_path, excludes
        )
        args.append(str(effective_path))
        returncode, stdout, _ = await run_restic(repo, args, check=False)
    if returncode != 0:
        return None
    for line in stdout.splitlines():
        try:
            message = json.loads(line)
        except json.JSONDecodeError:
            continue
        if message.get("message_type") == "summary":
            return int(message.get("total_files_processed", 0))
    return None


async def get_status(
    repo: ResticRepo,
    data_path: Path,
    *,
    remote_snapshot: str | None,
    local_snapshot: str | None,
    synced_at_unix: float | None = None,
    excludes: list[str] | None = None,
    box_index_name: str | None = None,
    expected_files: int | None = None,
    exclude_names: "set[str] | None" = None,
) -> ResticStatus:
    """
    Map (remote pointer, local record, local tree) onto a condition.

    Survives retention: if the locally recorded snapshot has been forgotten, an
    unmodified replica still reports NEEDS_PULL and only a genuinely edited one
    reports CONFLICT. See `local_is_modified`.
    """
    if remote_snapshot is None:
        return ResticStatus(ResticCondition.UNINITIALISED, None, local_snapshot, True)

    modified, clean_check_at = await local_is_modified(
        repo,
        data_path,
        local_snapshot,
        synced_at_unix=synced_at_unix,
        excludes=excludes,
        box_index_name=box_index_name,
        expected_files=expected_files,
        exclude_names=exclude_names,
    )

    if local_snapshot == remote_snapshot:
        return ResticStatus(
            ResticCondition.NEEDS_PUSH if modified else ResticCondition.SYNCED,
            remote_snapshot,
            local_snapshot,
            modified,
            clean_check_at_unix=clean_check_at,
        )

    if modified:
        return ResticStatus(
            ResticCondition.CONFLICT, remote_snapshot, local_snapshot, True
        )
    return ResticStatus(
        ResticCondition.NEEDS_PULL, remote_snapshot, local_snapshot, False
    )

# %% pts/mod/_restic.pct.py 31
@dataclass
class PushResult:
    snapshot_id: str
    source_path: str
    # How many files the snapshot holds. Recorded in the local state so a later
    # pass can notice a DELETION, which `backup --dry-run` cannot see.
    files: int = 0
    # False when this machine could not use the canonical root and backed up
    # through its own path instead. Expected to be True on every machine in the
    # live fleet, so a False is a MACHINE-level fault worth reporting -- a `/tmp`
    # that is a symlink, world-writable, or owned by someone else. The box still
    # syncs correctly; the cost is that every other machine loses `--parent`
    # matching and diff-based pulls for it until one of them pushes again.
    #
    # It is returned rather than logged here because this layer takes paths and
    # knows nothing about boxes or machines -- the same reason ownership is
    # decided in `sync_box` and not in `sync_helper`.
    canonical: bool = True


async def push(
    repo: ResticRepo,
    data_path: Path,
    *,
    parent: str | None = None,
    excludes: list[str] | None = None,
    exclude_file: Path | None = None,
    box_index_name: str | None = None,
) -> PushResult:
    """
    Back the box's DATA up. Returns the new snapshot id and the path it records.

    Deliberately does NOT write the pointer or the local state record: the
    caller does that, so the ordering (snapshot first, then pointer, then local
    state) stays visible at the call site rather than buried here.
    """
    with _backup_path(box_index_name, data_path) as (effective_path, canonical):
        args = ["backup", "--json"] + _backup_args(effective_path, excludes)
        if exclude_file is not None:
            args += ["--exclude-file", str(exclude_file)]
        if parent:
            args += ["--parent", parent]
        args.append(str(effective_path))

        _, stdout, stderr = await run_restic(repo, args)

    snapshot_id = None
    file_count = 0
    for line in stdout.splitlines():
        try:
            message = json.loads(line)
        except json.JSONDecodeError:
            continue
        if message.get("message_type") == "summary":
            snapshot_id = message.get("snapshot_id")
            file_count = int(message.get("total_files_processed", 0))
    if not snapshot_id:
        raise ResticError(
            f"restic backup of '{data_path}' reported no snapshot id.\n"
            f"{stdout}\n{stderr}"
        )

    source = await snapshot_source_path(repo, snapshot_id)
    if source is None:
        raise ResticError(
            f"restic backup created snapshot {snapshot_id} but it has no "
            f"recorded source path."
        )
    return PushResult(
        snapshot_id=snapshot_id, source_path=source, canonical=canonical,
        files=file_count,
    )

# %% pts/mod/_restic.pct.py 32
async def estimate_stored_bytes(
    repo: ResticRepo,
    data_path: Path,
    *,
    box_index_name: str | None = None,
    excludes: list[str] | None = None,
) -> int:
    """
    How many bytes restic would actually store for this tree, measured.

    `data_added_packed` from a dry-run backup: the compressed, packed size after
    deduplication, which is what lands on the remote. Not an estimate from a
    ratio -- deduplication and compression are content-dependent and a ratio
    quoted from another box would be a guess presented as a measurement.
    """
    with _backup_path(box_index_name, data_path) as (effective_path, _):
        args = ["backup", "--dry-run", "--json"] + _backup_args(
            effective_path, excludes
        )
        args.append(str(effective_path))
        _, stdout, _ = await run_restic(repo, args)

    for line in stdout.splitlines():
        try:
            message = json.loads(line)
        except json.JSONDecodeError:
            continue
        if message.get("message_type") == "summary":
            return int(message.get("data_added_packed", 0))
    raise ResticError("restic backup --dry-run reported no summary")

# %% pts/mod/_restic.pct.py 34
class PullMode(Enum):
    FULL = "full"
    # Never restored here, or the state record was lost.
    FULL_NO_BASE = "full-no-base"
    # The base was FORGOTTEN by a retention pass on another machine. Normal and
    # expected, not an error.
    FULL_BASE_FORGOTTEN = "full-base-forgotten"
    # Base and target were pushed from DIFFERENT absolute paths, so `restic
    # diff` would report everything as added and removed. Acting on that diff
    # would delete the box and restore it.
    FULL_PATH_MISMATCH = "full-path-mismatch"
    # `restic diff` itself failed.
    FULL_DIFF_FAILED = "full-diff-failed"
    # The snapshots differ but `restic diff` named no file: the change is
    # METADATA only -- a mode, or a symlink's target. Measured (restic 0.18.0):
    # after a `chmod` or an `ln -sfn` retarget, diff reports "0 new, 0 removed,
    # 0 changed" and moves only tree blobs. Restoring the named files would
    # therefore restore nothing and the replica would silently keep the old mode
    # for ever, so this falls back to a full restore.
    FULL_METADATA_ONLY = "full-metadata-only"
    DIFF = "diff"


@dataclass
class PullResult:
    mode: PullMode
    snapshot_id: str
    changed: int = 0
    removed: int = 0


def parse_diff(stdout: str, source_prefix: str) -> tuple[list[str], list[str]]:
    """
    `(changed-or-added, removed)` as paths RELATIVE to the snapshot's source.

    restic prints one line per path prefixed `+`, `-`, `M`, `U` or `T`, using
    the absolute path recorded in the snapshot. Only `-` means "gone in the
    newer snapshot"; everything else needs restoring.
    """
    changed: list[str] = []
    removed: list[str] = []
    prefix = source_prefix.rstrip("/")
    for line in stdout.splitlines():
        if len(line) < 2 or line[0] not in "+-MUT" or line[1] != " ":
            continue
        mark, path = line[0], line[2:].strip()
        if not path.startswith(prefix):
            continue
        rel = path[len(prefix):].strip("/")
        if not rel:
            continue
        (removed if mark == "-" else changed).append(rel)
    return changed, removed


def apply_removals(data_path: Path, rel_paths: list[str]) -> int:
    """
    Delete paths the newer snapshot no longer has. Returns how many were removed.

    `restore --include` does NOT delete -- verified: a file absent from the
    newer snapshot survives an --include restore and is only removed by a full
    `restore --delete`. Without this a file deleted on another machine silently
    comes back, which is the exact class of bug tombstones exist to prevent.
    """
    root = Path(data_path).resolve()
    removed = 0
    # Deepest first, so a directory is emptied before it is removed.
    for rel in sorted(rel_paths, key=lambda p: p.count("/"), reverse=True):
        # A path out of the repo is DATA, not an instruction: `..` must not
        # escape the box's own DATA directory, and `.` must not delete the box.
        normalised = os.path.normpath(rel)
        if (
            os.path.isabs(normalised)
            or normalised in (".", "")
            or normalised == ".."
            or normalised.startswith(".." + os.sep)
        ):
            continue

        victim = Path(data_path) / normalised
        # Resolve the PARENT, not the victim. Resolving the victim follows it
        # when it is itself a symlink, so a link pointing outside the box would
        # look like an escape attempt and be skipped -- leaving a file the newer
        # snapshot has deleted sitting on disk forever. Deleting the LINK is
        # both correct and safe; it never touches what the link points at.
        # Resolving the parent still catches the real escape, which is a
        # symlinked DIRECTORY on the way down.
        try:
            victim.parent.resolve().relative_to(root)
        except (ValueError, OSError):
            continue

        if victim.is_symlink():
            victim.unlink(missing_ok=True)
            removed += 1
        elif victim.is_file():
            victim.unlink(missing_ok=True)
            removed += 1
        elif victim.is_dir():
            shutil.rmtree(victim, ignore_errors=True)
            removed += 1
    return removed


def matches_restic_exclude(rel: str, excludes: list[str]) -> bool:
    """
    Would `excludes` (translated restic patterns) exclude this relative path?

    Mirrors restic's unanchored-pattern semantics the way `convert`'s verifier
    does: an unanchored pattern matches ANY path component (excluding `.venv`
    prunes everything beneath it), an anchored one matches from the box root.
    Used to keep pulls off excluded content -- see `pull` -- so erring towards
    True merely leaves a local file alone.
    """
    import fnmatch

    components = rel.split("/")
    for pattern in excludes:
        if pattern.startswith("/"):
            anchored = pattern.lstrip("/")
            if fnmatch.fnmatch(rel, anchored) or rel.startswith(anchored + "/"):
                return True
        elif any(fnmatch.fnmatch(c, pattern) for c in components):
            return True
    return False


async def pull(
    repo: ResticRepo,
    data_path: Path,
    *,
    target_snapshot: str,
    base_snapshot: str | None,
    excludes: list[str],
) -> PullResult:
    """
    Bring the local tree to `target_snapshot`.

    `excludes` is REQUIRED, not defaulted: the full-mode restore below runs
    with `--delete`, and without the box's exclude patterns it deletes local
    excluded content -- `.venv/` and friends, which the snapshot deliberately
    never carried. Measured on restic 0.18.0, and unlike a plain pull there is
    no `--backup-dir`, so what it deletes is locally unrecoverable. The
    exclude contract everywhere else in boxyard is "excluded content is
    local-only and untouched"; a defaulted `[]` here would let a new caller
    silently violate it. A caller restoring into an EMPTY or throwaway target
    (convert's verifier) passes `[]` explicitly and says why.
    """
    data_path = Path(data_path)
    data_path.mkdir(parents=True, exist_ok=True)

    target_source = await snapshot_source_path(repo, target_snapshot)
    if target_source is None:
        raise ResticError(
            f"snapshot {target_snapshot} is not in '{repo.url}', or has no "
            f"recorded source path."
        )

    _exclude_args = [arg for pat in excludes for arg in ("--exclude", pat)]

    async def _full(mode: PullMode) -> PullResult:
        # `<snap>:<source>` places the snapshot's CONTENTS at the target,
        # rather than at `<target>/<absolute source path>` which the plain form
        # produces. That is what makes the local checkout path independent of
        # the pusher's -- mymain alone has two checkout roots.
        #
        # The excludes ride along so `--delete` cannot touch local excluded
        # content (verified: restic's restore filters also decide what gets
        # deleted). They cost the restore nothing -- the snapshot never held
        # those paths to begin with.
        await run_restic(
            repo,
            [
                "restore",
                f"{target_snapshot}:{target_source}",
                "--target",
                str(data_path),
                "--delete",
            ]
            + _exclude_args,
        )
        return PullResult(mode=mode, snapshot_id=target_snapshot)

    if base_snapshot is None:
        return await _full(PullMode.FULL_NO_BASE)
    if base_snapshot == target_snapshot:
        return await _full(PullMode.FULL)

    base_source = await snapshot_source_path(repo, base_snapshot)
    if base_source is None:
        return await _full(PullMode.FULL_BASE_FORGOTTEN)
    if base_source != target_source:
        return await _full(PullMode.FULL_PATH_MISMATCH)

    returncode, stdout, _ = await run_restic(
        repo,
        ["diff", base_snapshot, target_snapshot],
        timeout=const.RESTIC_METADATA_TIMEOUT,
        check=False,
    )
    if returncode != 0:
        return await _full(PullMode.FULL_DIFF_FAILED)

    changed, removed = parse_diff(stdout, target_source)

    if not changed and not removed:
        # The two snapshots are not the same, or this function would not have
        # been called with different ids -- so a diff that names nothing means
        # the difference is metadata `restic diff` does not report. Restoring
        # the named files would restore NOTHING and leave the replica holding
        # the old mode or the old symlink target, permanently and silently.
        #
        # This is the same blindness as the detection side: `restic diff`
        # reports FILES, and a mode is not a file. Found by an end-to-end test
        # where a `chmod +x` pushed correctly and never arrived.
        return await _full(PullMode.FULL_METADATA_ONLY)

    if changed:
        await run_restic(
            repo,
            [
                "restore",
                f"{target_snapshot}:{target_source}",
                "--target",
                str(data_path),
            ]
            + anchored_include_args(changed),
        )

    # The diff tier needs the same protection as the full tier, for a subtler
    # reason: the diff names what changed BETWEEN SNAPSHOTS, and the exclude
    # list can change between them too. Add `.coverage` to the excludes, push,
    # and the newer snapshot simply lacks every `.coverage` -- so the diff says
    # "removed", and a replica's pull would delete its local copies of files
    # that were never deleted anywhere, merely excluded. Excluded content is
    # local-only and untouched, on every tier.
    removed = [r for r in removed if not matches_restic_exclude(r, excludes)]
    removed_count = apply_removals(data_path, removed)
    return PullResult(
        mode=PullMode.DIFF,
        snapshot_id=target_snapshot,
        changed=len(changed),
        removed=removed_count,
    )
