# AUTOGENERATED! DO NOT EDIT! File to edit: pts/mod/_sync_policy.pct.py

__all__ = ['BOX_OVERRIDABLE', 'BOX_SYNC_CONF_FILENAME', 'DEFAULT_STORAGE_FORMAT', 'DEFAULT_STORAGE_FORMAT_LOCAL', 'DueResult', 'PolicyConflict', 'RemoteRecordView', 'ResolvedPolicy', 'SCHEDULABLE_PARTS', 'SYNC_CHECKS_REL_PATH', 'SkipVerdicts', 'boxes_needing_sync_full', 'check_record_path', 'closure_of', 'conf_provably_unchanged', 'data_boxes_needing_sync', 'default_storage_format', 'due_boxes', 'matching_policies', 'meta_provably_unchanged', 'plain_data_provably_unchanged', 'project_record_listing', 'read_box_sync_override', 'read_check_record', 'remote_looks_unchanged', 'resolve_policy', 'write_check_record']

# %% pts/mod/_sync_policy.pct.py 2
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import boxyard.config
from . import const
from ._models import BoxMeta
from ._enums import BoxPart, StorageFormat

# %% pts/mod/_sync_policy.pct.py 3
SYNC_CHECKS_REL_PATH = "sync_checks"

BOX_SYNC_CONF_FILENAME = "sync.toml"

# The parts a cadence can be set for. CONF deliberately has none: it is tiny,
# it rides the DATA sync that needs it (its rclone filters are read before the
# DATA transfer), and a separate cadence for it would be a knob with no
# question behind it.
SCHEDULABLE_PARTS = (BoxPart.DATA, BoxPart.META)


class PolicyConflict(Exception):
    """
    A box matches two policies that state DIFFERENT values for one dimension.

    Carries the box, the dimension and the competing policies so the message
    names what to fix rather than only that something is wrong.
    """

    def __init__(
        self, box_index_name: str, dimension: str, choices: dict[str, Any]
    ):
        self.box_index_name = box_index_name
        self.dimension = dimension
        self.choices = choices
        rendered = ", ".join(
            f"{name}={value!r}" for name, value in sorted(choices.items())
        )
        super().__init__(
            f"Box '{box_index_name}' matches policies that disagree on "
            f"'{dimension}': {rendered}. Set '{dimension}' in the box's own "
            f"conf/{BOX_SYNC_CONF_FILENAME} to settle it, or stop the box "
            f"matching more than one of these policies."
        )


@dataclass(frozen=True)
class ResolvedPolicy:
    """
    The effective settings for one box, plus where each came from.

    `sources` exists so `doctor` and `--explain` can answer "why is this box on
    a 7-day cadence" without the user reverse-engineering the resolution order.
    """

    data_interval_seconds: int | None
    meta_interval_seconds: int | None
    # The format this box SHOULD have. NOT what it has -- that is
    # `BoxMeta.storage_format`, and only `boxyard convert` changes it. Nothing
    # acts on this yet; `doctor` reports where the two differ.
    storage_format: StorageFormat = StorageFormat.PLAIN
    sources: dict[str, str] = field(default_factory=dict)

    def interval_seconds(self, part: BoxPart) -> int | None:
        if part == BoxPart.DATA:
            return self.data_interval_seconds
        if part == BoxPart.META:
            return self.meta_interval_seconds
        raise ValueError(f"{part} has no cadence; schedulable parts are {SCHEDULABLE_PARTS}")


# The settings a box may override in its own conf/, and the policy field each
# maps to. Kept explicit rather than derived from SyncPolicyConfig because
# `groups` is a policy-level concept that a single box must not be able to set.
BOX_OVERRIDABLE = ("data_interval", "meta_interval", "storage_format")

# The format a NEW box gets when no policy says otherwise.
#
# `restic` for a remote storage location, because that is what the measurements
# argue for and `plain` is now the deliberate exception. `plain` for a `local`
# one: there is no remote, so the per-file transaction cost that motivates the
# whole design does not exist, and a repository would only add a key to lose.
#
# This governs CREATION ONLY. An existing box keeps whatever
# `BoxMeta.storage_format` records until an explicit `boxyard convert` changes
# it, and `doctor` reports the difference. A config edit must never reformat the
# primary copy of everything on the next pass.
DEFAULT_STORAGE_FORMAT = StorageFormat.RESTIC
DEFAULT_STORAGE_FORMAT_LOCAL = StorageFormat.PLAIN


def default_storage_format(
    config: boxyard.config.Config, box_meta: BoxMeta
) -> StorageFormat:
    """The format a box of this kind gets when no policy states one."""
    from .config import StorageType

    sl_config = config.storage_locations.get(box_meta.storage_location)
    if sl_config is None or sl_config.storage_type == StorageType.LOCAL:
        return DEFAULT_STORAGE_FORMAT_LOCAL
    return DEFAULT_STORAGE_FORMAT

# %% pts/mod/_sync_policy.pct.py 4
def read_box_sync_override(
    config: boxyard.config.Config, box_meta: BoxMeta
) -> dict[str, Any]:
    """
    Read a box's own `conf/sync.toml`, or `{}` if it has none.

    A box without the file is the normal case, not a problem -- almost no box
    will have one. A box WITH an unparseable one is a loud failure: it was
    written deliberately, so silently ignoring it would apply a cadence the
    author did not ask for and never say so.
    """
    import tomllib

    path = (
        box_meta.get_local_part_path(config, BoxPart.CONF)
        / BOX_SYNC_CONF_FILENAME
    )
    if not path.exists():
        return {}
    try:
        with open(path, "rb") as f:
            parsed = tomllib.load(f)
    except tomllib.TOMLDecodeError as exc:
        raise ValueError(f"{path}: not valid TOML: {exc}") from exc

    unknown = set(parsed) - set(BOX_OVERRIDABLE)
    if unknown:
        raise ValueError(
            f"{path}: unknown key(s) {sorted(unknown)}. A box may set "
            f"{list(BOX_OVERRIDABLE)}; 'groups' is a policy-level concept and "
            f"cannot be set per box."
        )
    return parsed


def matching_policies(
    config: boxyard.config.Config, box_meta: BoxMeta
) -> dict[str, "boxyard.config.SyncPolicyConfig"]:
    """
    The named policies whose `groups` intersect this box's groups.

    The `default` policy is NOT included: it is the floor every box falls back
    to, so counting it as a match would make every box that matches any policy
    look ambiguous.
    """
    out = {}
    for name, policy in config.sync_policies.items():
        if name == "default":
            continue
        if set(policy.groups) & set(box_meta.groups):
            out[name] = policy
    return out


def _resolve_dimension(
    box_index_name: str,
    dimension: str,
    override: dict[str, Any],
    matched: dict[str, Any],
    default: Any,
    default_source: str,
) -> tuple[Any, str]:
    """
    Resolve ONE dimension: box override, then matched policies, then default.

    Two matched policies stating the SAME value is not a conflict -- a box in
    both `archived` and `dormant`, where both map to the same cold settings,
    has been asked for one thing twice. Only genuinely different values raise.
    """
    if dimension in override and override[dimension] is not None:
        return override[dimension], f"conf/{BOX_SYNC_CONF_FILENAME}"

    stated = {
        name: value for name, value in matched.items() if value is not None
    }
    distinct = set(stated.values())
    if len(distinct) > 1:
        raise PolicyConflict(box_index_name, dimension, stated)
    if stated:
        name = sorted(stated)[0]
        return stated[name], f"sync_policies.{name}"

    return default, default_source


def resolve_policy(
    config: boxyard.config.Config, box_meta: BoxMeta
) -> ResolvedPolicy:
    """
    The effective sync policy for one box.

    With no `[sync_policies.*]` configured at all this returns intervals of
    `None` -- meaning "no cadence, always due" -- which is what keeps an
    un-opted-in fleet behaving exactly as it does today.
    """
    override = read_box_sync_override(config, box_meta)
    matched = matching_policies(config, box_meta)
    default = config.sync_policies.get("default")

    def _defaults(dimension: str):
        if default is None:
            return None, "unset"
        return getattr(default, dimension), "sync_policies.default"

    sources: dict[str, str] = {}
    resolved: dict[str, Any] = {}
    for dimension in BOX_OVERRIDABLE:
        default_value, default_source = _defaults(dimension)
        value, source = _resolve_dimension(
            box_meta.index_name,
            dimension,
            override,
            {name: getattr(p, dimension) for name, p in matched.items()},
            default_value,
            default_source,
        )
        resolved[dimension] = value
        sources[dimension] = source

    def _seconds(dimension: str) -> int | None:
        raw = resolved[dimension]
        if raw is None:
            return None
        if not isinstance(raw, str):
            raise ValueError(
                f"Box '{box_meta.index_name}': {dimension} must be a string "
                f"like '6h' (from {sources[dimension]}); got {raw!r}"
            )
        return boxyard.config.parse_interval(
            raw, f"{sources[dimension]}.{dimension}"
        )

    def _format() -> StorageFormat:
        raw = resolved["storage_format"]
        if raw is None:
            return default_storage_format(config, box_meta)
        try:
            return StorageFormat(raw)
        except ValueError:
            raise ValueError(
                f"Box '{box_meta.index_name}': storage_format must be one of "
                f"{[f.value for f in StorageFormat]} (from "
                f"{sources['storage_format']}); got {raw!r}"
            ) from None

    return ResolvedPolicy(
        data_interval_seconds=_seconds("data_interval"),
        meta_interval_seconds=_seconds("meta_interval"),
        storage_format=_format(),
        sources=sources,
    )

# %% pts/mod/_sync_policy.pct.py 5
def check_record_path(
    config: boxyard.config.Config, box_index_name: str, part: BoxPart
) -> Path:
    return (
        config.boxyard_data_path
        / SYNC_CHECKS_REL_PATH
        / box_index_name
        / f"{part.value}.json"
    )


def read_check_record(
    config: boxyard.config.Config, box_index_name: str, part: BoxPart
) -> dict[str, Any] | None:
    """
    The record of the last successful CHECK of this (box, part), or None.

    None means "never checked, or the record is unusable" and every caller must
    read it as "do the work". Corruption is deliberately NOT raised: this file
    is a local optimisation, it is regenerated by doing the sync it would have
    skipped, and refusing to sync a box because a cache file got truncated
    would turn a harmless local problem into a stalled box.
    """
    path = check_record_path(config, box_index_name, part)
    if not path.exists():
        return None
    try:
        record = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError, UnicodeDecodeError):
        return None
    if not isinstance(record, dict):
        return None
    if not isinstance(record.get("last_checked_unix"), (int, float)):
        return None
    return record


def write_check_record(
    config: boxyard.config.Config,
    box_index_name: str,
    part: BoxPart,
    now_unix: float,
    remote_modtime: str | None = None,
    remote_size: int | None = None,
) -> Path:
    """
    Record that this (box, part) was successfully checked at `now_unix`.

    `remote_modtime`/`remote_size` are what the bulk listing reported for the
    remote object at that moment. The META skip filter compares them against a
    later listing to decide whether anything moved -- see
    `remote_looks_unchanged`.

    Written via a temp file in the same directory then renamed, so a crash
    mid-write leaves either the old record or the new one, never a truncated
    file that reads as "never checked" and silently costs a full pass.
    """
    import os
    import tempfile

    path = check_record_path(config, box_index_name, part)
    path.parent.mkdir(parents=True, exist_ok=True)

    # A caller with no stamp to offer must not ERASE the one already recorded.
    # An ordinary `multi-sync` pass records only a timestamp, and wiping the
    # stamp would disarm the skip filter every time an unfiltered pass ran --
    # so the filter could never take effect on a machine that also runs the
    # normal DATA pass, which is every machine.
    #
    # Carrying an older stamp forward is the SAFE direction: if the remote moved
    # since, the next listing reports a different ModTime/Size and the box is
    # synced. A stale stamp can only ever cause extra work, never a wrong skip.
    if remote_modtime is None and remote_size is None:
        previous = read_check_record(config, box_index_name, part)
        if previous is not None:
            remote_modtime = previous.get("remote_modtime")
            remote_size = previous.get("remote_size")

    record = {
        "last_checked_unix": now_unix,
        "remote_modtime": remote_modtime,
        "remote_size": remote_size,
    }
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".tmp-", suffix=".json")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(json.dumps(record))
        os.replace(tmp, path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise
    return path


@dataclass
class DueResult:
    """
    What `due_boxes` found: the boxes to sync, and the boxes it could not
    decide about.

    Conflicts are RETURNED rather than raised. Raising would let one
    misconfigured box halt a whole pass, and dropping it silently would be the
    fallback this codebase forbids. Instead a conflicted box is reported AND
    included in `due` -- syncing it is the safe direction, since the ambiguity
    is only about how OFTEN to sync, never about whether it is allowed.
    """

    due: list[str] = field(default_factory=list)
    conflicts: list[PolicyConflict] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)


def due_boxes(
    config: boxyard.config.Config,
    box_metas: list[BoxMeta],
    part: BoxPart,
    now_unix: float,
) -> DueResult:
    """
    Which boxes are due for a `part` sync at `now_unix`, most overdue first.

    Pure local: reads the check records and the box groups already on disk, and
    makes ZERO remote calls. Measured at 171 ms across 590 boxes, which is what
    lets the scheduling loop wake every 15 minutes without costing anything.

    A box with no cadence -- because no policy configured one -- is ALWAYS due.
    That is what makes an un-opted-in config behave exactly as it does today.
    """
    if part not in SCHEDULABLE_PARTS:
        raise ValueError(
            f"{part} is not schedulable; schedulable parts are {SCHEDULABLE_PARTS}"
        )

    result = DueResult()
    overdue_by: dict[str, float] = {}

    for box_meta in box_metas:
        index_name = box_meta.index_name
        try:
            policy = resolve_policy(config, box_meta)
        except PolicyConflict as conflict:
            result.conflicts.append(conflict)
            result.due.append(index_name)
            overdue_by[index_name] = float("inf")
            continue

        interval = policy.interval_seconds(part)
        if interval is None:
            result.due.append(index_name)
            overdue_by[index_name] = float("inf")
            continue

        record = read_check_record(config, index_name, part)
        if record is None:
            result.due.append(index_name)
            overdue_by[index_name] = float("inf")
            continue

        age = now_unix - float(record["last_checked_unix"])
        if age >= interval:
            result.due.append(index_name)
            overdue_by[index_name] = age - interval
        else:
            result.skipped.append(index_name)

    # Most overdue first. A machine that was off comes back with everything
    # due at once; ordering by overdue-ness means the longest-neglected boxes
    # go first rather than whatever order the registry happened to hold.
    result.due.sort(key=lambda name: (-overdue_by[name], name))
    return result


def remote_looks_unchanged(
    record: dict[str, Any] | None, remote_modtime: str | None, remote_size: int | None
) -> bool:
    """
    Whether the remote object matches what was recorded at the last check.

    Both fields must be present and equal. A record that never captured them
    (an older boxyard wrote it) returns False -- "assume changed" -- so an
    upgrade costs one full pass rather than silently skipping every box.

    This is only ever an optimisation: see the note at the top of this module
    for why a false "changed" is harmless and a false "unchanged" cannot arise.
    """
    if record is None:
        return False
    recorded_modtime = record.get("remote_modtime")
    recorded_size = record.get("remote_size")
    if recorded_modtime is None or recorded_size is None:
        return False
    if remote_modtime is None or remote_size is None:
        return False
    return recorded_modtime == remote_modtime and recorded_size == remote_size

# %% pts/mod/_sync_policy.pct.py 7
def data_boxes_needing_sync(
    config: boxyard.config.Config,
    box_metas: list[BoxMeta],
    remote_listing: dict[str, tuple[str | None, int | None]],
) -> tuple[list[str], list[str]]:
    """
    Split boxes into (needs a DATA sync, provably does not).

    Rides the bulk `boxes/` listing: `boxes/<box>/data.snapshot` sits at depth
    2 beside `boxmeta.toml`, so the listing `multi-sync` already takes answers
    this too.

    Only RESTIC boxes are judged here: a plain box's DATA is proven by record
    identity plus fingerprint in `plain_data_provably_unchanged`, and
    `boxes_needing_sync_full` routes each format to its own predicate. A plain
    box handed to this function is always reported as needed.

    Two conditions, both cheap:

    - the remote pointer has not moved, by (ModTime, Size) against what was
      recorded at the last check;
    - the local tree has not been TOUCHED since this machine last agreed, by
      `tree_touched_since` -- the same gate the restic backend uses to decide
      whether to talk to the repository at all.

    Skipping is ONLY ever an optimisation. A wrong "changed" costs a sync. A
    wrong "unchanged" LOSES DATA, silently, until something else moves.

    IT USED TO USE `tree_modified_since`, AND THAT WAS TWO BUGS ON ONE LINE:

    1. That helper is the plain backend's newest-mtime walk, which sees two of
       ten change shapes. A restic box whose only change was a lone deletion, a
       rename, a chmod or a symlink edit was declared "provably unchanged" and
       skipped -- so it was never backed up, while this docstring claimed a
       wrong "unchanged" was prevented. `tree_touched_since` stats directories
       and uses max(mtime, ctime), which catches all of them; its false
       positives cost the real path one local check, which is precisely the
       trade a gate is allowed to make.
    2. It was called with NO exclude names, so any `.DS_Store` counted as a
       change. On a fleet with Macs in it that likely meant the filter never
       skipped anything at all -- the optimisation silently defeating itself,
       in the harmless direction, which is why nobody noticed.
    """
    from ._enums import StorageFormat
    from ._restic import read_state, tree_touched_since
    from ._utils import literal_exclude_names

    needed: list[str] = []
    skippable: list[str] = []

    for box_meta in box_metas:
        index_name = box_meta.index_name
        if box_meta.storage_format is not StorageFormat.RESTIC:
            needed.append(index_name)
            continue

        remote_modtime, remote_size = remote_listing.get(index_name, (None, None))
        record = read_check_record(config, index_name, BoxPart.DATA)
        if not remote_looks_unchanged(record, remote_modtime, remote_size):
            needed.append(index_name)
            continue

        state = read_state(config.boxyard_data_path, index_name)
        if state is None or state.get("pulling_from"):
            # No local state, or a restore that was interrupted. Both mean the
            # real path has work to do and must not be skipped.
            needed.append(index_name)
            continue

        synced_at = state.get("synced_at_unix")
        data_path = box_meta.get_local_part_path(config, BoxPart.DATA)
        if synced_at is None or not data_path.is_dir():
            needed.append(index_name)
            continue
        _conf_exclude = (
            box_meta.get_local_part_path(config, BoxPart.CONF)
            / const.RCLONE_EXCLUDE_FILENAME
        )
        _exclude_names = literal_exclude_names(
            _conf_exclude
            if _conf_exclude.exists()
            else config.default_rclone_exclude_path
        )
        if tree_touched_since(data_path, float(synced_at), _exclude_names):
            needed.append(index_name)
            continue

        skippable.append(index_name)

    return needed, skippable

# %% pts/mod/_sync_policy.pct.py 9
from ._models import parse_record_marker


# What a bulk listing of `sync_records/` tells us about one box.
@dataclass
class RemoteRecordView:
    """Per box: which `<part>.rec` files exist, and each part's marker ULIDs."""

    records: set[str] = field(default_factory=set)
    markers: dict[str, list[str]] = field(default_factory=dict)

    def identity(self, part: BoxPart) -> str | None:
        """The remote record ULID for `part`, or None when it is not KNOWN --
        no marker, or more than one (a crash between marker and sweep)."""
        ulids = self.markers.get(part.value, [])
        return ulids[0] if len(ulids) == 1 else None


def project_record_listing(entries: list[dict[str, Any]] | None) -> dict[str, RemoteRecordView]:
    """
    {index_name: RemoteRecordView} from ONE `rclone lsjson` over
    `<store>/sync_records/`, depth 2, files only.

    Exact keying: a path must have exactly two components, and the filename
    must be either `<part>.rec` or a well-formed marker. rclone's
    `<name>.<hash>.partial` upload residue, sidecars copied by hand, and
    anything deeper all fall through -- never keyed as a part.
    """
    view: dict[str, RemoteRecordView] = {}
    for entry in entries or []:
        parts = Path(entry["Path"]).parts
        if len(parts) != 2:
            continue
        box, name = parts
        if name.endswith(".rec") and name.count(".") == 1:
            view.setdefault(box, RemoteRecordView()).records.add(name[: -len(".rec")])
            continue
        parsed = parse_record_marker(name)
        if parsed is not None:
            part, ulid = parsed
            view.setdefault(box, RemoteRecordView()).markers.setdefault(part, []).append(ulid)
    return view


def closure_of(parts: "list[BoxPart]") -> "set[BoxPart]":
    """
    The parts `sync_box` actually executes for a request. DATA drags META
    (ownership is read from it) and CONF (its filters decide what DATA syncs)
    along, so a `-c data` pass must prove all three before skipping a box --
    a remote CONF edit would otherwise never reach this machine.
    """
    closure: set[BoxPart] = set(parts)
    if BoxPart.DATA in closure:
        closure |= {BoxPart.META, BoxPart.CONF}
    return closure


def _record_identity_and_tree_unchanged(
    config: boxyard.config.Config,
    box_meta: BoxMeta,
    part: BoxPart,
    remote_ulid: str | None,
    exclude_file,
) -> bool:
    """The three gates every content-bearing part shares. See the module note."""
    from ._fingerprint import filter_signature, local_tree_differs
    from ._models import SyncRecord

    if remote_ulid is None:
        return False
    rec_path = box_meta.get_local_sync_record_path(config, part)
    try:
        rec = SyncRecord.model_validate_json(rec_path.read_text())
    except (OSError, ValueError):
        return False
    if not rec.sync_complete or str(rec.ulid) != remote_ulid:
        return False
    differs = local_tree_differs(
        local_path=box_meta.get_local_part_path(config, part),
        local_sync_record_path=rec_path,
        local_sync_record_ulid=rec.ulid,
        rclone_config_path=config.rclone_config_path,
        exclude_file=exclude_file,
        filter_sig=filter_signature(exclude_file),
    )
    return differs is False


def meta_provably_unchanged(
    config: boxyard.config.Config, box_meta: BoxMeta, view: RemoteRecordView | None
) -> bool:
    if view is None:
        return False
    return _record_identity_and_tree_unchanged(
        config, box_meta, BoxPart.META, view.identity(BoxPart.META), None
    )


def conf_provably_unchanged(
    config: boxyard.config.Config,
    box_meta: BoxMeta,
    view: RemoteRecordView | None,
    remote_conf_dir_present: bool,
) -> bool:
    """
    Two states with nothing to pull are provable without a signal, because
    the real path answers SYNCED and transfers nothing for both (measured:
    `get_sync_status` reads both-sides-absent as SYNCED whatever the records
    say, and a pull whose source is missing returns silently):

    - never-had-CONF: no record, no marker, nothing under the remote `conf/`,
      no local record, no local directory;
    - recorded-but-never-materialized: the remote holds a `conf.rec` but no
      `conf/` directory, and this machine has neither. This is EVERY box
      created by `new_box` as seen from every other machine: it pushes an
      empty conf/, which rclone records but never creates on the remote. It
      must not require a marker, since the bootstrap can only publish one for
      a part this machine holds a record for -- so a remote written by an
      older boxyard would never converge here.

    A remote conf tree without its record is a loud ERROR on the real path
    and must stay one; a local directory or record the remote does not have is
    the real path's to push or warn about. Every other asymmetry goes there.
    """
    rec_path = box_meta.get_local_sync_record_path(config, BoxPart.CONF)
    conf_dir = box_meta.get_local_part_path(config, BoxPart.CONF)
    local_absent = not rec_path.exists() and not conf_dir.exists()
    remote_has_record = view is not None and (
        "conf" in view.records or bool(view.markers.get("conf"))
    )
    if local_absent and not remote_conf_dir_present:
        return True
    if local_absent or not remote_has_record or view is None:
        return False
    return _record_identity_and_tree_unchanged(
        config, box_meta, BoxPart.CONF, view.identity(BoxPart.CONF), None
    )


def plain_data_provably_unchanged(
    config: boxyard.config.Config, box_meta: BoxMeta, view: RemoteRecordView | None
) -> bool:
    """
    Placement decides first, and by EXACT state -- `check_included()` is
    false for MISSING and UNAVAILABLE too, which would have skipped an
    unplugged removable root where the real path raises. EXCLUDED with nothing
    on disk is provable with no signal (the real path could only answer
    EXCLUDED); EXCLUDED with a tree sitting at the path is the real path's to
    report; every other state keeps raising loudly through the real path.
    """
    from ._checkout import LocalCheckoutState

    state = box_meta.get_checkout_status(config).state
    if state is LocalCheckoutState.EXCLUDED:
        return not box_meta.get_local_part_path(config, BoxPart.DATA).exists()
    if state is not LocalCheckoutState.INCLUDED:
        return False
    if view is None:
        return False
    return _record_identity_and_tree_unchanged(
        config,
        box_meta,
        BoxPart.DATA,
        view.identity(BoxPart.DATA),
        box_meta.get_effective_exclude_path(config),
    )


@dataclass
class SkipVerdicts:
    needed: list[str] = field(default_factory=list)
    skippable: list[str] = field(default_factory=list)
    reasons: dict[str, str] = field(default_factory=dict)
    """index_name -> why it is needed (the first part that failed to prove)."""


def boxes_needing_sync_full(
    config: boxyard.config.Config,
    box_metas: list[BoxMeta],
    *,
    requested_parts: "list[BoxPart]",
    record_views: dict[str, RemoteRecordView],
    pointer_listing: dict[str, tuple[str | None, int | None]],
    remote_conf_dirs: set[str],
    tombstoned: set[str],
    skip_meta: bool,
    skip_data: bool,
) -> SkipVerdicts:
    """
    Split boxes into (needed, provably unchanged) for a pass that will execute
    `closure_of(requested_parts)`.

    `record_views` comes from the `sync_records/` listing, `pointer_listing`
    (restic pointers, by index name) and `remote_conf_dirs` (boxes with
    anything under `boxes/<box>/conf/`) from the `boxes/` listing. Each part
    is gated on its own flag -- `--skip-unchanged` for the whole box,
    `--skip-unchanged-meta` for META alone -- and a part without its flag is
    never provable.

    One box's failure to be judged must not abort the pass for 632 others:
    any exception while evaluating a box routes THAT box to needed, printed
    to stderr with its name. The real path then reports its own error.
    """
    import sys

    from ._enums import StorageFormat

    verdicts = SkipVerdicts()
    closure = closure_of(requested_parts)

    for box_meta in box_metas:
        index_name = box_meta.index_name
        try:
            if index_name in tombstoned:
                verdicts.reasons[index_name] = "tombstoned"
                verdicts.needed.append(index_name)
                continue
            view = record_views.get(index_name)
            failed: str | None = None
            for part in (BoxPart.META, BoxPart.CONF, BoxPart.DATA):
                if part not in closure:
                    continue
                if part is BoxPart.META:
                    ok = skip_meta and meta_provably_unchanged(config, box_meta, view)
                elif part is BoxPart.CONF:
                    ok = skip_data and conf_provably_unchanged(
                        config, box_meta, view, index_name in remote_conf_dirs
                    )
                else:
                    if not skip_data:
                        ok = False
                    elif box_meta.storage_format is StorageFormat.RESTIC:
                        _, provable = data_boxes_needing_sync(
                            config, [box_meta], pointer_listing
                        )
                        ok = index_name in provable
                    else:
                        ok = plain_data_provably_unchanged(config, box_meta, view)
                if not ok:
                    failed = part.value
                    break
            if failed is None:
                verdicts.skippable.append(index_name)
            else:
                verdicts.reasons[index_name] = failed
                verdicts.needed.append(index_name)
        except Exception as e:  # one box must not take the pass down
            print(
                f"--skip-unchanged: could not judge '{index_name}', syncing it "
                f"instead ({type(e).__name__}: {e})",
                file=sys.stderr,
            )
            verdicts.reasons[index_name] = f"error: {e}"
            verdicts.needed.append(index_name)

    return verdicts
