# AUTOGENERATED! DO NOT EDIT!

from pathlib import Path
import asyncio

from ..config import get_config
from .._utils import enable_soft_interruption
from .._utils.locking import BoxyardLockManager, LockAcquisitionError, BOX_SYNC_LOCK_TIMEOUT, acquire_lock_async
from .._tombstones import create_tombstone
from .._remote_index import remove_from_remote_index_cache

async def delete_box(
    config_path: Path,
    box_index_name: str,
    soft_interruption_enabled: bool = True,
):
    """ """
    config = get_config(config_path)
    
    if soft_interruption_enabled:
        enable_soft_interruption()
    from boxyard._models import get_boxyard_meta, BoxMeta
    from boxyard._ownership import owner_gate
    
    boxyard_meta = get_boxyard_meta(config)
    
    if box_index_name not in boxyard_meta.by_index_name:
        raise ValueError(f"Box '{box_index_name}' does not exist.")
    
    box_meta = boxyard_meta.by_index_name[box_index_name]
    
    from boxyard._checkout import (
        get_box_checkout_status,
        LocalCheckoutState,
        CheckoutRootUnavailable,
     )
    _checkout_status = get_box_checkout_status(config, box_meta)
    if _checkout_status.state == LocalCheckoutState.UNAVAILABLE:
        raise CheckoutRootUnavailable(
            f"Cannot delete '{box_index_name}': checkout root "
            f"'{_checkout_status.checkout_root}' is unavailable; refusing to confuse "
            "an unreachable copy with an absent one."
        )
    if _checkout_status.state in (LocalCheckoutState.MISSING, LocalCheckoutState.RELOCATING):
        raise RuntimeError(
            f"Cannot delete '{box_index_name}': checkout state is {_checkout_status.state.value}. "
            "Recover the local state first (`boxyard doctor --no-remote`)."
        )
    
    # Ownership is checked BEFORE and INDEPENDENTLY of any force/safety flag. A
    # `--force` that also bypassed ownership would leave the remote holding this
    # machine's data while `boxmeta.toml` still names another machine as the owner
    # -- a lie in shared state, which is worse than a refusal.
    # `delete` purges the REMOTE and writes a tombstone keyed by box id, so it
    # takes the box away from every machine, not just this one.
    owner_gate(
        config,
        BoxMeta.load(config, box_meta.storage_location, box_index_name),
        f"delete '{box_index_name}'",
    )
    import shutil
    from boxyard import const
    from boxyard._models import BoxPart, refresh_boxyard_meta, BoxMeta
    from boxyard._utils import rclone_purge_absent_ok
    from boxyard.config import StorageType
    
    _lock_manager = BoxyardLockManager(config.boxyard_data_path)
    _lock_path = _lock_manager.box_sync_lock_path(box_index_name)
    _lock_manager._ensure_lock_dir(_lock_path)
    _sync_lock = __import__('filelock').FileLock(_lock_path, timeout=0)
    await acquire_lock_async(
        _sync_lock,
        f"box sync ({box_index_name})",
        _lock_path,
        BOX_SYNC_LOCK_TIMEOUT,
    )
    try:
        # Extract box_id for tombstone and cache operations
        box_id = BoxMeta.extract_box_id(box_index_name)
        storage_location = box_meta.storage_location
        _sl_is_remote = (
            box_meta.get_storage_location_config(config).storage_type != StorageType.LOCAL
        )
    
        # Retry rmtree to handle macOS race where Finder recreates .DS_Store mid-delete
        import time
        import errno
        def _rmtree_retry(path):
            for _attempt in range(3):
                try:
                    shutil.rmtree(path)
                    return
                except OSError as e:
                    if e.errno == errno.ENOTEMPTY and _attempt < 2:
                        time.sleep(0.1)
                    else:
                        raise
    
        # Delete the local box FIRST — before creating the tombstone or purging the
        # remote. If a file is owned by another user (root, a container uid, ...) the
        # rmtree fails; doing it first means we abort cleanly with no partial delete,
        # and we surface an actionable error instead of a raw traceback.
        local_box_path = box_meta.get_local_part_path(config, BoxPart.DATA)
        try:
            if local_box_path.exists():
                _rmtree_retry(local_box_path)
        except PermissionError as e:
            raise PermissionError(
                f"Cannot delete box '{box_index_name}': some local files are owned by "
                f"another user and can't be removed ({e.filename or e}). Fix ownership and "
                f'retry, e.g.  sudo chown -R "$USER" {local_box_path}'
            ) from e
    
        # Create tombstone BEFORE deleting remote (so other machines can see it)
        if _sl_is_remote:
            await create_tombstone(
                config=config,
                storage_location=storage_location,
                box_id=box_id,
                last_known_name=box_meta.name,
            )
    
            # Delete remote box. `_absent_ok` because a box that was never pushed
            # has no remote directory, and that is an ordinary delete, not a
            # failure. Anything else RAISES -- which is what the comment further
            # down already promised and the code did not deliver: this return value
            # used to be discarded, so an unreachable remote left the box's data
            # sitting there forever while the delete reported success and removed
            # the registration that was the only way to find it again.
            await rclone_purge_absent_ok(
                config.rclone_config_path,
                source=storage_location,
                source_path=box_meta.get_remote_path(config),
            )
    
        # Clean up the box's sync records and backups (local + remote) so a delete never
        # leaves orphans behind (these were previously flagged by `boxyard doctor`).
        _local_sync_dir = box_meta.get_local_sync_record_path(config, BoxPart.DATA).parent
        if _local_sync_dir.exists():
            _rmtree_retry(_local_sync_dir)
        _local_backups_dir = config.local_sync_backups_path / box_meta.index_name
        if _local_backups_dir.exists():
            _rmtree_retry(_local_backups_dir)
        if _sl_is_remote:
            _store_path = box_meta.get_storage_location_config(config).store_path
            for _rel in (const.SYNC_RECORDS_REL_PATH, const.REMOTE_BACKUP_REL_PATH):
                # Absent is the NORMAL outcome for the backups path: `sync_helper`
                # keys remote backups by sync ULID (`sync_backups/<ulid>/`), not by
                # index name, so `sync_backups/<index_name>` exists only for boxes
                # written by a boxyard old enough to have used that layout. A real
                # failure still raises, for the same reason as the purge above.
                await rclone_purge_absent_ok(
                    config.rclone_config_path,
                    source=storage_location,
                    source_path=_store_path / _rel / box_meta.index_name,
                )
    
        # Remove from remote index cache
        remove_from_remote_index_cache(config, storage_location, box_id)
    
        # Keep registration + placement until all remote work succeeds. If remote
        # deletion fails after DATA removal, doctor sees an included-but-missing
        # checkout and the command can be retried without losing the box identity.
        _rmtree_retry(box_meta.get_local_path(config))
        from boxyard._checkout import delete_placement
        delete_placement(config, box_id)
    
        # Refresh the boxyard meta file
        refresh_boxyard_meta(config)
    finally:
        _sync_lock.release()
