# AUTOGENERATED! DO NOT EDIT!

from pathlib import Path

from ..config import get_config
from .._models import SyncStatus, BoxPart

async def get_box_sync_status(
    config_path: Path,
    box_index_name: str,
) -> dict[BoxPart, SyncStatus]:
    """ """
    config = get_config(config_path)
    from boxyard._models import get_boxyard_meta
    
    boxyard_meta = get_boxyard_meta(config)
    
    if box_index_name not in boxyard_meta.by_index_name:
        raise ValueError(f"Box '{box_index_name}' not found.")
    
    box_meta = boxyard_meta.by_index_name[box_index_name]
    # `remote=box_meta.storage_location` is passed to rclone as a remote NAME, and
    # a `local` storage location has no section in `boxyard_rclone.conf` -- so this
    # used to fail with `didn't find section in config file`, i.e. `box-status`,
    # `yard-status` and `list --status` all blew up on a local-storage box. There
    # is nothing to report against: the store IS this machine. Same shape as
    # `sync_box`'s branch, so both commands say the same thing.
    from boxyard._models import SyncCondition as _SyncCondition, SyncRecord as _SyncRecord
    from boxyard._models import SyncStatus as _SyncStatus, BoxPart as _BoxPart
    from boxyard.config import StorageType as _StorageType
    
    if box_meta.get_storage_location_config(config).storage_type == _StorageType.LOCAL:
        _local_only_record = _SyncRecord.create(sync_complete=False)
        box_sync_status = {
            box_part: _SyncStatus(
                sync_condition=_SyncCondition.LOCAL_STORAGE,
                local_path_exists=True,
                remote_path_exists=False,
                local_sync_record=_local_only_record,
                remote_sync_record=_local_only_record,
                is_dir=True,
                error_message=None,
            )
            for box_part in _BoxPart
        }
        return box_sync_status
    from boxyard._models import get_sync_status, BoxPart
    import asyncio
    
    # Guard the checkout root BEFORE probing DATA, exactly as `sync_box` does. An
    # unmounted volume makes the DATA directory absent, and an absent directory is
    # indistinguishable from a deleted tree -- so without this, `box-status` on a
    # machine whose removable root is unplugged reports the box as excluded or
    # deleted when nothing of the sort is true. `sync_box` RAISES here; a status
    # command should still report the other parts, so DATA gets an explicit ERROR
    # instead.
    from boxyard._checkout import LocalCheckoutState, get_box_checkout_status
    
    _checkout_state = get_box_checkout_status(config, box_meta).state
    _data_unreadable = _checkout_state in (
        LocalCheckoutState.UNAVAILABLE,
        LocalCheckoutState.RELOCATING,
    )
    _data_error_status = _SyncStatus(
        sync_condition=_SyncCondition.ERROR,
        local_path_exists=False,
        remote_path_exists=False,
        local_sync_record=None,
        remote_sync_record=None,
        is_dir=True,
        error_message=(
            f"The checkout root for this box is {_checkout_state.value} -- an "
            f"unmounted volume, or an interrupted relocation. DATA cannot be "
            f"judged from a tree that is not there; nothing has been probed."
        ),
    )
    
    # The box's EFFECTIVE exclude file, from the same resolver every other site
    # uses -- `box-status` must report the modification state a sync would act on.
    _effective_exclude_path = box_meta.get_effective_exclude_path(config)
    
    _probed_parts = [
        p for p in BoxPart if not (p is BoxPart.DATA and _data_unreadable)
    ]
    tasks = [
        get_sync_status(
            rclone_config_path=config.rclone_config_path,
            local_path=box_meta.get_local_part_path(config, box_part),
            local_sync_record_path=box_meta.get_local_sync_record_path(config, box_part),
            remote=box_meta.storage_location,
            remote_path=box_meta.get_remote_part_path(config, box_part),
            remote_sync_record_path=box_meta.get_remote_sync_record_path(
                config, box_part
            ),
            # Only DATA syncs under an exclude file; META and CONF go through
            # `sync_helper` with none, and their fingerprint baselines are written
            # under `filter_signature(None)`. Passing the DATA exclude for those
            # parts made the signatures mismatch, so `box-status` read them off the
            # mtime fallback while sync read the fingerprint -- and the two could
            # disagree, which is the one thing this command must not do.
            exclude_path=(
                _effective_exclude_path if box_part is BoxPart.DATA else None
            ),
        )
        for box_part in _probed_parts
    ]
    
    box_sync_status = {
        box_part: sync_status
        for box_part, sync_status in zip(_probed_parts, await asyncio.gather(*tasks))
    }
    if _data_unreadable:
        box_sync_status[BoxPart.DATA] = _data_error_status
    return box_sync_status
