# AUTOGENERATED! DO NOT EDIT!

from pathlib import Path
import subprocess
import re
import sys
from datetime import datetime
import asyncio

from .._utils.locking import BoxyardLockManager, LockAcquisitionError, GLOBAL_LOCK_TIMEOUT
from filelock import Timeout
from .._models import generate_unique_box_id, validate_box_name

def _extract_box_name_from_git_url(url: str) -> str:
    """Extract box name from a git URL (SSH or HTTPS)."""
    # Remove trailing .git if present
    url = url.rstrip("/")
    if url.endswith(".git"):
        url = url[:-4]

    # Handle SSH format: git@host:user/box
    ssh_match = re.match(r"^git@[^:]+:(.+)$", url)
    if ssh_match:
        path = ssh_match.group(1)
        return path.split("/")[-1]

    # Handle HTTPS/HTTP format: https://host/user/box
    https_match = re.match(r"^https?://[^/]+/(.+)$", url)
    if https_match:
        path = https_match.group(1)
        return path.split("/")[-1]

    # Fallback: just take the last path component
    return url.split("/")[-1]

def _rollback_new_box(
    box_path: Path,
    box_data_path: Path,
    moved_from_path: Path | None,
) -> None:
    """
    Undo a partially-created box.

    A box is registered by the directories it occupies, so a creation that
    fails part-way (a failed `git clone`, an interrupted copy) would otherwise
    leave a broken registration behind — and every retry would add another.
    """
    import shutil

    if moved_from_path is not None and box_data_path.exists():
        # `from_path` was moved into the box — put it back where it came from.
        # Also `shutil.move`. Safe by construction TODAY -- this only runs
        # after a forward move succeeded, so both ends were on one filesystem
        # -- but the forward move can now cross devices, which makes this
        # reachable across them too.
        shutil.move(str(box_data_path), str(moved_from_path))
    elif box_data_path.exists():
        shutil.rmtree(box_data_path)
    if box_path.exists():
        shutil.rmtree(box_path)

def new_box(
    config_path: Path,
    storage_location: str | None = None,
    box_name: str | None = None,
    from_path: Path | None = None,
    copy_from_path: bool = False,
    creator_hostname: str | None = None,
    creation_timestamp_utc: datetime | None = None,
    initialise_git: bool = True,
    verbose: bool = False,
    git_clone_url: str | None = None,
    sync_first: bool | None = None,
    claim: bool = True,
):
    """
    Create a new boxyard box.

    Args:
        config_path: The path to the boxyard config file.
        storage_location: The storage location to create the new box in.
        box_name: The name of the new box.
        from_path: The path to a local directory to move into boxyard as a new box.
        copy_from_path: Whether to copy the contents of the from_path into the new box.
        creator_hostname: The hostname of the creator of the new box.
        creation_timestamp_utc: The timestamp of the new box. If not provided, the current UTC timestamp will be used.
        initialise_git: Whether to initialise a git box in the new box.
        verbose: Whether to print verbose output.
        git_clone_url: Git URL (SSH or HTTPS) to clone as the new box.
        sync_first: If True, sync all boxmetas before creating to check for ID collisions
                   on remote. If None, uses config.sync_before_new_box setting.
        claim: Whether to make this machine the box's write owner. Pass False
               when creating a box here that will be worked on elsewhere.

    Returns:
        The index name of the new box.
    """
    from boxyard.config import get_config
    
    config = get_config(config_path)
    
    if storage_location is None:
        storage_location = config.default_storage_location
    
    if storage_location not in config.storage_locations:
        raise ValueError(
            f"Invalid storage location: {storage_location}. Must be one of: {', '.join(config.storage_locations)}."
        )
    
    if git_clone_url is not None and from_path is not None:
        raise ValueError("`git_clone_url` and `from_path` are mutually exclusive.")
    
    if box_name is None and from_path is None and git_clone_url is None:
        raise ValueError("Either `box_name`, `from_path`, or `git_clone_url` must be provided.")
    
    if from_path is not None:
        from_path = Path(from_path).expanduser().resolve()
    
    if from_path is not None and box_name is None:
        box_name = from_path.name
    
    if git_clone_url is not None and box_name is None:
        box_name = _extract_box_name_from_git_url(git_clone_url)
    
    # The name is used verbatim as a directory name, so reject anything that is not
    # a single path component before any of the box is created.
    validate_box_name(box_name)
    
    if from_path is None and copy_from_path:
        raise ValueError("`from_path` must be provided if `copy_from_path` is True.")
    
    from boxyard._utils import get_hostname
    
    if creator_hostname is None:
        creator_hostname = get_hostname()
    
    # Resolve sync_first from config if not specified
    if sync_first is None:
        sync_first = config.sync_before_new_box
    # `sync_before_new_box` had never once run. Two independent faults sat on
    # top of each other, and nothing exercised the branch because the setting
    # defaults to False:
    #
    #   * `sync_boxmetas` is not a name `boxyard.cmds` exports -- the function is
    #     `sync_missing_boxmetas`, and has been since the repoyard->boxyard rename
    #     (`32e1b24`). The import raised ImportError.
    #   * `asyncio.get_event_loop()` raises `RuntimeError: There is no current
    #     event loop` on Python 3.14 (which is what boxyard is installed under);
    #     it has been deprecated for this use since 3.12. Every other call site in
    #     the codebase already uses `asyncio.run`. This one was the only holdout.
    if sync_first:
        from boxyard.cmds import sync_missing_boxmetas
        if verbose:
            print("Syncing boxmetas before creating new box...")
        asyncio.run(sync_missing_boxmetas(config_path=config_path, verbose=verbose))
    from boxyard._models import get_boxyard_meta, BoxPart
    
    boxyard_meta = get_boxyard_meta(config)
    
    if from_path is not None:
        from_path = Path(from_path).expanduser().resolve()
        box_paths = [
            box_meta.get_local_part_path(config, BoxPart.DATA)
            for box_meta in boxyard_meta.box_metas
        ]
    
        if from_path in box_paths and not copy_from_path:
            raise ValueError(
                f"'{from_path}' is already a boxyard box. Use `copy_from_path=True` to copy the contents of this box into a new box."
            )
    _lock_manager = BoxyardLockManager(config.boxyard_data_path)
    _lock_path = _lock_manager.global_lock_path
    _lock_manager._ensure_lock_dir(_lock_path)
    _global_lock = __import__('filelock').FileLock(_lock_path, timeout=GLOBAL_LOCK_TIMEOUT)
    try:
        _global_lock.acquire()
    except Timeout:
        raise LockAcquisitionError(
            "global",
            _lock_path,
            GLOBAL_LOCK_TIMEOUT,
            message=(
                f"Could not acquire global lock within {GLOBAL_LOCK_TIMEOUT}s. "
                f"Another boxyard operation may be in progress."
            )
        )
    from boxyard._models import BoxMeta, format_creation_timestamp
    
    # Re-read the yard now that the global lock is held. The snapshot taken above
    # was read BEFORE the lock, so a box created by a concurrent `boxyard new`
    # between the two would be missing from the collision check -- the one thing
    # the lock exists to prevent.
    boxyard_meta = get_boxyard_meta(config)
    
    # Collect all existing box IDs to prevent collisions
    existing_ids = {rm.box_id for rm in boxyard_meta.box_metas}
    
    # A caller-supplied timestamp is resolved BEFORE the id is generated, so the
    # collision check runs against the id that will actually be written. The
    # override used to be applied after the check, which meant
    # `--creation-timestamp-utc` could mint a duplicate box id -- exactly what
    # `doctor`'s `duplicate-box-id` check exists to find.
    fixed_timestamp = (
        None
        if creation_timestamp_utc is None
        else format_creation_timestamp(config, creation_timestamp_utc)
    )
    creation_timestamp, box_subid = generate_unique_box_id(
        config, existing_ids, creation_timestamp=fixed_timestamp
    )
    
    # Claim the box for this machine as it is created.
    #
    # The machine creating a box is the machine that will work on it -- that is
    # what creating one MEANS -- and a box nobody has claimed is a box two machines
    # can still diverge on, which is the problem ownership exists to remove.
    # `include` already nudges about exactly this; creation is a stronger signal
    # than inclusion and was saying nothing at all.
    #
    # The "unowned by default" rule was a MIGRATION guarantee: v0.5.2 promised that
    # "nothing changes for the 583 boxes in the yard until someone claims them". A
    # box created afterwards has no v0.4.x behaviour to preserve, so the guarantee
    # does not reach it.
    #
    # Set locally, with NO network call, which is why this does not turn `boxyard
    # new` into an online command. `claim_box` reads the remote back to verify
    # because two machines can claim the same EXISTING box at once -- measured at 5
    # trials in 6 -- but a box created a moment ago cannot be contested: no other
    # machine knows its id yet. All of claim's machinery is for a race that cannot
    # happen here.
    _write_owner = None
    if claim:
        if config.machine_name:
            _write_owner = config.machine_name
        else:
            # Not fatal: a machine with no `machine_name` is an expected state (the
            # myrig template deliberately emits no key for a machine that is not in
            # its machines list), and refusing to create a box over an ownership
            # setting would be wildly out of proportion. Said out loud rather than
            # skipped silently, and `boxyard doctor` reports both the missing name
            # and the resulting unowned box.
            # STDERR. `boxyard new` prints the index name on stdout and callers
            # parse it -- `cd $(boxyard new ...)` -- so a notice on stdout is read
            # as part of the answer. That is the same defect as issue #18, and the
            # integration suite caught this one the moment it was introduced:
            # `test_new_parent_accepts_every_documented_form` reads the index name
            # off stdout and got this line instead.
            print(
                "Created without a write owner: this machine has no `machine_name` "
                "set, so it cannot claim a box. See `boxyard doctor`.",
                file=sys.stderr,
            )
    
    box_meta = BoxMeta(
        creation_timestamp_utc=creation_timestamp,
        box_subid=box_subid,
        name=box_name,
        storage_location=storage_location,
        creator_hostname=creator_hostname,
        groups=config.default_box_groups,
        write_owner=_write_owner,
    )
    from boxyard._models import BoxPart
    
    box_path = box_meta.get_local_path(config)
    box_data_path = box_meta.get_local_part_path(config, BoxPart.DATA)
    box_conf_path = box_meta.get_local_part_path(config, BoxPart.CONF)
    
    _moved_from_path = None  # Set once `from_path` has been moved into the box.
    try:
        box_meta.save(config)
        box_path.mkdir(parents=True, exist_ok=True)
        box_conf_path.mkdir(parents=True, exist_ok=True)
    
        if git_clone_url is not None:
            if verbose:
                print(f"Cloning {git_clone_url}")
            # git's own diagnosis is the only thing that distinguishes "bad URL"
            # from "no network" from "no permission", so it is captured and
            # re-raised. It used to go to DEVNULL, and `check=True` raised a
            # CalledProcessError carrying nothing but the exit status -- while the
            # `if res.returncode != 0` below it was unreachable.
            res = subprocess.run(
                ["git", "clone", git_clone_url, str(box_data_path)],
                stdout=subprocess.DEVNULL if not verbose else None,
                stderr=subprocess.PIPE,
                text=True,
            )
            if res.returncode != 0:
                detail = (res.stderr or "").strip()
                raise RuntimeError(
                    f"Failed to clone box from {git_clone_url} "
                    f"(git exited {res.returncode})"
                    + (f": {detail}" if detail else "")
                )
        elif from_path is not None:
            if copy_from_path:
                import shutil
    
                shutil.copytree(
                    from_path, box_data_path
                )  # TESTREF: test_new_box_copy_from_path
            else:
                # `shutil.move`, not `Path.rename`: rename is `os.rename` and
                # cannot cross a filesystem boundary, so staging a tree anywhere
                # that is not on the same filesystem as `user_boxes_path` failed
                # outright with `Invalid cross-device link`. That made the same
                # command work or not depending on how the machine happens to
                # mount /tmp -- it worked on mymain and failed on ideapad, whose
                # /tmp is tmpfs. `shutil.move` renames when it can and falls back
                # to copy+unlink when it cannot, so the fast path is unchanged.
                #
                # `--copy` is not a workaround: it leaves the source behind and
                # pays a second full copy, which is the cost `--from`'s move
                # exists to avoid.
                import shutil
    
                shutil.move(str(from_path), str(box_data_path))
                _moved_from_path = from_path
        else:
            box_data_path.mkdir(parents=True, exist_ok=True)
    
        # Skip git init when cloning (already a git box) or when .git exists
        if initialise_git and git_clone_url is None and not (box_data_path / ".git").exists():
            if verbose:
                print("Initialising git box")
            # A warning, not a failure: the box is fully created and registered by
            # this point, and `git init` is a convenience laid on top of it. The
            # code always said so -- but `check=True` raised before the warning
            # could ever be reached, so a machine without git got a
            # CalledProcessError and a rolled-back box instead. The warning goes to
            # stderr unconditionally; the CLI passes verbose=False, so gating it
            # would have made a failed `git init` completely silent.
            res = subprocess.run(
                ["git", "init"],
                cwd=box_data_path,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.PIPE,
                text=True,
            )
            if res.returncode != 0:
                detail = (res.stderr or "").strip()
                print(
                    f"Warning: `git init` failed in '{box_data_path}' "
                    f"(git exited {res.returncode}); the box was created without it"
                    + (f": {detail}" if detail else ""),
                    file=sys.stderr,
                )
    except BaseException:
        try:
            _rollback_new_box(box_path, box_data_path, _moved_from_path)
        except Exception as cleanup_error:
            print(
                f"Warning: failed to clean up the partially-created box "
                f"'{box_meta.index_name}': {cleanup_error}",
                file=sys.stderr,
            )
        if _global_lock.is_locked:
            _global_lock.release()
        raise
    from boxyard._models import refresh_boxyard_meta
    
    try:
        refresh_boxyard_meta(config, _skip_lock=True)
    finally:
        # The lock is released in a `finally`, not in a later statement. It used to
        # sit outside any try, so a refresh that raised left the global lock held --
        # harmless for a CLI process that is about to exit, but `new_box` is an
        # importable function and the next boxyard operation in the same process
        # would then block until the timeout.
        if _global_lock.is_locked:
            _global_lock.release()
    return box_meta.index_name
