# AUTOGENERATED! DO NOT EDIT!

from pathlib import Path

from .. import const
from .._models import BoxMeta, BoxPart, get_boxyard_meta, refresh_boxyard_meta
from .._ownership import OwnershipRefused
from .._remote_index import find_remote_box_by_id
from .._utils import rclone_cat
from .._utils.sync_helper import SyncSetting
from ..config import get_config

async def _remote_owner_is_cleared(config, box_meta, box_index_name: str) -> bool:
    """Does the REMOTE boxmeta now show this box as unowned?"""
    import tomllib

    remote_index_name = await find_remote_box_by_id(
        config, box_meta.storage_location, box_meta.box_id
    )
    if remote_index_name is None:
        remote_index_name = box_index_name
    remote_path = (
        config.storage_locations[box_meta.storage_location].store_path
        / const.REMOTE_BOXES_REL_PATH
        / remote_index_name
        / const.BOX_METAFILE_REL_PATH
    )
    exists, raw = await rclone_cat(
        rclone_config_path=config.rclone_config_path,
        source=box_meta.storage_location,
        source_path=remote_path.as_posix(),
    )
    if not exists:
        return False
    return tomllib.loads(raw).get("write_owner") is None

async def release_box(
    config_path: Path,
    box_index_name: str,
    verbose: bool = True,
    _skip_sync: bool = False,
) -> None:
    """
    Give up this machine's write ownership of a box.

    Args:
        config_path: Path to the boxyard config file.
        box_index_name: Index name of the box to release.
        verbose: Print what happened.
        _skip_sync: Write the boxmeta but do not push it. Only for callers that
            are already inside a sync of this box; a release that is not pushed
            is invisible to every other machine.

    Raises:
        OwnershipRefused: if the box is owned by a different machine.
    """
    config = get_config(config_path)
    
    boxyard_meta = get_boxyard_meta(config)
    if box_index_name not in boxyard_meta.by_index_name:
        raise ValueError(f"Box '{box_index_name}' not found.")
    
    # Re-read from disk: the cache predates any META pull that carried another
    # machine's claim.
    box_meta = BoxMeta.load(
        config, boxyard_meta.by_index_name[box_index_name].storage_location, box_index_name
    )
    from boxyard.cmds import sync_box
    
    await sync_box(
        config_path=config_path,
        box_index_name=box_index_name,
        sync_choices=[BoxPart.META],
        sync_setting=SyncSetting.CAREFUL,
        verbose=False,
    )
    box_meta = BoxMeta.load(config, box_meta.storage_location, box_index_name)
    
    if box_meta.write_owner is None:
        if verbose:
            print(f"'{box_index_name}' is already unowned; nothing to release.")
        return None
    
    if box_meta.write_owner != config.machine_name:
        raise OwnershipRefused(
            f"Cannot release '{box_index_name}': it is owned by "
            f"'{box_meta.write_owner}', not by this machine "
            f"({config.machine_name or 'unnamed'}).\n"
            f"Run `boxyard release -r '{box_index_name}'` on "
            f"'{box_meta.write_owner}', or take the box over here with "
            f"`boxyard claim --steal -r '{box_index_name}'`."
        )
    _previous_owner = box_meta.write_owner
    box_meta.write_owner = None
    box_meta.save(config)
    
    if not _skip_sync:
        try:
            await sync_box(
                config_path=config_path,
                box_index_name=box_index_name,
                sync_choices=[BoxPart.META],
                sync_setting=SyncSetting.CAREFUL,
                verbose=False,
            )
            _landed = await _remote_owner_is_cleared(config, box_meta, box_index_name)
        except Exception:
            box_meta.write_owner = _previous_owner
            box_meta.save(config)
            raise
    
        if not _landed:
            box_meta.write_owner = _previous_owner
            box_meta.save(config)
            raise OwnershipRefused(
                f"Could not publish the release of '{box_index_name}': the remote "
                f"boxmeta does not show it as unowned, so other machines would "
                f"still treat '{_previous_owner}' as the write owner. This machine "
                f"still owns it; try again once the remote is reachable."
            )
    
    refresh_boxyard_meta(config)
    
    if verbose:
        print(
            f"Released '{box_index_name}'. It is unowned again, so any machine may "
            f"push it — claim it elsewhere with `boxyard claim -r '{box_index_name}'`."
        )
