# AUTOGENERATED! DO NOT EDIT!

from pathlib import Path
import asyncio

from .._utils.sync_helper import sync_helper, SyncSetting, SyncDirection, SyncUnsafe
from .._models import (
    SyncStatus,
    BoxPart,
    BoxMeta,
    SyncCondition,
    MetaMergeConflict,
    get_sync_status,
    merge_box_metas,
    read_meta_base,
    record_meta_base,
)
from .._enums import StorageFormat
from .._ownership import may_push, push_would_transfer, write_denied_message
from ..config import get_config, StorageType
from .._utils import (
    check_interrupted,
    enable_soft_interruption,
    literal_exclude_names,
    SoftInterruption,
)
from .._utils.locking import BoxyardLockManager, LockAcquisitionError, BOX_SYNC_LOCK_TIMEOUT, acquire_lock_async
from .. import const
from .._tombstones import is_tombstoned, get_tombstone
from .._remote_index import find_remote_box_by_id, update_remote_index_cache

async def _try_merge_diverged_boxmeta(
    *,
    config,
    box_meta: BoxMeta,
    remote_index_name: str,
    local_path: Path,
    local_sync_record_path: Path,
    remote_path: Path,
    remote_sync_record_path: Path,
    local_sync_backups_path: Path,
    remote_sync_backups_path: Path,
    verbose: bool = False,
) -> bool:
    """
    Reconcile a boxmeta that BOTH sides have edited, before the sync sees it.

    Returns True when the merge was written and pushed, False when it declined
    -- and DECLINING IS THE DEFAULT SHAPE of this function. It bails out, in
    order, when: the setting is off; the status is not a conflict; there is no
    merge base; the remote copy cannot be read; the two sides changed the same
    scalar differently. Every one of those leaves the divergence exactly as it
    was, so the refusal that follows is unchanged for anything this cannot
    settle. Nothing here is a fallback that papers over a failure.

    On success it FORCE-PUSHES the merged boxmeta. That is a write today's code
    would refuse to make, and it is justified by what a merge is: the result
    CONTAINS the remote's content as well as this machine's, so the push adds
    and never discards. It is also why `merge_diverged_boxmetas` is off by
    default.
    """
    if not getattr(config, "merge_diverged_boxmetas", False):
        return False

    # Called only AFTER `sync_helper` has already refused, so the status is
    # known to be unsafe and does not need asking for again. `sync_helper`
    # raises for several reasons; the one this can settle is a two-sided
    # divergence, and the base is what distinguishes it -- a box whose local
    # and remote agree has nothing to merge, and the merge below is a no-op
    # that produces the local content unchanged.
    _base = read_meta_base(config, box_meta)
    if _base is None:
        # A box that has not synced its META since the base was introduced.
        # There is nothing to compute a delta against, and guessing one is the
        # thing this whole design exists to avoid.
        if verbose:
            print(
                "Boxmeta has diverged and there is no merge base to reconcile it "
                "against; leaving it for `boxyard doctor`."
            )
        return False

    from .._utils import rclone_cat

    _exists, _raw = await rclone_cat(
        rclone_config_path=config.rclone_config_path,
        source=box_meta.storage_location,
        source_path=remote_path.as_posix(),
    )
    if not _exists:
        return False

    import tempfile

    with tempfile.NamedTemporaryFile("w", suffix=".toml", delete=False) as _tmp:
        _tmp.write(_raw)
        _remote_copy = Path(_tmp.name)
    try:
        _remote_meta = BoxMeta.load_from_path(
            _remote_copy,
            creation_timestamp_utc=box_meta.creation_timestamp_utc,
            box_subid=box_meta.box_subid,
            name=box_meta.name,
            storage_location=box_meta.storage_location,
        )
    except Exception as e:
        if verbose:
            print(f"Could not read the remote boxmeta to merge it: {e}")
        return False
    finally:
        _remote_copy.unlink(missing_ok=True)

    # Re-read the LOCAL boxmeta from disk rather than trusting the registry
    # snapshot, for the same reason `modify_boxmeta` does: the cache is a
    # snapshot of the last refresh, and anything that reached boxmeta.toml
    # since would be silently dropped.
    _local_meta = BoxMeta.load(config, box_meta.storage_location, box_meta.index_name)

    try:
        _merged = merge_box_metas(_base, _local_meta, _remote_meta)
    except MetaMergeConflict as e:
        # The one case a human still has to settle. Say which field, and leave
        # everything alone.
        print(
            f"Boxmeta of '{box_meta.index_name}' has diverged and cannot be "
            f"merged automatically: both sides changed {', '.join(e.fields)}. "
            f"`boxyard doctor` names the ways out."
        )
        return False

    _merged.save(config)
    if verbose:
        print("Merged the diverged boxmeta; pushing the result.")

    # Force, because the records still disagree: this content supersedes both
    # and the normal push would refuse it. Safe for the same reason the merge
    # is -- the result CONTAINS what the remote had, so the push adds and never
    # discards.
    await sync_helper(
        rclone_config_path=config.rclone_config_path,
        sync_direction=SyncDirection.PUSH,
        sync_setting=SyncSetting.FORCE,
        local_path=local_path,
        local_sync_record_path=local_sync_record_path,
        remote=box_meta.storage_location,
        remote_path=remote_path,
        remote_sync_record_path=remote_sync_record_path,
        local_sync_backups_path=local_sync_backups_path,
        remote_sync_backups_path=remote_sync_backups_path,
        verbose=verbose,
    )
    record_meta_base(config, box_meta)
    return True

async def sync_box(
    config_path: Path,
    box_index_name: str,
    sync_direction: SyncDirection | None = None,
    sync_setting: SyncSetting = SyncSetting.CAREFUL,
    sync_choices: list[BoxPart] | None = None,
    verbose: bool = False,
    show_rclone_progress: bool = False,
    soft_interruption_enabled: bool = True,
    tombstoned_box_ids: set[str] | None = None,
    _skip_lock: bool = False,
    _allow_missing_checkout: bool = False,
) -> dict[BoxPart, tuple[SyncStatus, bool]]:
    """
    Syncs a box with its remote.

    Args:
        config_path: Path to the boxyard config file.
        box_index_name: Full name of the box to sync.
        sync_direction: Direction of sync.
        sync_setting: SyncSetting option (SAFE, CAREFUL, FORCE).
        sync_choices: List of BoxPart specifying what to sync. If None, all parts are synced.
        tombstoned_box_ids: Every tombstoned box id at this box's storage location,
            when the caller already holds the set (see `list_tombstoned_box_ids`).
            Avoids one remote probe per box. If None, the box is probed individually.
        force: Force syncing, possibly overwriting changes.
        verbose: Print verbose output during sync.
        show_rclone_progress: Show rclone progress during sync.
    """
    config = get_config(config_path)
    if sync_choices is None:
        sync_choices = [box_part for box_part in BoxPart]
    
    if soft_interruption_enabled:
        enable_soft_interruption()
    from boxyard._models import get_boxyard_meta
    
    boxyard_meta = get_boxyard_meta(config)
    
    if box_index_name not in boxyard_meta.by_index_name:
        raise ValueError(f"Box '{box_index_name}' not found.")
    
    box_meta = boxyard_meta.by_index_name[box_index_name]
    
    if BoxPart.DATA in sync_choices:
        from boxyard._checkout import (
            get_box_checkout_status,
            LocalCheckoutState,
            CheckoutRootUnavailable,
        )
        _checkout_status = get_box_checkout_status(config, box_meta)
        if _checkout_status.state == LocalCheckoutState.UNAVAILABLE:
            raise CheckoutRootUnavailable(
                f"Cannot sync DATA for '{box_index_name}': checkout root "
                f"'{_checkout_status.checkout_root}' is unavailable. No fallback root will be used."
            )
        if _checkout_status.state == LocalCheckoutState.RELOCATING:
            raise RuntimeError(
                f"Cannot sync DATA for '{box_index_name}': checkout state is relocating. "
                "Run `boxyard relocate` to recover relocation."
            )
        if (
            _checkout_status.state == LocalCheckoutState.MISSING
            and not _allow_missing_checkout
        ):
            raise RuntimeError(
                f"Cannot sync DATA for '{box_index_name}': its recorded checkout is missing. "
                "Run `boxyard doctor --no-remote` and use `boxyard include` to recover it."
            )
    # A `local` storage location has no remote: its store is a directory on this
    # machine, so there is nothing to sync against. That is a legitimate,
    # permanent state -- not an error, and not something a retry resolves.
    #
    # It used to `return` with no value, while the signature promises a dict and
    # every caller reads one. `multi-sync` calls `.values()` on the result, so a
    # single local-storage box became an `AttributeError` rendered as a red
    # `Error` line, every 1200s, on every machine. The shape below mirrors the
    # TOMBSTONED path, which had the same "a fact about the whole box" problem.
    if box_meta.get_storage_location_config(config).storage_type == StorageType.LOCAL:
        if verbose:
            print(
                f"Box '{box_index_name}' is in the local storage location "
                f"'{box_meta.storage_location}'. Nothing to sync."
            )
        from boxyard._models import SyncRecord as _SyncRecord
    
        _local_only_record = _SyncRecord.create(sync_complete=False)
        sync_results = {
            part: (
                SyncStatus(
                    sync_condition=SyncCondition.LOCAL_STORAGE,
                    local_path_exists=True,
                    remote_path_exists=False,
                    local_sync_record=_local_only_record,
                    remote_sync_record=_local_only_record,
                    is_dir=True,
                    error_message=None,
                ),
                False,
            )
            for part in sync_choices
        }
        return sync_results
    box_id = BoxMeta.extract_box_id(box_index_name)
    storage_location = box_meta.storage_location
    
    # One remote probe PER BOX is what this parameter exists to avoid: a
    # `multi-sync` pass over 587 boxes made 587 separate SFTP connections to the
    # same storage box, every 20 minutes, on every machine. That saturated the
    # server's connection limit and was measurably failing ~8 boxes per pass on
    # three machines with "couldn't initialise SFTP".
    #
    # The caller passes the set when it already holds one for this storage
    # location. When it does not -- `sync_box` is also a standalone command --
    # fall back to the single probe rather than skipping the check: a silent
    # skip would turn a safety check into a no-op and let a box deleted from
    # another machine be resurrected here.
    if tombstoned_box_ids is not None:
        _is_tombstoned = box_id in tombstoned_box_ids
    else:
        _is_tombstoned = await is_tombstoned(config, storage_location, box_id)
    if _is_tombstoned:
        _tombstone = await get_tombstone(config, storage_location, box_id)
        _tombstone_msg = f"Box '{box_index_name}' was deleted"
        if _tombstone:
            _tombstone_msg += f" by {_tombstone.deleted_by_hostname} at {_tombstone.deleted_at_utc}"
        print(f"Warning: {_tombstone_msg}. Skipping sync.")
        from boxyard._models import SyncRecord
        _dummy_sync_record = SyncRecord.create(sync_complete=False)
        sync_results = {
            part: (SyncStatus(
                sync_condition=SyncCondition.TOMBSTONED,
                local_path_exists=False,
                remote_path_exists=False,
                local_sync_record=_dummy_sync_record,
                remote_sync_record=_dummy_sync_record,
                is_dir=True,
                error_message=_tombstone_msg,
            ), False)
            for part in sync_choices
        }
        return sync_results
    remote_index_name = await find_remote_box_by_id(config, storage_location, box_id)
    
    # If remote doesn't exist, this is a new box - use local index_name for remote
    # If remote exists with different name, use that name for remote paths
    if remote_index_name is None:
        remote_index_name = box_index_name
    
    # Precompute remote paths using the remote_index_name (which may differ from local)
    def _get_remote_path_for_index(idx_name: str) -> Path:
        return (
            config.storage_locations[storage_location].store_path
            / const.REMOTE_BOXES_REL_PATH
            / idx_name
        )
    
    def _get_remote_part_path_for_index(idx_name: str, part: BoxPart) -> Path:
        base = _get_remote_path_for_index(idx_name)
        if part == BoxPart.DATA:
            return base / const.BOX_DATA_REL_PATH
        elif part == BoxPart.META:
            return base / const.BOX_METAFILE_REL_PATH
        elif part == BoxPart.CONF:
            return base / const.BOX_CONF_REL_PATH
        raise ValueError(f"Invalid box part: {part}")
    
    def _get_remote_sync_record_path_for_index(idx_name: str, part: BoxPart) -> Path:
        sl_conf = config.storage_locations[storage_location]
        return (
            sl_conf.store_path
            / const.SYNC_RECORDS_REL_PATH
            / idx_name
            / f"{part.value}.rec"
        )
    _sync_lock = None
    if not _skip_lock:
        _lock_manager = BoxyardLockManager(config.boxyard_data_path)
        _lock_path = _lock_manager.box_sync_lock_path(box_index_name)
        _lock_manager._ensure_lock_dir(_lock_path)
        _sync_lock = __import__('filelock').FileLock(_lock_path, timeout=0)
        await acquire_lock_async(
            _sync_lock,
            f"box sync ({box_index_name})",
            _lock_path,
            BOX_SYNC_LOCK_TIMEOUT,
        )
    
    try:
        # Prints
        if verbose:
            print(f"Syncing box {box_index_name} at {box_meta.storage_location}.")
    
        # Get the backup locations
        sl_config = box_meta.get_storage_location_config(config)
        local_sync_backups_path = config.local_sync_backups_path
        remote_sync_backups_path = sl_config.store_path / const.REMOTE_BACKUP_REL_PATH
    
        # Sync the boxmeta
        sync_results = {}
    
        if check_interrupted():
            raise SoftInterruption()
    
        # META is synced whenever DATA is, even when the caller did not ask for it:
        # the ownership decision below reads `write_owner` out of the boxmeta, and
        # `boxyard sync -c data` would otherwise decide it from a local copy that
        # predates another machine's claim. That is the one path by which a
        # non-owner could push without ever learning it had been claimed.
        #
        # Its result is only RECORDED when META was actually requested, so the
        # returned dict still answers exactly what the caller asked about.
        sync_part = BoxPart.META
        if sync_part in sync_choices or BoxPart.DATA in sync_choices:
            if verbose:
                print(f"Syncing {sync_part.value}.")
    
            _meta_paths = dict(
                local_path=box_meta.get_local_part_path(config, BoxPart.META),
                local_sync_record_path=box_meta.get_local_sync_record_path(config, sync_part),
                remote_path=_get_remote_part_path_for_index(remote_index_name, BoxPart.META),
                remote_sync_record_path=_get_remote_sync_record_path_for_index(
                    remote_index_name, sync_part
                ),
            )
            try:
                _meta_sync_result = await sync_helper(
                    rclone_config_path=config.rclone_config_path,
                    sync_direction=sync_direction,
                    sync_setting=sync_setting,
                    remote=box_meta.storage_location,
                    local_sync_backups_path=local_sync_backups_path,
                    remote_sync_backups_path=remote_sync_backups_path,
                    verbose=verbose,
                    show_rclone_progress=show_rclone_progress,
                    **_meta_paths,
                )
            except SyncUnsafe:
                # Reconcile only from the FAILURE path. Asking beforehand whether a
                # merge is needed costs two remote calls per box per pass -- 1,180
                # of them on this fleet's largest yard, every 20 minutes -- and
                # per-box remote calls are exactly what saturated the storage box's
                # connection limit once already (see the tombstone fetch in
                # `multi_sync`). Here the cost is paid only by a box that has
                # actually diverged.
                #
                # Declines -- no base, no remote copy, a scalar both sides changed
                # differently -- re-raise, so the refusal is unchanged for every
                # case this cannot settle.
                if not await _try_merge_diverged_boxmeta(
                    config=config,
                    box_meta=box_meta,
                    remote_index_name=remote_index_name,
                    local_sync_backups_path=local_sync_backups_path,
                    remote_sync_backups_path=remote_sync_backups_path,
                    verbose=verbose,
                    **_meta_paths,
                ):
                    raise
                _meta_sync_result = await sync_helper(
                    rclone_config_path=config.rclone_config_path,
                    sync_direction=sync_direction,
                    sync_setting=sync_setting,
                    remote=box_meta.storage_location,
                    local_sync_backups_path=local_sync_backups_path,
                    remote_sync_backups_path=remote_sync_backups_path,
                    verbose=verbose,
                    show_rclone_progress=show_rclone_progress,
                    **_meta_paths,
                )
            if sync_part in sync_choices:
                sync_results[BoxPart.META] = _meta_sync_result
    
            # Record the merge base, but ONLY where local and remote are known to
            # match: the status said SYNCED (nothing to do), or a transfer
            # completed and was verified. A base that never corresponded to a
            # shared state would make a later merge confidently wrong, which is
            # worse than the refusal a missing base falls back to.
            #
            # Being precise about what this condition is worth TODAY: every
            # non-agreeing META outcome currently RAISES out of `sync_helper`
            # (conflict, incomplete push, unsafe direction), so control does not
            # reach here at all, and the one refusal that returns normally --
            # EXCLUDED -- has no local boxmeta, which `record_meta_base` handles by
            # dropping the base. So this is defence in depth rather than the only
            # thing holding the line, and a mutation test will not catch its
            # removal.
            #
            # It stays because that is a property of today's error handling, not a
            # guarantee. `SyncCondition.WRITE_DENIED` is the precedent: a refusal
            # that was deliberately turned into a RETURNED STATUS rather than an
            # exception, to stop the supervisor logging the same error 72 times a
            # day. If META ever gains such a status, this condition is what keeps
            # the base from moving under it.
            _meta_status, _meta_synced = _meta_sync_result
            if _meta_status.sync_condition == SyncCondition.SYNCED or _meta_synced:
                record_meta_base(config, box_meta, verbose=verbose)
    
        # ---- Write ownership -------------------------------------------------
        #
        # Decided HERE: after the META sync, so it reads whatever the rest of the
        # fleet last said about this box, and before CONF/DATA, which are the parts
        # ownership governs. Not in `sync_helper` -- that takes paths and knows
        # nothing about boxes, and pushing box semantics into it would be the wrong
        # layer.
        #
        # `box_meta` above came from `get_boxyard_meta`, a cache read BEFORE the
        # META sync, and is stale the moment that sync pulls: re-read from disk.
        _box_meta_on_disk = BoxMeta.load(config, storage_location, box_index_name)
        _write_owner = _box_meta_on_disk.write_owner
        _may_push = may_push(config, _box_meta_on_disk)
    
        def _deny(status: SyncStatus) -> tuple[SyncStatus, bool]:
            return (
                status._replace(
                    sync_condition=SyncCondition.WRITE_DENIED,
                    error_message=write_denied_message(config, _box_meta_on_disk),
                ),
                False,
            )
    
        async def _sync_part(
            *,
            probe_include_path=None,
            probe_exclude_path=None,
            probe_filters_path=None,
            **helper_kwargs,
        ) -> tuple[SyncStatus, bool]:
            """
            `sync_helper`, except that a non-owner never pushes.
    
            A non-owner is a read-only replica doing its job, so it pulls quietly
            and says nothing; it only speaks up when it holds changes that will
            never leave this machine. Nothing here raises -- see
            `SyncCondition.WRITE_DENIED`.
            """
            if _may_push:
                return await sync_helper(**helper_kwargs)
    
            # Only a non-owner pays for this extra status read; an unowned box or
            # one we own takes the path above untouched.
            _status = await get_sync_status(
                rclone_config_path=config.rclone_config_path,
                local_path=helper_kwargs["local_path"],
                local_sync_record_path=helper_kwargs["local_sync_record_path"],
                remote=helper_kwargs["remote"],
                remote_path=helper_kwargs["remote_path"],
                remote_sync_record_path=helper_kwargs["remote_sync_record_path"],
                exclude_path=probe_exclude_path,
                # Must match what the sync below will use, or a non-owner reads a
                # different condition than the one it then acts on. CONF passes
                # False here for the same reason it does at the call site.
                local_absence_means_excluded=helper_kwargs.get(
                    "local_absence_means_excluded", True
                ),
            )
            _condition = _status.sync_condition
    
            if _condition == SyncCondition.SYNCED:
                return _status, False
    
            if _condition == SyncCondition.NEEDS_PULL:
                # The ordinary state of a read-only replica. Pull, silently.
                return await sync_helper(
                    **{**helper_kwargs, "sync_direction": SyncDirection.PULL}
                )
    
            if _condition == SyncCondition.NEEDS_PUSH:
                # `needs_push` is not evidence of a real change: it comes from a
                # tree walk, so a single `.DS_Store` sets it even though the file
                # can never be transferred. Ask what a push would ACTUALLY move.
                _would_transfer = await push_would_transfer(
                    config,
                    local_path=Path(helper_kwargs["local_path"]),
                    remote=helper_kwargs["remote"],
                    remote_path=Path(helper_kwargs["remote_path"]),
                    include_path=probe_include_path,
                    exclude_path=probe_exclude_path,
                    filters_path=probe_filters_path,
                )
                if not _would_transfer:
                    # Nothing to send. Report it as what it is rather than as a
                    # refusal, or every machine would carry a permanent complaint
                    # about changes that do not exist.
                    return _status._replace(sync_condition=SyncCondition.SYNCED), False
                return _deny(_status)
    
            if _condition == SyncCondition.CONFLICT:
                return _deny(_status)
    
            # ERROR, EXCLUDED, TOMBSTONED, and the interrupted-sync conditions are
            # not ownership's business: they are handled exactly as before.
            return await sync_helper(**helper_kwargs)
    
        # Sync the boxconf
        if check_interrupted():
            raise SoftInterruption()
    
        # CONF is synced whenever DATA is, even when the caller did not ask for it,
        # for the same reason META is: `conf/.rclone_include|_exclude|_filters`
        # decide WHAT DATA syncs, and they are read off the local disk immediately
        # below. `boxyard sync -c data` on a machine that has never pulled this
        # box's conf/ would otherwise sync DATA with the GLOBAL filters -- so a box
        # whose `.rclone_include` narrows what it syncs would sync EVERYTHING.
        # That is precisely the harm v0.5.3 fixed, still reachable through `-c
        # data` (which `multi-sync` also accepts, i.e. across the whole yard).
        #
        # Its result is only RECORDED when CONF was actually requested, so the
        # returned dict still answers exactly what the caller asked about.
        sync_part = BoxPart.CONF
        if sync_part in sync_choices or BoxPart.DATA in sync_choices:
            if verbose:
                print("Syncing", sync_part.value)
            # CONF follows DATA: `conf/.rclone_include|_exclude|_filters` decide
            # what DATA syncs, so letting a non-owner push CONF would let it change
            # the owner's filters. Non-owners pull it only.
            #
            # META, by contrast, stays writable by every machine -- without that,
            # ownership could never be transferred and `groups`/`parents` could not
            # be edited from a non-owner.
            _conf_sync_result = await _sync_part(
                rclone_config_path=config.rclone_config_path,
                sync_direction=sync_direction,
                sync_setting=sync_setting,
                local_path=box_meta.get_local_part_path(config, BoxPart.CONF),
                local_sync_record_path=box_meta.get_local_sync_record_path(config, sync_part),
                remote=box_meta.storage_location,
                remote_path=_get_remote_part_path_for_index(remote_index_name, BoxPart.CONF),
                remote_sync_record_path=_get_remote_sync_record_path_for_index(
                    remote_index_name, sync_part
                ),
                local_sync_backups_path=local_sync_backups_path,
                remote_sync_backups_path=remote_sync_backups_path,
                verbose=verbose,
                show_rclone_progress=show_rclone_progress,
                allow_missing_source=True,  # CONF is optional - may not exist on either side
                # A missing local conf/ means "never fetched", NOT "deliberately
                # excluded" -- exclusion is a DATA concept. Reading it as EXCLUDED
                # made the absence self-perpetuating, so a box's own rclone filters
                # only ever existed on the machine that wrote them, and a box whose
                # `conf/.rclone_include` narrows its sync would sync EVERYTHING on
                # the second machine.
                local_absence_means_excluded=False,
            )
            if sync_part in sync_choices:
                sync_results[sync_part] = _conf_sync_result
    
        # Get the now locally synced conf files for the sync of the box data
        _rclone_include_path = (
            box_meta.get_local_part_path(config, BoxPart.CONF) / const.RCLONE_INCLUDE_FILENAME
        )
        _rclone_exclude_path = (
            box_meta.get_local_part_path(config, BoxPart.CONF) / const.RCLONE_EXCLUDE_FILENAME
        )
        _rclone_filters_path = (
            box_meta.get_local_part_path(config, BoxPart.CONF) / const.RCLONE_FILTERS_FILENAME
        )
    
        _rclone_include_path = _rclone_include_path if _rclone_include_path.exists() else None
        _rclone_exclude_path = (
            _rclone_exclude_path
            if _rclone_exclude_path.exists()
            else config.default_rclone_exclude_path
        )
        _rclone_filters_path = _rclone_filters_path if _rclone_filters_path.exists() else None
    
        # Sync the box data
        if check_interrupted():
            raise SoftInterruption()
    
        sync_part = BoxPart.DATA
        if sync_part in sync_choices:
            if verbose:
                print("Syncing", sync_part.value)
    
        # ---- The storage-format branch ---------------------------------------
        #
        # ONE branch, and the plain arm is the untouched call it always was -- not
        # "mostly the same", literally the same expression. The overwhelming
        # majority of boxes are plain and will be for a long time, so a regression
        # here is a far bigger incident than anything restic-related.
        #
        # Decided from the boxmeta ON DISK, after the META sync, so a box converted
        # on another machine is recognised on the pass that learns about it rather
        # than the one after.
        if sync_part in sync_choices and _box_meta_on_disk.storage_format is StorageFormat.RESTIC:
            from boxyard._restic_sync import sync_data_restic
    
            from boxyard._restic import restic_excludes_from_rclone_file
    
            sync_results[sync_part] = await sync_data_restic(
                config,
                _box_meta_on_disk,
                remote_index_name,
                may_push=_may_push,
                sync_direction=sync_direction,
                sync_setting=sync_setting,
                # The SAME exclude list the plain path would apply, translated. A
                # converted box must not silently start storing `.venv/` and
                # `node_modules/`.
                excludes=restic_excludes_from_rclone_file(_rclone_exclude_path),
                # The SAME literal names the plain backend's own mtime walk uses,
                # from the box's effective exclude file -- so the two backends gate
                # on the same set rather than two subtly different ones.
                exclude_names=literal_exclude_names(_rclone_exclude_path),
                # Tells ADOPTION apart from EXCLUSION, which look identical from
                # the filesystem: both are "no local tree, a snapshot on the
                # remote". MISSING means a placement record says this box IS
                # included here, so the tree has to be materialised.
                checkout_missing=(
                    _checkout_status.state == LocalCheckoutState.MISSING
                ),
                verbose=verbose,
            )
        elif sync_part in sync_choices:
            sync_results[sync_part] = await _sync_part(
                probe_include_path=_rclone_include_path,
                probe_exclude_path=_rclone_exclude_path,
                probe_filters_path=_rclone_filters_path,
                rclone_config_path=config.rclone_config_path,
                sync_direction=sync_direction,
                sync_setting=sync_setting,
                local_path=box_meta.get_local_part_path(config, BoxPart.DATA),
                local_sync_record_path=box_meta.get_local_sync_record_path(config, sync_part),
                remote=box_meta.storage_location,
                remote_path=_get_remote_part_path_for_index(remote_index_name, BoxPart.DATA),
                remote_sync_record_path=_get_remote_sync_record_path_for_index(
                    remote_index_name, sync_part
                ),
                local_sync_backups_path=local_sync_backups_path,
                remote_sync_backups_path=remote_sync_backups_path,
                include_path=_rclone_include_path,
                exclude_path=_rclone_exclude_path,
                filters_path=_rclone_filters_path,
                verbose=verbose,
                show_rclone_progress=show_rclone_progress,
                preserve_exec_perms=True,
            )
    
        # Update remote index cache
        update_remote_index_cache(config, storage_location, box_id, remote_index_name)
    
        # Refresh the boxyard meta file
        if BoxPart.META in sync_choices:
            from boxyard._models import refresh_boxyard_meta
    
            refresh_boxyard_meta(config)
    finally:
        if _sync_lock is not None:
            _sync_lock.release()
    return sync_results
