# AUTOGENERATED! DO NOT EDIT!

import pytest
import asyncio

from boxyard.cmds import new_box, sync_box, sync_missing_boxmetas
from boxyard.cmds._rename_box import rename_box
from boxyard._enums import RenameScope
from boxyard._models import get_boxyard_meta, BoxMeta

from ...integration.conftest import create_boxyards

@pytest.mark.integration
def test_rename_propagates_without_duplicating():
    """A rename on one machine is adopted by another, not duplicated."""
    asyncio.run(_test_rename_propagates_without_duplicating())

async def _test_rename_propagates_without_duplicating():
    (
        sl_name,
        sl_rclone_path,
        [(config1, config_path1, data_path1), (config2, config_path2, data_path2)],
    ) = create_boxyards(num_boxyards=2)
    original_index_name = new_box(
        config_path=config_path1, box_name="before-rename", storage_location=sl_name
    )
    box_id = BoxMeta.extract_box_id(original_index_name)
    await sync_box(config_path=config_path1, box_index_name=original_index_name)
    await sync_missing_boxmetas(config_path=config_path2)
    
    meta2 = get_boxyard_meta(config2, force_create=True)
    registrations = [bm for bm in meta2.box_metas if bm.box_id == box_id]
    assert len(registrations) == 1, f"expected one registration, got {[b.index_name for b in registrations]}"
    assert registrations[0].name == "before-rename"
    new_index_name = await rename_box(
        config_path=config_path1,
        box_index_name=original_index_name,
        new_name="after-rename",
        scope=RenameScope.BOTH,
    )
    assert new_index_name == f"{box_id}__after-rename"
    await sync_missing_boxmetas(config_path=config_path2)
    
    meta2 = get_boxyard_meta(config2, force_create=True)
    registrations = [bm for bm in meta2.box_metas if bm.box_id == box_id]
    
    assert len(registrations) == 1, (
        "the rename produced a DUPLICATE registration instead of being adopted: "
        f"{[b.index_name for b in registrations]}"
    )
    assert registrations[0].name == "after-rename", (
        f"machine 2 kept the stale name {registrations[0].name!r}"
    )
    old_local_store_path = config2.local_store_path / sl_name / original_index_name
    assert not old_local_store_path.exists(), f"{old_local_store_path} survived the rename"
    
    new_local_store_path = config2.local_store_path / sl_name / new_index_name
    assert new_local_store_path.exists(), f"{new_local_store_path} was not created"
    from boxyard.cmds._doctor import run_doctor
    
    report = await run_doctor(config_path=config_path2, check_remote=False)
    _dupes = report["checks"]["duplicate-box-id"]["findings"]
    assert not _dupes, f"doctor reports duplicate box ids: {_dupes}"
