# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/integration/sync/test_baseline_convergence.pct.py

__all__ = ['run', 'test_a_box_without_baselines_regains_all_three_on_a_synced_pass', 'test_a_hidden_divergence_is_surfaced_not_blessed']

# %% pts/tests/integration/sync/test_baseline_convergence.pct.py 3
import asyncio
import json

import pytest

from boxyard._enums import BoxPart
from boxyard._fingerprint import base_path_for
from boxyard._models import SyncCondition, get_boxyard_meta
from boxyard.cmds import new_box, sync_box
from boxyard.config import get_config

from ...integration.conftest import create_boxyards


def run(coro):
    return asyncio.run(coro)


def _sidecars(config, idx):
    bm = get_boxyard_meta(config, force_create=True).by_index_name[idx]
    return {
        part: base_path_for(bm.get_local_sync_record_path(config, part))
        for part in BoxPart
    }


def _usable(base_path, rec_path) -> bool:
    base = json.loads(base_path.read_text())
    rec = json.loads(rec_path.read_text())
    return base["sync_record_ulid"] == rec["ulid"]

# %% pts/tests/integration/sync/test_baseline_convergence.pct.py 4
@pytest.mark.integration
def test_a_box_without_baselines_regains_all_three_on_a_synced_pass():
    """
    The upgrade path: records exist (the box has synced for years), sidecars
    do not (they postdate 0.8.0). One SYNCED pass must establish all three —
    META and CONF by blessing, DATA through the probe.
    """
    remote_name, remote_root, config, config_path, _dp = create_boxyards()
    idx = new_box(config_path=config_path, box_name="convergence",
                  storage_location=remote_name)
    config = get_config(config_path)
    bm = get_boxyard_meta(config, force_create=True).by_index_name[idx]
    (bm.get_local_part_path(config, BoxPart.DATA) / "work.txt").write_text("w")
    conf_dir = bm.get_local_part_path(config, BoxPart.CONF)
    conf_dir.mkdir(parents=True, exist_ok=True)
    (conf_dir / "keep.txt").write_text("conf")
    run(sync_box(config_path=config_path, box_index_name=idx, verbose=False))

    # Simulate a machine that synced before the fingerprint existed.
    sidecars = _sidecars(config, idx)
    for p in sidecars.values():
        p.unlink()

    results = run(sync_box(config_path=config_path, box_index_name=idx, verbose=False))
    for part in BoxPart:
        assert results[part][0].sync_condition is SyncCondition.SYNCED
        assert results[part][1] is False  # nothing was transferred

    for part in BoxPart:
        assert sidecars[part].exists(), f"{part.value} baseline was not established"
        assert _usable(
            sidecars[part], bm.get_local_sync_record_path(config, part)
        ), f"{part.value} baseline is not bound to the current record"

# %% pts/tests/integration/sync/test_baseline_convergence.pct.py 5
@pytest.mark.integration
def test_a_hidden_divergence_is_surfaced_not_blessed(capsys):
    """
    The reason DATA does not simply bless: a box whose local and remote
    actually differ — invisibly to the mtime test — must come out of this as a
    WARNING and no baseline, never as a baseline that makes the divergence
    permanent.
    """
    remote_name, remote_root, config, config_path, _dp = create_boxyards()
    idx = new_box(config_path=config_path, box_name="diverged",
                  storage_location=remote_name)
    config = get_config(config_path)
    bm = get_boxyard_meta(config, force_create=True).by_index_name[idx]
    data = bm.get_local_part_path(config, BoxPart.DATA)
    (data / "kept.txt").write_text("kept")
    (data / "stranded.txt").write_text("never made it")
    run(sync_box(config_path=config_path, box_index_name=idx, verbose=False))

    # Manufacture the historical state: the remote lost a file nobody
    # noticed, and this machine has no baseline to see it with.
    data_sidecar = _sidecars(config, idx)[BoxPart.DATA]
    data_sidecar.unlink()
    _remote_stranded = (
        remote_root / "boxyard" / "boxes" / idx / "data" / "stranded.txt"
    )
    assert _remote_stranded.exists()
    _remote_stranded.unlink()

    capsys.readouterr()
    results = run(sync_box(config_path=config_path, box_index_name=idx, verbose=False))
    out = capsys.readouterr().out

    assert results[BoxPart.DATA][0].sync_condition is SyncCondition.SYNCED
    assert "actually differ" in out, "the divergence went unreported"
    assert not data_sidecar.exists(), (
        "a baseline was written over a real divergence, making it permanent"
    )
