package parity

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

// RealRcloneConfigPath is the user's rclone config. The parity suite copies the
// remote definition out of it (read-only) so it can reach the same storage box.
const RealRcloneConfigPath = "~/.config/boxyard/boxyard_rclone.conf"

// RealRemoteName is the rclone remote holding both the real yard and the test
// prefix. Isolation comes from the path within it, not from a separate remote.
const RealRemoteName = "hetzner-box"

// TestRemoteName is the alias remote the sandbox defines. See newRcloneConfig
// for why an alias is used rather than pointing straight at RealRemoteName.
const TestRemoteName = "boxyard-test"

// runID returns a short random token so concurrent or repeated parity runs
// never share remote state.
func runID() (string, error) {
	b := make([]byte, 4)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

// NewSandbox builds an isolated boxyard rooted at localRoot. It does not touch
// the filesystem or the remote; call Provision for that.
func NewSandbox(localRoot string) (*Sandbox, error) {
	id, err := runID()
	if err != nil {
		return nil, err
	}
	storePath := "run-" + id
	s := &Sandbox{
		Root:           localRoot,
		ConfigPath:     filepath.Join(localRoot, "config", "config.toml"),
		DataPath:       filepath.Join(localRoot, "data"),
		UserBoxesPath:  filepath.Join(localRoot, "boxes"),
		UserGroupsPath: filepath.Join(localRoot, "groups"),
		// RemotePrefix is the EFFECTIVE full path on the real remote, which is
		// what the guard must check. The config below stores only the part
		// after the alias root.
		RemotePrefix: RequiredRemotePrefix + storePath,
		RcloneConfig: filepath.Join(localRoot, "config", "boxyard_rclone.conf"),
	}
	s.storePath = storePath
	return s, nil
}

// storePath is the store_path written into the sandbox's config.toml. It is
// relative to the alias remote's root (RequiredRemotePrefix), so
// RemotePrefix == RequiredRemotePrefix + storePath by construction.
func (s *Sandbox) StorePath() string { return s.storePath }

// newRcloneConfig builds the sandbox's rclone config: the real remote's
// definition copied verbatim, plus an ALIAS remote rooted at the test prefix.
//
// The alias is a genuine safety layer, not a convenience. The AssertSandboxed
// guard validates configuration INPUTS, but it cannot see paths that boxyard
// constructs at runtime — a bug in, say, rename's path joining could in
// principle walk out of the test prefix. Because the alias's root IS the test
// prefix, every path boxyard hands to rclone is resolved beneath it.
func (s *Sandbox) newRcloneConfig() (string, error) {
	realPath, err := expand(RealRcloneConfigPath)
	if err != nil {
		return "", err
	}
	raw, err := os.ReadFile(realPath)
	if err != nil {
		return "", fmt.Errorf("cannot read rclone config %s: %w", realPath, err)
	}

	section, err := extractSection(string(raw), RealRemoteName)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Generated by the boxyard parity suite. Do not edit.\n")
	b.WriteString("# The remote below is copied from the user's real rclone config.\n")
	b.WriteString(section)
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("# Alias rooted at the test prefix, so no path boxyard builds\n"+
		"# can resolve outside %s.\n", RequiredRemotePrefix))
	b.WriteString(fmt.Sprintf("[%s]\ntype = alias\nremote = %s:%s\n",
		TestRemoteName, RealRemoteName, strings.TrimSuffix(RequiredRemotePrefix, "/")))
	return b.String(), nil
}

// extractSection returns the named INI section from an rclone config, including
// its header line, up to the next section header.
func extractSection(cfg, name string) (string, error) {
	lines := strings.Split(cfg, "\n")
	header := "[" + name + "]"
	start := -1
	for i, l := range lines {
		if strings.TrimSpace(l) == header {
			start = i
			break
		}
	}
	if start < 0 {
		return "", fmt.Errorf("rclone config has no [%s] section", name)
	}
	end := len(lines)
	for i := start + 1; i < len(lines); i++ {
		t := strings.TrimSpace(lines[i])
		if strings.HasPrefix(t, "[") && strings.HasSuffix(t, "]") {
			end = i
			break
		}
	}
	return strings.Join(lines[start:end], "\n"), nil
}

// configTOML renders the sandbox's boxyard config.
func (s *Sandbox) configTOML() string {
	return fmt.Sprintf(`# Generated by the boxyard parity suite. Do not edit.
default_storage_location = %q
boxyard_data_path = %q
box_timestamp_format = "date_only"
user_boxes_path = %q
user_box_groups_path = %q
default_box_groups = []
box_subid_character_set = "abcdefghijklmnopqrstuvwxyz0123456789"
box_subid_length = 6
max_concurrent_rclone_ops = 2
box_groups = {}
virtual_box_groups = {}

[storage_locations.%s]
storage_type = "rclone"
store_path = %q
`, TestRemoteName, s.DataPath, s.UserBoxesPath, s.UserGroupsPath, TestRemoteName, s.storePath)
}

// Provision creates the sandbox on disk and on the remote. It refuses to do
// anything until AssertSandboxed passes.
func (s *Sandbox) Provision() error {
	if err := AssertSandboxed(s); err != nil {
		return err
	}
	// Belt and braces: the config's store_path must compose to exactly the
	// prefix the guard just approved.
	if RequiredRemotePrefix+s.storePath != s.RemotePrefix {
		return fmt.Errorf("parity guard: store_path %q does not compose to the approved prefix %q",
			s.storePath, s.RemotePrefix)
	}

	for _, d := range []string{
		filepath.Dir(s.ConfigPath), s.DataPath, s.UserBoxesPath, s.UserGroupsPath,
	} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return err
		}
	}

	rc, err := s.newRcloneConfig()
	if err != nil {
		return err
	}
	// 0600: this file carries the storage box credentials.
	if err := os.WriteFile(s.RcloneConfig, []byte(rc), 0o600); err != nil {
		return err
	}
	if err := os.WriteFile(s.ConfigPath, []byte(s.configTOML()), 0o644); err != nil {
		return err
	}
	return nil
}

// Env returns the environment a boxyard binary must run with to see only the
// sandbox. BOXYARD_CONFIG_PATH is honoured by both implementations.
func (s *Sandbox) Env() []string {
	env := os.Environ()
	out := env[:0:0]
	for _, e := range env {
		// Strip anything that could pull the process back to the real yard.
		if strings.HasPrefix(e, "BOXYARD_CONFIG_PATH=") ||
			strings.HasPrefix(e, "DEFAULT_BOX_GROUPS=") {
			continue
		}
		out = append(out, e)
	}
	out = append(out, "BOXYARD_CONFIG_PATH="+s.ConfigPath)
	return out
}

// rclone runs an rclone command against the sandbox's own rclone config.
func (s *Sandbox) rclone(args ...string) (string, error) {
	full := append([]string{"--config", s.RcloneConfig}, args...)
	cmd := exec.Command("rclone", full...)
	cmd.Env = s.Env()
	out, err := cmd.CombinedOutput()
	if err != nil {
		return string(out), fmt.Errorf("rclone %s: %w\n%s", strings.Join(args, " "), err, out)
	}
	return string(out), nil
}

// Teardown removes the sandbox's remote directory. The local root is a temp
// dir and is cleaned up by the caller.
//
// It re-runs the guard first: a teardown that purges the wrong path is the
// worst possible bug in this file.
func (s *Sandbox) Teardown() error {
	if err := AssertSandboxed(s); err != nil {
		return fmt.Errorf("refusing to tear down: %w", err)
	}
	// Purge through the ALIAS, addressing only the run subdirectory, so the
	// deepest path this can ever name is <alias root>/run-xxxx.
	if _, err := s.rclone("purge", TestRemoteName+":"+s.storePath); err != nil {
		// A run that created nothing has nothing to purge.
		if strings.Contains(err.Error(), "directory not found") {
			return nil
		}
		return err
	}
	return nil
}

// RemoteTree lists every path under the sandbox's remote prefix, for asserting
// that two implementations produced the same remote layout.
func (s *Sandbox) RemoteTree() ([]string, error) {
	out, err := s.rclone("lsf", "-R", "--dirs-only=false", TestRemoteName+":"+s.storePath)
	if err != nil {
		if strings.Contains(err.Error(), "directory not found") {
			return nil, nil
		}
		return nil, err
	}
	var paths []string
	for _, l := range strings.Split(out, "\n") {
		if l = strings.TrimSpace(l); l != "" {
			paths = append(paths, l)
		}
	}
	return paths, nil
}

// WaitForRemote gives the SFTP backend a moment to settle. Used sparingly.
func WaitForRemote() { time.Sleep(250 * time.Millisecond) }
