# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/integration/cmds/test_delete_and_parent_cleanup.pct.py

__all__ = ['test_delete_removes_sync_records', 'test_remove_parent_drops_dangling_parent', 'test_remove_parent_reports_when_not_a_parent']

# %% pts/tests/integration/cmds/test_delete_and_parent_cleanup.pct.py 2
import asyncio

import pytest

from boxyard.cmds import new_box, sync_box, delete_box, modify_boxmeta
from boxyard._models import get_boxyard_meta, BoxPart

# %% pts/tests/integration/cmds/test_delete_and_parent_cleanup.pct.py 3
@pytest.mark.integration
def test_delete_removes_sync_records(temp_boxyard):
    """boxyard#13: deleting a box also removes its sync-record directory."""
    remote_name, remote_rclone_path, config, config_path, data_path = temp_boxyard

    idx = new_box(config_path=config_path, box_name="rec-box", storage_location=remote_name)
    asyncio.run(sync_box(config_path=config_path, box_index_name=idx))

    bm = get_boxyard_meta(config).by_index_name[idx]
    local_sync_dir = bm.get_local_sync_record_path(config, BoxPart.DATA).parent
    assert local_sync_dir.exists(), "sync should have created local sync records"

    asyncio.run(delete_box(config_path=config_path, box_index_name=idx))

    assert not local_sync_dir.exists(), "delete must not leave orphaned sync records"

# %% pts/tests/integration/cmds/test_delete_and_parent_cleanup.pct.py 4
@pytest.mark.integration
def test_remove_parent_drops_dangling_parent(temp_boxyard):
    """boxyard#14: `remove-parent --parent-id` drops a parent whose box no longer exists."""
    from typer.testing import CliRunner
    from boxyard._cli.main import app

    remote_name, remote_rclone_path, config, config_path, data_path = temp_boxyard
    runner = CliRunner()

    child = new_box(config_path=config_path, box_name="child", storage_location=remote_name)

    # Point the child at a parent id that does not correspond to any existing box —
    # exactly the state a deleted parent leaves behind (modify_boxmeta warns but allows it).
    fake_parent_id = "20200101_000000_zzzzz"
    modify_boxmeta(
        config_path=config_path,
        box_index_name=child,
        modifications={"parents": [fake_parent_id]},
    )
    assert fake_parent_id in get_boxyard_meta(config).by_index_name[child].parents

    # Before the fix this errored with "Box with id ... not found". Now it succeeds.
    result = runner.invoke(
        app,
        ["--config", str(config_path), "remove-parent", "-r", child,
         "--parent-id", fake_parent_id, "--no-refresh-user-symlinks"],
    )
    assert result.exit_code == 0, result.output
    assert get_boxyard_meta(config).by_index_name[child].parents == []

# %% pts/tests/integration/cmds/test_delete_and_parent_cleanup.pct.py 5
@pytest.mark.integration
def test_remove_parent_reports_when_not_a_parent(temp_boxyard):
    """Removing a parent id the box doesn't have still fails cleanly (exit 1)."""
    from typer.testing import CliRunner
    from boxyard._cli.main import app

    remote_name, remote_rclone_path, config, config_path, data_path = temp_boxyard
    runner = CliRunner()

    child = new_box(config_path=config_path, box_name="child2", storage_location=remote_name)
    result = runner.invoke(
        app,
        ["--config", str(config_path), "remove-parent", "-r", child,
         "--parent-id", "20200101_000000_zzzzz", "--no-refresh-user-symlinks"],
    )
    assert result.exit_code == 1
    assert "does not have parent" in result.output
