# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/integration/cmds/test_new_box_claims.pct.py

__all__ = ['test_new_box_claims_for_this_machine', 'test_no_claim_leaves_it_unowned', 'test_the_env_override_is_enough_to_claim', 'test_without_a_machine_name_the_box_is_still_created']

# %% pts/tests/integration/cmds/test_new_box_claims.pct.py 2
import tomllib

import pytest
import tomli_w

from boxyard import const
from boxyard.cmds import new_box
from boxyard._models import get_boxyard_meta
from boxyard.config import get_config


def _boxmeta(config, index_name):
    return tomllib.loads(
        (
            config.local_store_path
            / config.default_storage_location
            / index_name
            / const.BOX_METAFILE_REL_PATH
        ).read_text()
    )


def _drop_machine_name(config_path):
    cfg = tomllib.loads(config_path.read_text())
    cfg.pop("machine_name", None)
    config_path.write_text(tomli_w.dumps(cfg))

# %% pts/tests/integration/cmds/test_new_box_claims.pct.py 4
@pytest.mark.integration
def test_new_box_claims_for_this_machine(temp_boxyard):
    _, _, _, config_path, _ = temp_boxyard
    index_name = new_box(config_path=config_path, box_name="mine")

    config = get_config(config_path)
    assert config.machine_name, "the fixture must set a machine name or this proves nothing"
    assert _boxmeta(config, index_name)["write_owner"] == config.machine_name
    assert get_boxyard_meta(config, force_create=True).by_index_name[
        index_name
    ].write_owner == config.machine_name


@pytest.mark.integration
def test_no_claim_leaves_it_unowned(temp_boxyard):
    """For a box created here that will be worked on elsewhere."""
    _, _, _, config_path, _ = temp_boxyard
    index_name = new_box(config_path=config_path, box_name="theirs", claim=False)

    config = get_config(config_path)
    # ABSENT, not empty: an unowned box omits the key entirely, which is what
    # keeps every pre-0.5 boxmeta byte-identical.
    assert "write_owner" not in _boxmeta(config, index_name)

# %% pts/tests/integration/cmds/test_new_box_claims.pct.py 6
@pytest.mark.integration
def test_without_a_machine_name_the_box_is_still_created(temp_boxyard, monkeypatch, capsys):
    _, _, _, config_path, _ = temp_boxyard
    _drop_machine_name(config_path)
    monkeypatch.delenv(const.ENV_VAR_BOXYARD_MACHINE_NAME, raising=False)

    index_name = new_box(config_path=config_path, box_name="nameless")

    config = get_config(config_path)
    assert config.machine_name is None
    # Created, not refused. A machine with no `machine_name` is an expected
    # state — the myrig template deliberately emits no key for a machine that
    # is not in its machines list — and refusing to create a box over an
    # ownership setting would be wildly out of proportion.
    assert index_name in get_boxyard_meta(config, force_create=True).by_index_name
    assert "write_owner" not in _boxmeta(config, index_name)
    # But NOT silent.
    assert "no `machine_name`" in capsys.readouterr().out


@pytest.mark.integration
def test_the_env_override_is_enough_to_claim(temp_boxyard, monkeypatch):
    """BOXYARD_MACHINE_NAME already exists, so `new` needs no flag of its own."""
    _, _, _, config_path, _ = temp_boxyard
    _drop_machine_name(config_path)
    monkeypatch.setenv(const.ENV_VAR_BOXYARD_MACHINE_NAME, "from-the-env")

    index_name = new_box(config_path=config_path, box_name="env-owned")
    assert _boxmeta(get_config(config_path), index_name)["write_owner"] == "from-the-env"
