# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/integration/cmds/test_meta_skip_filter.pct.py

__all__ = ['RemoteCallCounter', 'test_a_box_missing_from_the_listing_is_never_skipped', 'test_a_box_that_failed_is_never_stamped', 'test_a_box_with_no_merge_base_is_never_skipped', 'test_an_unchanged_box_is_skippable', 'test_the_filter_collapses_a_clean_pass', 'test_the_filter_still_syncs_a_box_whose_local_meta_changed']

# %% pts/tests/integration/cmds/test_meta_skip_filter.pct.py 2
import time

import pytest
import tomli_w
import tomllib

from boxyard._enums import BoxPart
from boxyard._models import get_boxyard_meta, read_meta_base
from boxyard._sync_policy import (
    local_meta_differs_from_base,
    meta_boxes_needing_sync,
    read_check_record,
    write_check_record,
)
from boxyard.cmds import modify_boxmeta, new_box


def _make_box(config_path, remote_name, name):
    return new_box(
        config_path=config_path,
        box_name=name,
        storage_location=remote_name,
        verbose=False,
        claim=False,
    )


def _run(config_path, *args):
    from typer.testing import CliRunner

    from boxyard._cli.app import app

    result = CliRunner().invoke(
        app, ["--config", str(config_path), "multi-sync", *args]
    )
    assert result.exit_code == 0, f"exited {result.exit_code}\n{result.output}"
    return result

# %% pts/tests/integration/cmds/test_meta_skip_filter.pct.py 4
class RemoteCallCounter:
    def __init__(self, monkeypatch):
        import boxyard._utils.rclone as rclone_module

        self.calls = []
        self._original = rclone_module.run_cmd_async

        async def _counting(cmd, *args, **kwargs):
            self.calls.append(cmd)
            return await self._original(cmd, *args, **kwargs)

        monkeypatch.setattr(rclone_module, "run_cmd_async", _counting)

    def __len__(self):
        return len(self.calls)

# %% pts/tests/integration/cmds/test_meta_skip_filter.pct.py 6
def test_the_filter_collapses_a_clean_pass(temp_boxyard, monkeypatch):
    """
    With nothing changed on either side, a filtered META pass must cost far
    less than an unfiltered one. If this ever regresses, the whole point of
    B-prime is gone and the fast loop is back to ~6.6 min on the real yard.
    """
    remote_name, _, config, config_path, _ = temp_boxyard
    for i in range(5):
        _make_box(config_path, remote_name, f"box-{i}")

    # Sync once so both sides agree and the check records exist.
    _run(config_path, "-c", "meta")
    _run(config_path, "-c", "meta", "--skip-unchanged-meta")

    unfiltered = RemoteCallCounter(monkeypatch)
    _run(config_path, "-c", "meta")
    unfiltered_calls = len(unfiltered)

    filtered = RemoteCallCounter(monkeypatch)
    _run(config_path, "-c", "meta", "--skip-unchanged-meta")
    filtered_calls = len(filtered)

    print(
        f"\n  5 boxes, nothing changed: "
        f"unfiltered={unfiltered_calls} remote calls, "
        f"filtered={filtered_calls}"
    )
    assert unfiltered_calls > 0, "the counter caught nothing -- it is vacuous"
    assert filtered_calls < unfiltered_calls, (
        f"the filter saved nothing: {filtered_calls} vs {unfiltered_calls}"
    )
    # The filter's cost is a FIXED two listings; the unfiltered pass grows with
    # the box count. Asserting a ratio rather than "fewer" keeps the test
    # meaningful: on the real 590-box yard this is ~1,180 calls against ~2.
    assert filtered_calls <= unfiltered_calls / 2, (
        f"the filter saved only {unfiltered_calls - filtered_calls} of "
        f"{unfiltered_calls} calls; expected at least half"
    )


def test_the_filter_still_syncs_a_box_whose_local_meta_changed(temp_boxyard):
    """
    A local edit must reach the remote even though the remote has not moved.
    This is the half a naive remote-only filter would silently drop -- fast
    inbox, dead outbox.
    """
    remote_name, _, config, config_path, _ = temp_boxyard
    index_name = _make_box(config_path, remote_name, "edited-box")
    _run(config_path, "-c", "meta", "--skip-unchanged-meta")

    config = get_boxyard_meta(config) and config
    metas = get_boxyard_meta(config).box_metas
    meta = next(m for m in metas if m.index_name == index_name)
    assert not local_meta_differs_from_base(config, meta), "should start agreed"

    modify_boxmeta(
        config_path=config_path,
        box_index_name=index_name,
        modifications={"groups": ["a-new-group"]},
    )
    metas = get_boxyard_meta(config).box_metas
    meta = next(m for m in metas if m.index_name == index_name)
    assert local_meta_differs_from_base(config, meta), (
        "a local edit was not detected -- it would never be pushed"
    )

    needed, skipped = meta_boxes_needing_sync(
        config, [meta], {index_name: _remote_stamp(config, index_name)}
    )
    assert needed == [index_name]
    assert skipped == []


def _remote_stamp(config, index_name):
    """The (ModTime, Size) the check record last saw, i.e. 'remote unmoved'."""
    record = read_check_record(config, index_name, BoxPart.META)
    if record is None:
        return (None, None)
    return (record.get("remote_modtime"), record.get("remote_size"))

# %% pts/tests/integration/cmds/test_meta_skip_filter.pct.py 8
def test_a_box_missing_from_the_listing_is_never_skipped(temp_boxyard):
    """
    Absent from the bulk listing means new here, deleted there, or on a storage
    location the listing did not cover. Every one of those wants the real sync
    path to look.
    """
    remote_name, _, config, config_path, _ = temp_boxyard
    index_name = _make_box(config_path, remote_name, "ghost-box")
    _run(config_path, "-c", "meta", "--skip-unchanged-meta")

    metas = get_boxyard_meta(config).box_metas
    needed, skipped = meta_boxes_needing_sync(config, metas, {})
    assert needed == [index_name]
    assert skipped == []


def test_a_box_with_no_merge_base_is_never_skipped(temp_boxyard):
    """
    No base means "cannot tell whether there is a local edit", which must cost
    a sync rather than skip one. This is what makes the upgrade safe: every box
    is checked once, then settles.
    """
    remote_name, _, config, config_path, _ = temp_boxyard
    index_name = _make_box(config_path, remote_name, "baseless-box")
    _run(config_path, "-c", "meta", "--skip-unchanged-meta")

    metas = get_boxyard_meta(config).box_metas
    meta = metas[0]
    base_path = meta.get_local_meta_base_path(config)
    assert base_path.exists()
    base_path.unlink()

    needed, _ = meta_boxes_needing_sync(
        config, [meta], {index_name: _remote_stamp(config, index_name)}
    )
    assert needed == [index_name]


def test_an_unchanged_box_is_skippable(temp_boxyard):
    """The positive case -- without it the tests above could all pass vacuously."""
    remote_name, _, config, config_path, _ = temp_boxyard
    index_name = _make_box(config_path, remote_name, "quiet-box")
    _run(config_path, "-c", "meta", "--skip-unchanged-meta")

    metas = get_boxyard_meta(config).box_metas
    meta = metas[0]
    needed, skipped = meta_boxes_needing_sync(
        config, [meta], {index_name: _remote_stamp(config, index_name)}
    )
    assert skipped == [index_name], (needed, skipped)
    assert needed == []


def test_a_box_that_failed_is_never_stamped(temp_boxyard, monkeypatch):
    """
    The most dangerous wrong answer this filter could give.

    The post-pass stamping records "the remote looked like this when we
    reconciled". Stamping a box whose sync ERRORED would record a
    reconciliation that never happened -- and because the stamp is what makes a
    box skippable, that box would be skipped on every subsequent pass. A box
    that fails once would go silently un-synced forever, reporting nothing.

    Constructed so the two outcomes are DISTINGUISHABLE: sync cleanly first so
    a stamp exists, then move the remote boxmeta so the listing reports a new
    one, then fail the sync. A correct pass leaves the OLD stamp (box still
    needs work); a pass that stamps regardless adopts the new one (box goes
    quiet).
    """
    import os

    import boxyard.cmds as cmds_module

    remote_name, remote_rclone_path, config, config_path, _ = temp_boxyard
    index_name = _make_box(config_path, remote_name, "doomed-box")
    _run(config_path, "-c", "meta", "--skip-unchanged-meta")

    before = read_check_record(config, index_name, BoxPart.META)
    assert before is not None and before.get("remote_modtime") is not None, (
        "setup failed: the clean pass did not stamp the box"
    )

    # Move the remote's boxmeta on, so a wrongful stamp would be visibly different.
    remote_meta = (
        remote_rclone_path / "boxyard" / "boxes" / index_name / "boxmeta.toml"
    )
    assert remote_meta.exists(), remote_meta
    remote_meta.write_text(remote_meta.read_text() + "\n# nudged\n")
    os.utime(remote_meta, (time.time() + 120, time.time() + 120))

    async def _explode(*args, **kwargs):
        raise RuntimeError("remote went away")

    monkeypatch.setattr(cmds_module, "sync_box", _explode)
    _run(config_path, "-c", "meta", "--skip-unchanged-meta")

    after = read_check_record(config, index_name, BoxPart.META)
    assert after["remote_modtime"] == before["remote_modtime"], (
        "a box whose sync FAILED adopted the remote's new stamp; it would now "
        f"be skipped on every future pass. before={before!r} after={after!r}"
    )

    # ...and it is still selected next time.
    metas = get_boxyard_meta(config).box_metas
    needed, skipped = meta_boxes_needing_sync(
        config, metas, {index_name: ("2026-01-01T00:00:00Z", 123)}
    )
    assert needed == [index_name]
    assert skipped == []
