# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/integration/cmds/test_rollout_pin.pct.py

__all__ = ['create_and_read_format', 'doctor_findings', 'pytestmark', 'remote_yard', 'set_policies', 'test_a_pinned_machine_reports_no_format_mismatch', 'test_a_policy_table_without_the_key_also_means_the_module_constant', 'test_an_unknown_policy_key_is_tolerated_not_fatal', 'test_an_unpinned_machine_reports_a_mismatch_for_every_plain_box', 'test_deleting_the_pin_is_the_flip', 'test_no_policy_table_at_all_means_the_module_constant', 'test_the_config_pin_beats_the_module_constant']

# %% pts/tests/integration/cmds/test_rollout_pin.pct.py 2
import tomllib
from pathlib import Path

import tomli_w

import pytest

from boxyard._enums import BoxPart, StorageFormat
from boxyard._models import get_boxyard_meta
from boxyard._sync_policy import DEFAULT_STORAGE_FORMAT, resolve_policy
from boxyard.cmds import new_box
from boxyard.config import get_config

pytestmark = [pytest.mark.integration]

# %% pts/tests/integration/cmds/test_rollout_pin.pct.py 3
@pytest.fixture
def remote_yard(monkeypatch, tmp_path):
    """
    One yard whose storage location is of type `rclone` -- i.e. the case the
    module constant answers RESTIC for. A `local` location would default to
    plain for its own reasons and would prove nothing about the pin.

    The password is set because creating a restic box requires one; without it
    `new_box` refuses, and these tests would pass for the wrong reason.
    """
    from ...integration.conftest import create_boxyards

    monkeypatch.setenv("BOXYARD_RESTIC_PASSWORD", "rollout-pin-test-password")
    # With `num_boxyards=1` this returns the flattened 5-tuple, not a list.
    remote_name, _remote_root, _cfg, config_path, _data = create_boxyards(
        num_boxyards=1
    )
    return {"config_path": config_path, "remote_name": remote_name}


def set_policies(config_path, policies):
    """Rewrite the config's `[sync_policies]` table wholesale.

    `policies=None` removes the table entirely, which is what every machine in
    the fleet looks like today.
    """
    dump = tomllib.loads(Path(config_path).read_text())
    if policies is None:
        dump.pop("sync_policies", None)
    else:
        dump["sync_policies"] = policies
    Path(config_path).write_text(tomli_w.dumps(dump))


def create_and_read_format(yard, box_name):
    """Create a box; report the stamped format and the boxmeta as written.

    Read back from the boxmeta on disk, not from the return value: what governs
    the box for the rest of its life is the stamped field, and a test that
    asserted on a freshly resolved policy could pass while nothing was written.
    """
    config_path = yard["config_path"]
    idx = new_box(config_path=config_path, box_name=box_name,
                  storage_location=yard["remote_name"], claim=False)
    config = get_config(config_path)
    box = get_boxyard_meta(config).by_index_name[idx]
    on_disk = tomllib.loads(
        box.get_local_part_path(config, BoxPart.META).read_text()
    )
    return box.storage_format, on_disk, config, box

# %% pts/tests/integration/cmds/test_rollout_pin.pct.py 5
def test_the_config_pin_beats_the_module_constant(remote_yard):
    """
    THE load-bearing test. With `storage_format = "plain"` in config, a new box
    on a remote storage location is created PLAIN even though the module
    constant says RESTIC.

    The assertion on the constant is not decoration: without it a future edit
    setting `DEFAULT_STORAGE_FORMAT = PLAIN` would leave this test passing while
    proving nothing at all about the pin.
    """
    assert DEFAULT_STORAGE_FORMAT is StorageFormat.RESTIC, (
        "this test only means something while the constant disagrees with the pin"
    )
    set_policies(remote_yard["config_path"],
                 {"default": {"storage_format": "plain"}})

    stamped, on_disk_keys, config, box = create_and_read_format(
        remote_yard, "pinned"
    )

    assert stamped is StorageFormat.PLAIN
    assert resolve_policy(config, box).storage_format is StorageFormat.PLAIN
    assert box.get_local_part_path(config, BoxPart.DATA).is_dir(), (
        "a plain box keeps a real DATA directory -- the point of pinning"
    )
    # A plain box OMITS the key rather than writing `storage_format = "plain"`
    # (`_models.py`: "a plain box writes the file every earlier version
    # wrote"). That is worth more to this rollout than a written key would be:
    # during the pin window a 0.7.0 machine produces boxmetas byte-identical to
    # 0.6.x's, so pocket4 sees nothing new at all -- not even the
    # `unknown-boxmeta-keys` that a restic box would give it.
    assert "storage_format" not in on_disk_keys, (
        "the pin must leave the boxmeta indistinguishable from a 0.6.x one"
    )


def test_deleting_the_pin_is_the_flip(remote_yard):
    """
    The same yard and the same creation with the stanza removed yields RESTIC.
    Paired with the test above deliberately: together they are the rollout, and
    the only difference between them is the one line a person deletes.
    """
    set_policies(remote_yard["config_path"], {"default": {}})

    stamped, on_disk, _config, _box = create_and_read_format(
        remote_yard, "unpinned"
    )

    assert stamped is StorageFormat.RESTIC
    assert on_disk["storage_format"] == "restic", (
        "a restic box must WRITE the key -- that is what tells a stale machine "
        "something is different, via `unknown-boxmeta-keys`"
    )

# %% pts/tests/integration/cmds/test_rollout_pin.pct.py 7
def test_no_policy_table_at_all_means_the_module_constant(remote_yard):
    """
    Answers the rollout question directly: an absent table means CONSTANT, so
    on 0.7.0 it means RESTIC. This is the unsafe reading of the two, and it is
    the one that is true.

    So the pin must be ADDED to every machine's config. Deploying 0.7.0 without
    the template change would flip the default on the four reachable machines
    the moment it landed -- which is exactly the coupling the decoupled rollout
    exists to avoid.
    """
    set_policies(remote_yard["config_path"], None)

    config = get_config(remote_yard["config_path"])
    assert config.sync_policies == {}, "precondition: this is a fleet machine today"

    stamped, on_disk, _config, _box = create_and_read_format(
        remote_yard, "notable"
    )

    assert stamped is StorageFormat.RESTIC
    assert on_disk["storage_format"] == "restic", (
        "a restic box must WRITE the key -- that is what tells a stale machine "
        "something is different, via `unknown-boxmeta-keys`"
    )


def test_a_policy_table_without_the_key_also_means_the_module_constant(remote_yard):
    """
    The sharper case, and the one a person is most likely to get wrong: a
    machine that already carries a `[sync_policies.default]` for CADENCE is not
    pinned. `None` means "not stated at this level" per dimension, so an
    unrelated policy stanza gives no protection whatsoever.

    A rollout check of the shape "does this machine have a `[sync_policies]`
    table?" would therefore pass on a machine that is about to create restic
    boxes. The check has to be for the KEY.
    """
    set_policies(remote_yard["config_path"],
                 {"default": {"data_interval": "6h"}})

    config = get_config(remote_yard["config_path"])
    assert config.sync_policies["default"].storage_format is None
    assert config.sync_policies["default"].data_interval == "6h"

    stamped, on_disk, _config, _box = create_and_read_format(
        remote_yard, "cadenceonly"
    )

    assert stamped is StorageFormat.RESTIC
    assert on_disk["storage_format"] == "restic", (
        "a restic box must WRITE the key -- that is what tells a stale machine "
        "something is different, via `unknown-boxmeta-keys`"
    )

# %% pts/tests/integration/cmds/test_rollout_pin.pct.py 9
def doctor_findings(config_path):
    import asyncio

    from boxyard.cmds import run_doctor

    report = asyncio.run(run_doctor(config_path=config_path, check_remote=False))
    # `report["checks"]` carries EVERY check name whether or not it found
    # anything, so `"x" in report["checks"]` is always true and proves nothing.
    # Return the findings themselves.
    return {
        name: entry["findings"]
        for name, entry in report["checks"].items()
        if entry["findings"]
    }


def test_a_pinned_machine_reports_no_format_mismatch(remote_yard):
    """What step 1 and step 2 look like when they pass."""
    set_policies(remote_yard["config_path"],
                 {"default": {"storage_format": "plain"}})
    create_and_read_format(remote_yard, "pinnedbox")

    assert "storage-format-mismatch" not in doctor_findings(
        remote_yard["config_path"]
    ), "a pinned machine has no gap between policy and box"


def test_an_unpinned_machine_reports_a_mismatch_for_every_plain_box(remote_yard):
    """
    The same yard with the pin removed. This is BOTH the failure signal for
    step 1 -- a machine that was deployed without the template change -- and
    the expected state after step 4, where it stops being a warning and becomes
    the migration backlog.

    Which is why the release note has to say so: after the flip this finding
    fires on ~596 boxes at once, and its length must not be read as breakage.
    """
    set_policies(remote_yard["config_path"],
                 {"default": {"storage_format": "plain"}})
    create_and_read_format(remote_yard, "boxone")
    create_and_read_format(remote_yard, "boxtwo")

    set_policies(remote_yard["config_path"], None)

    findings = doctor_findings(remote_yard["config_path"])
    assert "storage-format-mismatch" in findings
    messages = " ".join(str(m) for m in findings["storage-format-mismatch"])
    assert "boxone" in messages and "boxtwo" in messages, (
        "it fires per box, not once -- that is what makes it a backlog"
    )

# %% pts/tests/integration/cmds/test_rollout_pin.pct.py 11
def test_an_unknown_policy_key_is_tolerated_not_fatal(remote_yard):
    """
    A key `SyncPolicyConfig` does not declare must land in `unknown_keys` and
    leave the config loadable -- which is what lets a pinned config reach a
    machine that predates the key.
    """
    set_policies(remote_yard["config_path"],
                 {"default": {"storage_format": "plain",
                              "a_key_from_the_future": "x"}})

    config = get_config(remote_yard["config_path"])

    assert config.unknown_keys == {
        "sync_policies.default.a_key_from_the_future": "x"
    }, "an unknown policy key must be parked, not rejected and not dropped"
    assert (
        config.sync_policies["default"].storage_format is StorageFormat.PLAIN
    ), "and the keys it DOES know must still take effect"
