# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/unit/test_export_completeness.pct.py

__all__ = ['exported_path', 'repo_root', 'test_every_test_function_reaches_the_exported_module', 'test_the_guard_would_notice_a_dropped_test']

# %% pts/tests/unit/test_export_completeness.pct.py 2
import re
from pathlib import Path

import pytest


def repo_root() -> Path:
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / "pyproject.toml").exists() and (parent / "pts").is_dir():
            return parent
    pytest.skip("not running from a source checkout")


def exported_path(root: Path, pct: Path) -> Path:
    """`pts/tests/a/b.pct.py` -> `src/tests/a/b.py`."""
    rel = pct.relative_to(root / "pts" / "tests")
    return root / "src" / "tests" / rel.with_suffix("").with_suffix(".py")

# %% pts/tests/unit/test_export_completeness.pct.py 3
def test_every_test_function_reaches_the_exported_module():
    """
    The guard. Any test function defined in `pts/` and missing from `src/` is a
    test that cannot possibly have run, however green the suite looked.
    """
    root = repo_root()
    sources = sorted((root / "pts" / "tests").glob("**/*.pct.py"))
    assert sources, "no test sources found -- this guard would pass vacuously"

    missing: list[str] = []
    compared = 0
    for pct in sources:
        exported = exported_path(root, pct)
        defined = set(re.findall(r"^def (test_\w+)", pct.read_text(), re.M))
        if not defined:
            continue
        if not exported.exists():
            missing.append(f"{pct.name}: no exported module at all")
            continue
        present = set(re.findall(r"^\s*def (test_\w+)", exported.read_text(), re.M))
        compared += len(defined)
        for name in sorted(defined - present):
            missing.append(f"{pct.relative_to(root)}: {name}")

    assert compared > 0, "compared nothing -- the guard would pass vacuously"
    assert not missing, (
        "these tests are defined but were never exported, so they do NOT run "
        "(a `# %%` cell without `#|export` is dropped silently):\n  "
        + "\n  ".join(missing)
        + "\nAdd `#|export` to the cell and re-run `nbl export`."
    )


def test_the_guard_would_notice_a_dropped_test(tmp_path):
    """
    The guard checked against itself: a test present in the source and absent
    from the export must be reported. Without this, a bug in the comparison
    would make the guard pass on everything -- which is the same class of
    silent-green failure it exists to prevent.
    """
    root = tmp_path
    (root / "pyproject.toml").write_text("")
    src_dir = root / "pts" / "tests"
    src_dir.mkdir(parents=True)
    (src_dir / "sample.pct.py").write_text(
        "# %%\n#|export\ndef test_kept():\n    pass\n\n"
        "# %%\ndef test_dropped():\n    pass\n"
    )
    out_dir = root / "src" / "tests"
    out_dir.mkdir(parents=True)
    (out_dir / "sample.py").write_text("def test_kept():\n    pass\n")

    pct = src_dir / "sample.pct.py"
    defined = set(re.findall(r"^def (test_\w+)", pct.read_text(), re.M))
    present = set(
        re.findall(r"^\s*def (test_\w+)", exported_path(root, pct).read_text(), re.M)
    )
    assert defined - present == {"test_dropped"}
