# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/unit/models/test_box_name_validation.pct.py

__all__ = ['test_validate_box_name_accepts_valid_names', 'test_validate_box_name_rejects_invalid_names', 'test_validate_box_name_rejects_non_strings']

# %% pts/tests/unit/models/test_box_name_validation.pct.py 2
import pytest

from boxyard._models import validate_box_name

# %% pts/tests/unit/models/test_box_name_validation.pct.py 3
@pytest.mark.parametrize(
    "name",
    [
        "my-box",
        "my_box",
        "lukastk.github.io",
        "box with spaces",
        "20260101-notes",
        "a",
        "name__with__underscores",
    ],
)
def test_validate_box_name_accepts_valid_names(name):
    validate_box_name(name)

# %% pts/tests/unit/models/test_box_name_validation.pct.py 4
@pytest.mark.parametrize(
    "name",
    [
        "/github.com/lukastk/lukastk.github.io",  # the name that broke a real yard
        "github.com/lukastk/lukastk.github.io",
        "nested/name",
        "trailing/",
        "back\\slash",
        "with\0null",
        "",
        ".",
        "..",
        ".hidden",
        " leading-space",
        "trailing-space ",
    ],
)
def test_validate_box_name_rejects_invalid_names(name):
    with pytest.raises(ValueError):
        validate_box_name(name)

# %% pts/tests/unit/models/test_box_name_validation.pct.py 5
def test_validate_box_name_rejects_non_strings():
    with pytest.raises(ValueError):
        validate_box_name(None)
